### ISSUE TITLE
self loops on node do not work with arrow.meta, silently changing arrows to default

### ISSUE THREAD

**Issue by matu3ba** [pgf-tikz/pgf#1008]
**Brief outline of the bug**

Arrow heads of self-loops are not changeable with arrows.meta and instead reset to default. The suggested workaround [here](https://tex.stackexchange.com/a/409884) __only works for__ less beautiful __arrows that are not in arrows.meta__.
Also this creates no warning or error about this behavior and instead breaks silently the layout.

**Minimal working example (MWE)**

```tex
\documentclass[utf8,compress]{beamer}
\usepackage{tikz}
\usetikzlibrary{arrows, arrows.meta, positioning, calc, bending}
\begin{document}
\begin{frame}[t,containsverbatim]{Motivation1} %also working: fragile
\begin{tikzpicture}[-{Stealth}] % This line only correctly works with ...
% standard arrows, ie \begin{tikzpicture}[>=Latex]
\centering
\node [circle,fill=green!50!black!20,draw=green!50!black,] (A) {\scriptsize entry};
\node [circle,fill=blue!50!black!20,draw=green!50!black,] (B) [below=0.5cm of A]{\scriptsize $CP_0$};
\draw[->] (A) -- (B); %[-{Stealth[length=0.3cm]}]
\draw[->] (B)  edge [out=60, in=310, loop] (B); %[-{Stealth[length=0.3cm]}] does not work either
\end{tikzpicture}
\end{frame}
\end{document}
```

**Comment by ilayn** [comment]
pass the arrow specification to edge options

Also relevant questions already answering this issue 

https://tex.stackexchange.com/questions/222403/how-loop-edge-set-the-arrow-type
https://tex.stackexchange.com/questions/295786/what-is-the-reason-that-two-arrows-are-different

**Comment by hmenke** [comment]
```latex
\begin{tikzpicture}[>={Stealth}]
```

**Comment by matu3ba** [comment]
@hmenke @ilayn Is there a specific reason, why there is `[-{Arrowtype}]` and `[>={Arrowtype}]` ?

It would be very nice to deprecate one arrow type to minimize confusion.

**Comment by ilayn** [comment]
`[>={Arrowtype}]` this means "make all arrows `{ArrowType}`"  and you supply this to generic style settings.

`[-{Arrowtype}]` this means "put an end arrow head `{ArrowType}`"  and you supply this style to paths and edges

They are not the same thing.

**Comment by matu3ba** [comment]
@ilayn `[>={Arrowtype}]` also works in `\draw[>={Stealth[length=0.3cm]}] (B)  edge [out=60, in=310, loop] (B);`, so to me it looks like `[-{Arrowtype}]` "should always override" (but does not work for `loop`).

**Comment by ilayn** [comment]
Yes because you are setting the wrong key which happens to be including your use case. Thls also works

``` 
\draw[every path/.style={red}]...... 
``` 

Doesn't mean you should do it. `>` is a shorthand for `every arrow`.if you are not setting all arrows in a scope or tikz picture don't use it and set arrowheads separately. 

Remember edges are separate paths, they won't read the initial arrow from the `\draw`. You need to set in the edge styles as the links above demonstrate
