### ISSUE TITLE
library external: content of \AddToHook in background 

### ISSUE THREAD

**Issue by gitfl1** [pgf-tikz/pgf#1009]
**Brief outline of the bug**

When using externalization library in combination with `\AddToHook`, the content of `\AddToHook` is displayed in the background of the original drawing.

**Minimal working example (MWE)**

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize[/tikz/external/optimize=false]

\AddToHook{shipout/background}{\put(100pt,-100pt){\Huge FooBar}}

\begin{document}

\tikzsetnextfilename{circle}
\begin{tikzpicture}
\draw (0,0) circle [radius=5cm];
\end{tikzpicture}

\end{document}
```

**Comment by hmenke** [comment]
That is completely expected because when you externalize a picture it just recompiles the entire document but throws away everything before and after the picture. My advice, just don't use background drawings with external. The same probably happens with `eso-pic` and `atbegshi`.

**Comment by hmenke** [comment]
This will work around the problem:
```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize[/tikz/external/optimize=false]

\tikzifexternalizing{%
  % no hook in externalized pictures
}{%
  \AddToHook{shipout/background}{\put(100pt,-100pt){\Huge FooBar}}%
}

\begin{document}

\tikzsetnextfilename{circle}
\begin{tikzpicture}
\draw (0,0) circle [radius=5cm];
\end{tikzpicture}

\end{document}
```

**Comment by gitfl1** [comment]
> That is completely expected because when you externalize a picture it just recompiles the entire document but throws away everything before and after the picture. My advice, just don't use background drawings with external. The same probably happens with `eso-pic` and `atbegshi`.

This topic indeed has its origin in the use of the combination of `pdfpages` (which uses `eso-pic`) with the externalization library. Is there any way to overcome this particular case?

**Comment by hmenke** [comment]
That is unrelated to PGF/TikZ. Please consult https://tex.stackexchange.com/ for Q&A.

**Comment by hmenke** [comment]
You can patch `\AddToShipoutPicture` to consult if TikZ is externalizing but `pdfpages` and `eso-pic` are not under our control. Of course the external library could just erase the values of all shipout hook, but this is a whack-a-mole game, because there is always another shipout hook that we did not catch and furthermore this would break all pictures that rely on the current behavior.

**Comment by gitfl1** [comment]
I found a simple solution to the problem while using `pdfpages` by replacing the `\AddToHook` line in your solution with the corresponding `\includepdf` line provided by `pdfpages`. 
Thank you!
