### ISSUE TITLE
Is there a way to generate the manual in A6 paper?

### ISSUE THREAD

**Issue by gutofarias** [pgf-tikz/pgf#1011]
I've been trying to generate the manual in A6 paper format in order to use it with the kindle in a size appropriated to the screen, but with no success. Is there an easy way to accomplish that? Can you give me the steps to make it? 

I did clone the repo and tried to use make in the 'version-for-pdftex', but I got too many errors.

Version:

**Comment by hmenke** [comment]
Use this patch, then compile as usual (also stated in the README)

```patch
--- a/doc/generic/pgf/text-en/pgfmanual-en-main-preamble.tex
+++ b/doc/generic/pgf/text-en/pgfmanual-en-main-preamble.tex
@@ -150,7 +150,7 @@
 \fi
 
 
-\usepackage[a4paper,left=2.25cm,right=2.25cm,top=2.5cm,bottom=2.5cm,nohead]{geometry}
+\usepackage[a6paper,left=2.25cm,right=2.25cm,top=2.5cm,bottom=2.5cm,nohead]{geometry}
 \usepackage{amsmath,amssymb}
 \usepackage{xxcolor}
 \usepackage{pifont}
```

Enjoy the overfull boxes.

**Comment by hmenke** [comment]
I've quickly compiled the LuaTeX version of manual in A6. Enjoy!
https://0x0.st/-B-I.pdf (link expires at some point)

**Comment by gutofarias** [comment]
Thank you!!
Could you be so kind to do it using:
\usepackage[a6paper,left=1.00cm,right=1.00cm,top=1.25cm,bottom=1.25cm,nohead]{geometry}
