### ISSUE TITLE
Tikz External: (large width) figures render with inconsistent glitches

### ISSUE THREAD

**Issue by jeertmans** [pgf-tikz/pgf#1017]
**Brief outline of the bug**

When producing some figures with Tikz externalize, I encounter some inconsistent glitches.
The figure that I want to produce sometimes seems to have a part merged with another pdf that is the front banner (not even generated via Tikz or else). I say *merge with front banner* because it has the exact same color as my front banner and I do not use it elsewhere.

I can solve the problem by either (1) remove externalization on the current figure or (2) reduce the width via `width=...` but none of these solution is optimal when I have more than 80 Tikz figure to externalize :-/

The problem seems to come from the width as the size of the (blue) glitch seems to growth when to width of the figure growth.

**With Externalize, glitches appear**

![2021-05-24_14-38](https://user-images.githubusercontent.com/27275099/119350147-4649dd80-bc9f-11eb-9cac-bc7a05fcb50e.png)

**Without Externalize, no glitch**

![2021-05-24_14-39](https://user-images.githubusercontent.com/27275099/119350194-519d0900-bc9f-11eb-8e04-d8273145f5c7.png)

**Minimal working example (MWE)**

The example here uses *PGFPlots* but the glitches also appear on pure Tikz figures.
Same applies for subfigures: the problem also appears on single figure.

```latex
\documentclass[10pt,twoside]{report}

\usepackage{graphicx} % figures
\usepackage[labelfont=sc]{caption}
\usepackage{subcaption}
\usepackage{float} % add H location
\usepackage{pdfpages} % include pdf pages
\usepackage{geometry}
\geometry{%
letterpaper, % a4paper
left=   18 mm,
right=  30 mm,
top=    25 mm,
bottom= 25 mm,
}

% Lot of tikz and pgfplots packages
\usepackage{tikz,tikz-3dplot}
\usepackage{pgfplots}
% ...
\usepgfplotslibrary{external}
\tikzexternalize[prefix=figures/]

  % Any preamble code goes here

\begin{document}
    % The front banner that I include (do not know why it merges with this)
    \includepdf[pages=1]{template-ucl/EPL-master-thesis-covers-template-EN.pdf}

    % Demonstration of issue here

    \begin{figure}[H]
		\centering
		\begin{subfigure}[b]{0.49\textwidth}
			\tikzsetnextfilename{wifi_obo_status}
                        % or \tikzset{external/export next=false}
			\begin{tikzpicture}
				\begin{axis}[
					view={0}{90},   % not needed for `matrix plot*' variant
					xlabel={Time index},
					ylabel={Channel index},
					colormap name=COLORMAP_STATUS,
					colormap access=direct,
					colorbar horizontal,
					colorbar as palette,
					colorbar style={
						at={(0,1.2)},               % <-- (changed)
						anchor=north west,
						title=Error status,
						xtick={0.5,...,3.5},
						xticklabels={0,...,3},
					},
					enlargelimits=false,
					axis on top,
					point meta min=-.5,
					point meta max=3.5,
				]
					\addplot [matrix plot*,point meta=explicit] table [y=channel, x=index,meta=status] {file1.csv};
				\end{axis}
			\end{tikzpicture}
			\caption{Status}
			\label{fig:wifi_obo_status}
		\end{subfigure}
		\hfill
		\begin{subfigure}[b]{0.49\textwidth}
			\tikzsetnextfilename{wifi-obo-heatmap}
                        % or \tikzset{external/export next=false}
			\begin{tikzpicture}
				\begin{axis}[
					view={0}{90},   % not needed for `matrix plot*' variant
					xlabel={Time index},
					ylabel={Channel index},
					colormap name=COLORMAP_A,
					colorbar horizontal,
					colorbar,
					colorbar style={
						at={(0,1.2)},               % <-- (changed)
						anchor=north west,
						title=\si{\decibel},
					},
					enlargelimits=false,
					axis on top,
					point meta min=-90,
					point meta max=-10,
				]
					\addplot [matrix plot*,point meta=explicit] table [y=channel, x=index,meta=rssi] {file2.csv};
				\end{axis}
			\end{tikzpicture}
			\caption{Heatmap}
			\label{fig:wifi-obo-heatmap}
		\end{subfigure}
		\caption{\todo{}.}
		\label{fig:wifi-obo-1}
	\end{figure}

\end{document}
```

**Comment by hmenke** [comment]
Sounds more like a glitch with `\includegraphics` which is what `external` uses under the hood. Probably the PDF `template-ucl/EPL-master-thesis-covers-template-EN.pdf` is damaged, but I can't tell because I don't have it.

**Comment by hmenke** [comment]
Also this example is far from minimal and doesn't compile at all without your undisclosed external files.

**Comment by jeertmans** [comment]
@hmenke Well indeed it seems to come from the banner. I will investigate why but removing it solves the problem.
Sorry for bothering you and thanks for the tips !

**Comment by hmenke** [comment]
You can try repairing the PDF as I showed here: https://github.com/pgf-tikz/pgf/issues/288#issuecomment-776832819
If you have further questions, please head over to https://tex.stackexchange.com/.

**Comment by jeertmans** [comment]
@hmenke My PDF was not broken but this did the trick: https://tex.stackexchange.com/a/160670/240238
The problem seems to be related to \includepdf and externalization.

Thanks !
