### ISSUE TITLE
the two rhombic Catalan solids.

### ISSUE THREAD

**Issue by mfrasca** [pgf-tikz/pgf#1020]
**two missing solids**

There are only nine edge-transitive convex polyhedra, seven are already included in this library (the five Platonic solids, the cuboctahedron, and the icosidodecahedron), we miss the rhombic dodecahedron and the rhombic triacontahedron.  My guess for this omission is that the faces aren't regular polygons, but golden rhombi.  

**Brief outline of the proposed feature**

I have never written a latex library, but looking at the code, I guess it might be sufficient to have a `\tikz@lib@fold@goldenrhombus`, on which to base the two `\tikzfoldingrhombicdodecahedron` and `\tikzfoldingrhombictriacontahedron`.  

In particular the rhombic dodecahedron would be nice, because it would offer an other option for a solid calendar.

Would it be possible to slant the reference system in each rhombus, as to follow the sides of the face?

https://en.wikipedia.org/wiki/Rhombic_dodecahedron

https://en.wikipedia.org/wiki/Rhombic_triacontahedron

**Comment by mfrasca** [comment]
apparently, I missed the difference between the two rhombic dodecahedra (https://it.wikipedia.org/wiki/Dodecaedro_rombico_aureo) and I have programmed the Catalan rhombic dodecahedron, obviously using non golden rhombi (but keeping the name for the function).

I'm not so sure what would be the best now.  apparently, the two rhombi face functions should be renamed to something else, possibly "square rhombus" ? (since they are defined as »le cui diagonali possiedono lo stesso rapporto che sussiste tra il lato e la diagonale di un quadrato«).

next, either we stop here, or you decide you can use the rhombic tricontahedron (for which one would need the two golden rhombi), and being there we could reuse the golden rhombi functions and add the golden rhombic dodecahedron.

I think I would stop here, correcting the two functions and possibly redoing my calculations, which are now just approximate.

the whole history started when I saw a crushed calendar on a paper Catalan dodecahedron, and I wanted to reproduce it using your fine library, and being there, share the result with you.

**Comment by mfrasca** [comment]
fixed it on my branch.  it has the two rhombic dodecahedra and it has a partial implementation of the tricontahedron, which I don't think I'm going to complete.

**Comment by ilayn** [comment]
Can you please open a pull request on a branch that is not master? Then everyone else can have a look at it. You don't need to mention the issue name in the commits as GitHub handles that.

**Comment by mfrasca** [comment]
> Can you please open a pull request on a branch that is not master?

hi.  sure, but can you address me to which branch I should use other than master?  I only see "gh-pages" and I'm not sure that is what you meant.  or is it?

I'm still uploading refinements to master on my own fork.

**Comment by hmenke** [comment]
Forget about the branch thing, just use master. In principle it's better to use feature branches, but that's too complicated now.
