### ISSUE TITLE
Foreach operation's syntax is incorrectly documented

### ISSUE THREAD

**Issue by Symbol1** [pgf-tikz/pgf#1039]
Version: 3.1.9a

On page 167, the document reads

>     \path ... foreach⟨variables⟩[⟨options⟩] in {⟨path commands⟩} ...;

which suggest that the syntax is
`\path (0,0) foreach \x in { -- (\x, \x^2) };`
while in reality you have to specify a list
`\path (0,0) foreach \x in {1, 2, 3, 4, 5} { -- (\x, \x^2) };`

For comparison, foreach statement's syntax is documented on page 1001 as follows

>    \foreach ⟨variables⟩ [⟨options⟩] in ⟨list⟩ ⟨commands⟩

which brings up a question:
Isn't ⟨list⟩ always enclosed by curly braces?
So we should have `\marg{list}` in both [tikz-paths.tex#L1123](https://github.com/pgf-tikz/pgf/blob/master/doc/generic/pgf/text-en/pgfmanual-en-tikz-paths.tex#L1123) and [pgffor.tex#L23](https://github.com/pgf-tikz/pgf/blob/master/doc/generic/pgf/text-en/pgfmanual-en-pgffor.tex#L23).

(I am not pull-requesting this because I don't know what should I use.
`\marg{list}` or `\meta{list}`?)

**Comment by muzimuzhi** [comment]
I think `\meta{list}` is enough, in which 
https://github.com/pgf-tikz/pgf/blob/9ab9df7b7f6d865dfea99e5feaa8f317b45d2a72/doc/generic/pgf/text-en/pgfmanual-en-pgffor.tex#L35-L38
