### ISSUE TITLE
pgfmathless command is incorrectly documented

### ISSUE THREAD

**Issue by bosze** [pgf-tikz/pgf#1040]
Version: 3.1.9a

94.3.5 Comparison and logical functions (page 1040)

less(x,y)
\pgfmathless{x}{y}
This returns 1 if x < y and 0 otherwise.
0 \pgfmathparse{greater(20,25)} \pgfmathresult

In the above called command needs to be inserted the term "less"
First time reporting any documentation issues, I hope I did it correct?

**Comment by hmenke** [comment]
Fixed in https://github.com/pgf-tikz/pgf/commit/9ab9df7b7f6d865dfea99e5feaa8f317b45d2a72
