### ISSUE TITLE
Angle in polar coordinates: lose its accepted value range

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#1048]
Version: 3.1.9a

In Sec. 13.2.1 "Canvas, XYZ, and Polar Coordinate Systems", page 138, it reads
https://github.com/pgf-tikz/pgf/blob/85d2c38b78407e5b1ba42140dfd11fcdf8df1edf/doc/generic/pgf/text-en/pgfmanual-en-tikz-coordinates.tex#L195-L198

But according to how coord system [`canvas polar`](https://github.com/pgf-tikz/pgf/blob/85d2c38b78407e5b1ba42140dfd11fcdf8df1edf/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex#L5002-L5006), [`\pgfpointpolar`](https://github.com/pgf-tikz/pgf/blob/85d2c38b78407e5b1ba42140dfd11fcdf8df1edf/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex#L646-L659) and the relied `\pgfmath(cos|sin)@` are implemented, the restriction `-360 <= <angle> <= 720` seems to be unnecessary.

Moreover, whether realized the documented restriction or not, users may already used out-of-range angles in polar coordinates e.g., in `foreach` loops.

**Example** showing that out-of-range angles work
```tex
\documentclass{article}
\usepackage{tikz}

\begin{document}
\begin{tikzpicture}
  % draw three pairwise parallel line segments without error nor warning
  \draw           (0,0) -- (30:1cm) 
    [yshift=10pt] (0,0) -- (1080+30:1cm)
    [yshift=10pt] (0,0) -- (-720+30:1cm);
\end{tikzpicture}
\end{document}
```

**Comment by hmenke** [comment]
Interesting, good catch. I didn't even know that there was supposed to be a restriction. Feel free to remove it from the manual.
