### ISSUE TITLE
Could you please add the possibility to add text and picture into a node with the text wrapping around the picture

### ISSUE THREAD

**Issue by FilippoGuenzi** [pgf-tikz/pgf#1060]
**Brief outline of the proposed feature**

Adding text and a picture in a tikz node where the text wraps around the picture.

There are ways in LaTeX to have text wrapping around the picture but none seems to be able to achieve that.
If something was directly supported by pgf/tikZ that would be nice.

Usage example
Imagine a genealogical tree made in tikZ with a node for every person.
You might want to add a picture for that person to show what does (s)he looks like.
And you might also want to add a little biography.
You might want to have the biography text wrap around the person picture.

Another example. 
A game board with several steps each with an image and text wrapping around like it does sometimes in here 
![image](https://user-images.githubusercontent.com/13381116/136952810-b09a2148-8c1a-4b18-a9de-ec49a4187351.png)

**Usage example**

Th below is not the proposed syntax but what we would do naturally if we expected tikZ and wrapfig to work well together for what we want to achieve here.

```latex
\documentclass{article}
\usepackage{tcolorbox, graphicx, tikz, xfp, pgf, wrapfig}

\usetikzlibrary{decorations.pathmorphing}

\usepackage[paperwidth=1000pt, paperheight=1000pt, margin=100pt]{geometry}
\begin{document}
    \begin{tcolorbox}[boxsep=0pt, left=0pt, right=0pt, top=0pt, bottom=0pt, sharpish corners, opacityframe=0, opacityback=0, boxrule=0pt]
        \begin{tikzpicture}[x=1pt, y=1pt]
    
            \draw[xshift=100, yshift=100] node[draw, dotted, anchor=south west, text width=500, align=justify, inner sep=\padding, fill=white] {
                \begin{wrapfigure}{l}{0.25\textwidth}
                    \centering
                    \includegraphics[width=200pt]{example-image-a}
                \end{wrapfigure}

                Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
            };

        \end{tikzpicture}
    \end{tcolorbox}
\end{document}```

**Comment by hmenke** [comment]
I don't understand this request. How about just putting a minipage in the node?

```latex
\documentclass{article}
\usepackage{tikz}
\usepackage{wrapfig}

\begin{document}
\begin{tikzpicture}
  
  \node[draw,dotted] {%
    \begin{minipage}{10cm}
      \begin{wrapfigure}{l}{3cm}
        \centering
        \includegraphics[width=3cm]{example-image-a}
      \end{wrapfigure}

      \input{knuth.tex}
    \end{minipage}%
  };

\end{tikzpicture}
\end{document}
```

![Screenshot from 2021-10-12 14-20-53](https://user-images.githubusercontent.com/1903556/136955012-25b60e68-224a-46dd-b655-56153f04e50d.png)

**Comment by FilippoGuenzi** [comment]
Wonderful ! I didn't know that minipage thing. Thank you.

**Comment by hmenke** [comment]
Happy to help. In the future please consult https://tex.stackexchange.com/ first for Q&A.

**Comment by FilippoGuenzi** [comment]
I went there in the first place to ask my question.
Here is my question in TeX : https://tex.stackexchange.com/questions/618041/nodes-of-a-tikzpicture-each-with-text-wrapping-around-a-picture/
But I didn't get any satisfactory reply (or maybe as a newbie I didn't understand them)
