### ISSUE TITLE
Text nt placed at nodes when typsetting with latex

### ISSUE THREAD

**Issue by OpticBoom** [pgf-tikz/pgf#1066]
**Brief outline of the bug**

When typesetting with latex (as opposed to pdflatex, ect), text is not placed at the corresponding node. I am using miktex on Ubuntu 20.04 LTS.

**Minimal working example (MWE)**

```latex
\documentclass{article}

\usepackage{tikz}

\begin{document}

\begin{tikzpicture}
  \draw(0,0) node {Node at (0,0)} --
  (0,4) node {Node at (0,4)} --
  (4,4) node {Node at (4,4)} --
  (4,0) node {Node at (4,0)};
\end{tikzpicture}

\end{document}
```
When this is run with pdflatex using `pdflatex mwe.tex`, the expected output is achieved.
![Screenshot from 2021-10-31 17-11-35](https://user-images.githubusercontent.com/79890335/139601651-1ac9d6cf-c750-4d27-ab50-e56227e3a817.png)

When this is run with latex using `latex mwe.tex`, the bug is achieved
![Screenshot from 2021-10-31 17-23-24](https://user-images.githubusercontent.com/79890335/139601745-47901146-292f-4898-a384-8abe33bba314.png)
.

**Comment by hmenke** [comment]
When I run
```
$ latex test.tex
$ dvips test.dvi
```
I get the correct output. Looks like you are trying to view the DVI with a viewer that doesn't correctly interpret or understand the Postscript specials.
