### ISSUE TITLE
Error when using `angle` pic in another pic

### ISSUE THREAD

**Issue by knuesel** [pgf-tikz/pgf#1068]
**Brief outline of the bug**

Using the `angle` pic in the definition of a new pic triggers an error.

**Minimal working example (MWE)**

```latex
\documentclass[crop,tikz]{standalone}
\usetikzlibrary{angles}
\usetikzlibrary{quotes}
\begin{document}
\begin{tikzpicture}
    \tikzset{
        myangle/.pic={
            \draw (3,0) coordinate (A)
               -- (0,1) coordinate (B)
               -- (1,2) coordinate (C)
               pic [draw, "$\alpha$"] {angle};
        },
    }
    \pic { myangle };
\end{tikzpicture}
\end{document}
```

This produces the following error message:

```
! TeX capacity exceeded, sorry [grouping levels=255].
\XC@edef #1#2->\begingroup 
                           \ifnum \catcode `\!=13 \edef !{\string !}\fi \ifn...
l.14     \pic { myangle }
                         ;
!  ==> Fatal error occurred, no output PDF file produced!
```

Other people hit by this: see [here](https://tex.stackexchange.com/questions/620221/problem-embedding-angle-into-tikz-pic) (which suggests the workaround of using the `angle` pic in `foreground code`, but that doesn't seem to work in the case of this MWE) and [here](https://tex.stackexchange.com/questions/558426/nested-tikz-pics-double-angle-symbol).

**Comment by muzimuzhi** [comment]
@knuesel Before next release, you can use `... pic [draw, "$\alpha$", pics/code=] {angle};` as a workaround.

**Comment by knuesel** [comment]
Thanks for the fix and temporary workaround!
