### ISSUE TITLE
Graph drawing doesn't work with `name prefix`

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#1087]
**Brief outline of the bug**

When `name prefix` (or `name suffix`) is set, graph drawing throws Lua error
```tex
...graphdrawing/lua/pgf/gd/interface/InterfaceToDisplay.lua:510: attempting to create edge between nodes c and a that are not in the graph
stack traceback:
	[C]: in function 'assert'
	...graphdrawing/lua/pgf/gd/interface/InterfaceToDisplay.lua:510: in function 'pgf.gd.interface.InterfaceToDisplay.createEdge'
	[\directlua]:1: in main chunk.
\pgfgdedge ...uaescapestring {\the \toks 1}', }) }
                                                  \endpgfinterruptpath }}\en...
```

**Minimal working example (MWE)**

```latex
% !TeX program = lualatex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{graphs, graphdrawing}
\usegdlibrary{layered}

\begin{document}
% without graphdrawing
\tikz                \graph { {a,b} -> c }; % works
\tikz[name prefix=x] \graph { {a,b} -> c }; % works

% with graphdrawing
\tikz                \graph[layered layout] { {a,b} -> c }; % works
\tikz[name prefix=x] \graph[layered layout] { {a,b} -> c }; % lua error
\tikz[name prefix=x] \graph[layered layout, /tikz/name prefix=]
                       { {a,b} -> c };                      % works again
\end{document}
```

I don't speak Lua, but by adding `print()` to function `InterfaceToDisplay.createEdge()`, I find when the error is thrown,
see lines 482--484 below, `head == 'c'` and `tail == 'a'`. However the keys stored in table `scope.node_names` is `xa, xb, xc`. Hence both `h` and `t` are nil and the `assert()` fails.

https://github.com/pgf-tikz/pgf/blob/247f1f0445a9e996560c9f5a9b3fb03a4184e6ec/tex/generic/pgf/graphdrawing/lua/pgf/gd/interface/InterfaceToDisplay.lua#L475-L495

**Comment by hmenke** [comment]
Probably `\graph` doesn't wrap node names in `\tikz@pp@name{<name>}`.
