### ISSUE TITLE
Matrix library sometimes puts delimiter to the wrong place

### ISSUE THREAD

**Issue by gabor-braun** [pgf-tikz/pgf#1102]
**Brief outline of the bug**

The TikZ library matix have options "left delimiter" etc to add
delimiters to maticies.  In the following example, these are obviously at a position having nothing to do with the matrix.

**Minimal working example (MWE)**

```latex
\documentclass[tikz]{standalone}
\usetikzlibrary{matrix}

\begin{document}
\begin{tikzpicture}[ampersand replacement=\&]
  \draw[->] (0, 0) --
  node[matrix of math nodes, anchor=north,
  left delimiter=(, right delimiter=)]
  {0 \& -1 \\ 1 \& 0 \\}
  (1, 0);
\end{tikzpicture}
\end{document}
```

**Comment by muzimuzhi** [comment]
This is the sibling issue of #126, which reported wrong positioning of labels.

Each of labels, pins, and matrix delimiters use option `append after command` to insert another node at the end of the 
"main node". But when a node is placed on a line (e.g., `(0,0) -- <node> (1,0)`) or curve implicitly (see pgfmanual, sec. 17.9), such node is first collected then rescanned as if it is a label (by [setting `\tikz@node@is@a@labeltrue`][tikz@node@is@a@labeltrue]). When being treated as a label, node positioning is solely controlled by `pos` option, which is initialized to `pos=.5` at picture beginning, and never by normal `at` setting.

[tikz@node@is@a@labeltrue]: https://github.com/pgf-tikz/pgf/blob/acfa21c9fb09909ce5fa8f9760f0a706e32753e5/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex#L2787

```tex
\draw (0,0) -- node[at={(1,1)}] {x}  (1,0); % this `at={(1,1)}` is ignored
```

To reenable `at` setting used by matrix delimiters, locally setting `\tikz@node@is@a@labelfalse` does the trick, just like how 438758daf4a910043438b6232ee8a7fd71978109 fixed #126. I've prepared a PR.

PS: Setting `pos=` also works, which maybe helpful in (tricky) user input.
