### ISSUE TITLE
About "6 Tutorial: A Lecture Map for Johannes"

### ISSUE THREAD

**Issue by brucejuz** [pgf-tikz/pgf#1107]
- I have read the "6 Tutorial: A Lecture Map for Johannes" and followed the instruction in the manual, but just can't get the output exactly as in the manual. 

- Until finally, I found that it's about the page margin.
- If you want to get the output image exactly as in the manual, you can't just use 
`\documentclass{article}`

- You should change the page margin such as this:
` \usepackage[a4paper, inner=1.5cm, outer=1.5cm, top=2cm, bottom=3cm]{geometry}`

- Then you can get the image same as in the manual.
- Since some of the readers who want to follow the instruction of the tutorial are newbie like me, it would better to point out this in the tutorial. 
- Thanks! The tutorials in the manual are really helpful!

**Comment by hmenke** [comment]
This doesn't look like an issue. If you want to post comments please do so on the official mailing list at https://tug.org/mailman/listinfo/pgf-tikz or in the chat on the Matrix network at https://matrix.to/#/#pgf-tikz:matrix.org.
