### ISSUE TITLE
Form-only patterns have no specified color

### ISSUE THREAD

**Issue by QJLc** [pgf-tikz/pgf#1122]
```latex
\documentclass{article}

\usepackage{tikz}

\begin{document}

\pgfdeclarepatternformonly[\testcolor]{Rings}
{\pgfpoint{-0.5*20pt}{-0.5*20pt}}
{\pgfpoint{0.5*20pt}{0.5*20pt}}
{\pgfpoint{20pt}{20pt}}
{
%  \pgfsetstrokecolor{\testcolor}%
  \pgfpathcircle\pgfpointorigin{8pt}
  \pgfusepath{stroke}
}

\begin{tikzpicture}[testcolor/.store in=\testcolor, Rings/.style={pattern=Rings}]
  \begin{scope}[testcolor=red]
    \filldraw [Rings] (0,0) rectangle +(1.5,2);
    \filldraw [Rings, pattern color=green] (2,0) rectangle +(1.5,2);
  \end{scope}
  \begin{scope}[testcolor=green]
    \filldraw [Rings] (0,2.5) rectangle +(1.5,2);
    \filldraw [Rings, pattern color=red] (2,2.5) rectangle +(1.5,2);
  \end{scope}
\end{tikzpicture}

\end{document}
```
I find that, in file `pgfcorepatterns.code.tex`, the line 184 has a number `7`, it should be `#7`.
https://github.com/pgf-tikz/pgf/blob/f3ee9140d004204a2b57ebfb499c03fdd015717c/tex/generic/pgf/basiclayer/pgfcorepatterns.code.tex#L176-L186

**Comment by muzimuzhi** [comment]
Great catch! Would you like to prepare a pull request so you can be one of the contributors of pgf? Alternatively I can do the fixing commit and [co-author] with you, if you're willing to provide your email address, either the real one or the [`no-reply`][no-reply] one.

[co-author]: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors
[no-reply]: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address

**Comment by hmenke** [comment]
Fixed in https://github.com/pgf-tikz/pgf/commit/f8119529eaf7608a65f654a83e24ecf792f9e152

**Comment by QJLc** [comment]
Sorry, my link to GitHub is not stable.
