### ISSUE TITLE
Macros with optional arguments do not work in TikZ commands [Semi-patch]

### ISSUE THREAD

**Issue by ilyaza** [pgf-tikz/pgf#1147]
**Brief outline of the bug**

The `TikZ` command loop fails handling `LaTeX` macros with optional arguments.  It gives a cryptic error message (like `Did you forget to insert a semicolon`).  (A “semi-patch” included — it works for the older version of the scan loop.)

**Minimal working example (MWE)**

(The following example includes also a `\global\def` chunk to illustrate another functionality of the patch.)

```latex
\documentclass{article}
\usepackage{tikz}

\begin{document}

\newcommand\foo[1][node {123}]{#1}

\tikz \draw (0,0) node {123} -- ++(1,1);.

\tikz \draw (0,0) \foo \foo[-- ++(1,1)] \global\def\BAR{node {yyy}};.

\tikz \draw (0,0) node {123} -- ++(1,1);.

\tikz \draw \BAR;

\end{document}
```
**How to fix**

Right now I cannot test with the latest version.  I include the patch for the version in `TeXLive2021`.  I expect the first and the third chunks would work in the bleeding-edge version too (they are only 4 LoCs), and the dispatcher would need an extra chunk like
```latex
    {\global}{\let\pgfutil@next\tikz@global}%
    {\let}{\let\pgfutil@next\tikz@assignment}%
    {\futurelet}{\let\pgfutil@next\tikz@assignment}%
    {\def}{\let\pgfutil@next\tikz@assignment}%
    {\gdef}{\let\pgfutil@next\tikz@assignment}%
    {\edef}{\let\pgfutil@next\tikz@assignment}%
    {\xdef}{\let\pgfutil@next\tikz@assignment}%
```
[diff-tikz.code.tex.txt](https://github.com/pgf-tikz/pgf/files/8287662/diff-tikz.code.tex.txt)

**Comment by hmenke** [comment]
You cannot use unexpandable material on a path and that is also documented. I'm not going to change that.

**Comment by ilyaza** [comment]
I do not follow: **with the given patch**, you can use *this particular kind* of unexpandable “material”.  So your statement would be valid only in the past tense.

**Comment by hmenke** [comment]
If you want to perform semantic actions (like assignments) on a path use `\pgfextra`. Macros with unexpandable material are intentionally unsupported, because you will quickly run into problems with incomplete `\if` or dangling `\else`.

See also https://github.com/pgf-tikz/pgf/pull/967

**Comment by muzimuzhi** [comment]
A workaround
 - `\newcommand\foo[1][...]{...}` is replaced with option `insert path` and key handler `/.default`,
 - `\global\def\BAR{..}` is wrapped in `\pgfextra`

```tex
\documentclass{article}
\usepackage{tikz}

\tikzset{
  foo/.style={insert path={#1}},
  foo/.default={node {123}}
}

\begin{document}
\tikz \draw (0,0) node {123} -- ++(1,1);.

\tikz \draw (0,0) [foo] [foo={-- ++(1,1)}]
  \pgfextra{\global\def\BAR{node {yyy}}};.

\tikz \draw (0,0) node {123} -- ++(1,1);.

\tikz \draw \BAR;
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/158910482-e3f555f5-74cf-4082-9f5a-655db35e34bc.png)
