### ISSUE TITLE
[Question] where is `fadings` library source code located?

### ISSUE THREAD

**Issue by antshar** [pgf-tikz/pgf#1157]
I'm trying to compile this example from the documentation
![image](https://user-images.githubusercontent.com/54121465/168442037-8e1288eb-e97e-4edb-8768-315eb6773caf.png)
but I'm getting 
```
Package pgf Error: Undefined fading 'fade out'.
```
Apparently I have an outdated `tikz` library, it's `3.1.5b` now.

I'm curious where is the source code for `fadings` library so that I can manually update it? I tried to make a search of this repo by `fade out` keyword but didn't really find the definition of this option for `path fading`

**Comment by hmenke** [comment]
1. Never update only parts of PGF. Always update the entire package.
2. Nothing has changed in the `fadings` library recently.
3. Cannot reproduce. For me the MWE works perfectly.
     ```latex
     \documentclass{article}
     \usepackage{tikz}
     \usetikzlibrary{fadings,patterns}
     \begin{document}
     \tikzfading[name=fade out,
                 inner color=transparent!0,
                 outer color=transparent!100]
     
     % Now we use the fading in another picture:
     \begin{tikzpicture}
       % Background
       \fill [black!20] (-1.2,-1.2) rectangle (1.2,1.2);
       \path [pattern=checkerboard,pattern color=black!30]
                        (-1.2,-1.2) rectangle (1.2,1.2);
     
       \fill [blue,path fading=fade out] (-1,-1) rectangle (1,1);
     \end{tikzpicture}
     \end{document}
     ```

**Comment by antshar** [comment]
Oh, wait, I missed `\tikzfading` part... Sorry for being inattentive. I thought it's a predefined option.
