### ISSUE TITLE
Color transitions of mindmap nodes are not always applied automatically

### ISSUE THREAD

**Issue by claell** [pgf-tikz/pgf#1165]
### Brief outline of the bug

As you can see in https://latexdraw.com/mind-map-latex-tutorial/ for example, some nodes have color transitions between them and some don't. Apparently, it is a different, if a concept color is set for a level or for a node. This seems like a bug to me, but maybe it is also wanted like this.

### Minimal working example (MWE)

```
\documentclass[tikz,border=10]{standalone}

\usepackage{calc}

\usetikzlibrary{backgrounds,mindmap}

\begin{document}
\begin{tikzpicture}[
    mindmap,
    concept color = red!30, 
    every node/.style = {concept}, 
    grow cyclic,
    level 1/.append style = {
        level distance = 4.5cm,
        sibling angle = 120
    },
    level 2/.append style = {
        level distance = 3cm,
        sibling angle = 45}
]
 
\node {Our root concept}
    child {node [concept color = blue!30] {First idea}
        child {node {Fact 1}}
        child {node {Fact 2}}
    }
    child [concept color = green!30] {node {Second idea}
        child {node {Sub-idea}}
    }
    child {node [concept color = magenta!30] {Third idea}
            child [concept color = magenta!50!black] {node {Note 1}}
            child [concept color = magenta!60!black] {node {Note 2}}
            child [concept color = magenta!70!black] {node {Note 3}}
    };
 
\end{tikzpicture}
\end{document}
```

**Comment by muzimuzhi** [comment]
According to the doc, smooth color transition is only made when `concept color` is given to `child`, not `node`.

https://github.com/pgf-tikz/pgf/blob/acfa21c9fb09909ce5fa8f9760f0a706e32753e5/doc/generic/pgf/pgfmanual-en-library-mindmaps.tex#L217-L224

If I change your example accordingly, the output seems fine.
```tex
\documentclass[tikz,border=10]{standalone}
\usepackage{calc}
\usetikzlibrary{backgrounds,mindmap}

\begin{document}
\begin{tikzpicture}[
    mindmap,
    concept color = red!30,
    every node/.style = {concept}, 
    grow cyclic,
    level 1/.append style = {
        level distance = 4.5cm,
        sibling angle = 120
    },
    level 2/.append style = {
        level distance = 3cm,
        sibling angle = 45}
]

\node {Our root concept}
    child[concept color = blue!30] {node {First idea}
        child {node {Fact 1}}
        child {node {Fact 2}}
    }
    child[concept color = green!30] {node {Second idea}
        child {node {Sub-idea}}
    }
    child[concept color = magenta!30] {node {Third idea}
            child [concept color = magenta!50!black] {node {Note 1}}
            child [concept color = magenta!60!black] {node {Note 2}}
            child [concept color = magenta!70!black] {node {Note 3}}
    };
\end{tikzpicture}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/172916656-ada79d7b-e413-42ee-b29d-867a1f204511.png)

**Comment by claell** [comment]
Ah, then this is wanted. So is there an easy way to do this for levels? Or doesn't that make sense to be used in such cases?

**Comment by muzimuzhi** [comment]
> So is there an easy way to do this for levels?

Does the last example in sec. 60.3.2 "Concepts in Trees" (unofficial [online version](https://tikz.dev/library-mindmaps#sec-60.3.2)) help?

**Comment by claell** [comment]
Yes, thank you very much! I should have read the documentation more carefully!

**Comment by claell** [comment]
One thing that I noticed there: Apparently, the mindmap option needs to be given after setting the root concept style. Else, the root concept will be black (as in the example), although it was set to blue in the example. Possibly, the example should be adjusted, as it currently does not work as intended? Should I create another issue for that?

**Comment by muzimuzhi** [comment]
> Should I create another issue for that?

I opened #1166, with what you caught (nice caught) and something more.

**Comment by claell** [comment]
Thanks!
