### ISSUE TITLE
`doc` v3 causes errors when building manual

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#1171]
### Brief outline of the bug

`doc` v3, which is shipped with latex2e 2022-06 (also see ltnews35),  causes errors when building manual.

Restoring to v2 fixes the problem, see https://github.com/muzimuzhi/pgf/commit/932ee035eb4b09377afd1ec0bdbe01c8d44a4c35.

### Minimal working example (MWE)

In workflow run https://github.com/pgf-tikz/pgf/actions/runs/2601893848, the first error is

```
! Package PGF Math Error: Sorry, an internal routine of the floating point unit
 got an ill-formatted floating point number `'. The unreadable part was near ''
..
```

A simplified (but not minimal) example:
```tex
\documentclass{article}
% \usepackage{doc}[=v2] % works
\usepackage{doc} % fails

\usepackage{calc, tikz}
\usetikzlibrary{datavisualization}

\makeatletter
\input pgfmanual-en-macros.tex
\makeatother

\begin{document}

% excerpted from `pgfmanual-en-dv-main.tex`
\begin{codeexample}[setup code]
\tikz \datavisualization data group {points} = {
  data {
    x, y
    0, 1
    1, 2
    2, 2
    5, 1
    2, 0
    1, 1
  }
};
\end{codeexample}

%\begin{codeexample}[preamble={}]
\tikz \datavisualization [school book axes,      visualize as line] data group {points};
\qquad
\tikz \datavisualization [scientific axes=clean, visualize as line] data group {points};
%\end{codeexample}

\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/177020070-6eaa8630-4b15-4162-97c0-6a7920dd2a99.png)

The code acts like the data group `points` is defined, but empty.

**Comment by muzimuzhi** [comment]
With `doc` v3, somehow the `data {x, y<NEWLINE>0, 1<NEWLINE>...}` is tokenized before `\datavisualization` parses it, hence `<NEWLINE>` is converted to space.

**Comment by muzimuzhi** [comment]
`hypdoc` is the culprit, see ho-tex/hypdoc#3.

Update: As long as `pgfmanual` doesn't take massive rewrites, using `\documentclass[a4paper,doc2]{ltxdoc}` as in https://github.com/muzimuzhi/pgf/commit/932ee035eb4b09377afd1ec0bdbe01c8d44a4c35 seems enough. I'll provide a PR.

**Comment by muzimuzhi** [comment]
Let me add some explanations:

**In short**, `codeexample` env requires that the active `^^M` is `\edef`-unexpandable.

**In more details**,
 - By setting catcodes for special characters (including setting `^^M` active) and using `\end{codeexample}` as a delimiter, `codeexample` env collects its content in verbatim and passes it to `\endofcodeexample`.
 - In `\endofcodeexample`, the verbatim env content (its `#1`) is normalized by an `\edef` to convert active `~`, ` `, and `^^I` to spaces and remove comments. See lines 1714 and 1730 below. This step requires that the active `^^M` is unexpandable.
 - In LaTeX kernel, the active `^^M` is let to `\par`, which is either an unexpandable primitive or an unexpandable macro since the introduction of paragraphs hooks.
 - If active `^^M` is not `\edef`-unexpandable, for example when `hypdoc` is loaded which does `\def^^M{}`, then the (multi-line) `codeexample` content will be joint into a single line. Since `datavisualization` needs to read inline data line-by-line, errors were thrown.

https://github.com/pgf-tikz/pgf/blob/2b1da75747475e869ef9dd48de271b80bc851be3/tex/latex/pgf/doc/pgfmanual-en-macros.tex#L1707-L1731

In response to @u-fischer's comment in https://github.com/ho-tex/hypdoc/issues/3#issuecomment-1173044927

> But this here errors too, so perhaps the datavisualization code needs to guard itself against `^^M` changes better too:
> [an example showing `\obeylines` followed by datavisualization with inline data is broken]

It's worth to add `\let^^M\par` to `\endofcodeexample`, to ensure active `^^M` is `\edef`-unexpandable. But making `datavisualization` compatible with `\obeylines` need too much work, compared to the fact `datavisualization` is far from popular. Also I doubt whether `tikz` or even `pgf` is ever `\obeylines` compatible.

**Comment by muzimuzhi** [comment]
> Also I doubt whether `tikz` or even `pgf` is ever `\obeylines` compatible.

A stricter grammar covering where a space (either explicit or converted from normal line end) or an active line end (which will expand to `\par`) is allowed on a tikz path, is required. And that would be too complex for both developers and users.

For example, in `\draw <pos1> (0,0) <pos2> circle <pos3> (3pt);`, currently `<pos1>` and `<pos2>` accepts either space or active line end (thanks to `\tikz@handle` which will expand unrecognized next token and retry), while `<pos3>` can't be active line end.

**Comment by davidcarlisle** [comment]
hypdoc is updated at ctan to fix the original issue

**Comment by muzimuzhi** [comment]
> In workflow run https://github.com/pgf-tikz/pgf/actions/runs/2601893848, the first error is
> 
> ```
> ! Package PGF Math Error: Sorry, an internal routine of the floating point unit
>  got an ill-formatted floating point number `'. The unreadable part was near ''
> ..
> ```

With `hypdoc` v1.17, [re-runed job](https://github.com/pgf-tikz/pgf/actions/runs/2601893848) for manual building now succeeds, but the resulted `pgfmanual.pdf` has some changes in its style.

Sectioning titles in toc, some code in `codeexample`, page numbers in index entries are all in a bright blue, the default linkcolor.
![image](https://user-images.githubusercontent.com/6376638/177510562-503cb5cf-5939-4036-9839-f587e4a15c0a.png)
![image](https://user-images.githubusercontent.com/6376638/177510611-d6fb769d-0228-4f91-9c5f-30eb241ec343.png)
![image](https://user-images.githubusercontent.com/6376638/177510689-1e44929c-3ca7-4f37-b335-0f4b5e217d21.png)


The change may be related to the loading position and configuration of `hyperref`, as now it seems `hyperref` should be loaded by `hypdoc`, which is loaded by `doc` at hook `begindocument/before`. Any loading of `hyperref` prior to that hook will cause a warning
```tex
Package hypdoc Warning: hyperref has been loaded before. Check the options! on 
input line 56.
```

Although the problem reported in this issue has been resolved, the backwards compatibility task is not. Thus PR #1172 still seems to have merit.

_Edit:_ Or I will test adapting pgfmanual for `doc` v3 tomorrow.

**Comment by hmenke** [comment]
We should just use `doc2` for the time being. Otherwise we run into problems if people try to compile the manual on only slightly outdated versions of TeX Live.
