### ISSUE TITLE
Feature request: Provide a `shorten` key that works on both ends.

### ISSUE THREAD

**Issue by gerion0** [pgf-tikz/pgf#1184]
Currently, this works in TikZ:
```tex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{arrows.meta}
\begin{document}
  \begin{tikzpicture}
    \draw[red] (0,0) -- (1,1);
    \draw[blue, shorten <= 2pt, shorten >= 2pt] (0,0) -- (1,1);
  \end{tikzpicture}
\end{document}
```

Sometimes you want (like in this example) that the path is shortened by the same amount on both ends. I needed that already for myself, but also saw it in random examples. Is it technically possible and what do think of something like this that produces the exact same result as the other code?:
```tex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{arrows.meta}
\begin{document}
  \begin{tikzpicture}
    \draw[red] (0,0) -- (1,1);
    \draw[blue, shorten = 2pt] (0,0) -- (1,1);
  \end{tikzpicture}
\end{document}
```
So basically provide also a `shorten` key that works on both ends at once.

**Comment by hmenke** [comment]
You can easily implement this yourself in one line of code.

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{arrows.meta}
\tikzset{shorten/.style={shorten <={#1},shorten >={#1}}}
\begin{document}
  \begin{tikzpicture}
    \draw[red] (0,0) -- (1,1);
    \draw[blue,shorten=2pt] (0,0) -- (1,1);
  \end{tikzpicture}
\end{document}
```

[Live example](https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%7Btikz%7D%0A%5Cusetikzlibrary%7Barrows.meta%7D%0A%5Ctikzset%7Bshorten/.style=%7Bshorten%20%3C=%7B#1%7D,shorten%20%3E=%7B#1%7D%7D%7D%0A%5Cbegin%7Bdocument%7D%0A%20%20%5Cbegin%7Btikzpicture%7D%0A%20%20%20%20%5Cdraw%5Bred%5D%20(0,0)%20--%20(1,1);%0A%20%20%20%20%5Cdraw%5Bblue,shorten=2pt%5D%20(0,0)%20--%20(1,1);%0A%20%20%5Cend%7Btikzpicture%7D%0A%5Cend%7Bdocument%7D)

**Comment by gerion0** [comment]
Thank you for the hint. Maybe this is worth taking it in the default code base?
