### ISSUE TITLE
Missing HTML page

### ISSUE THREAD

**Issue by thistlillo** [pgf-tikz/pgf#1190]
### Version

Missing (empty) https://tikz.dev/tikz-paths

### Details

The page at https://tikz.dev/tikz-paths is missing (it is empty, no errors returned).

**Comment by hmenke** [comment]
This is not the correct repo. Go to https://github.com/DominikPeters/tikz.dev-issues/issues

**Comment by thistlillo** [comment]
Right. It is the repository I reach clicking on the github link at: https://tikz.dev/tikz-actions
