### ISSUE TITLE
LMTX incompatbility: don't use fixed strings for \meaning

### ISSUE THREAD

**Issue by leahneukirchen** [pgf-tikz/pgf#1193]
### Brief outline of the bug

Some TikZ libraries (e.g. `quotes`) use keys which include the string given by `\meaning`, e.g.
```
\pgfkeyssetvalue{/handlers/first char syntax/the character "}{\tikz@quote@parser}%
```

However, in LMTX, `\meaning"` expands to
```
the character U+0022 'quotation mark'
```
and [they don't intent to change that](https://www.mail-archive.com/ntg-context@ntg.nl/msg103052.html).

In my experiments, it seems sufficient to instead write
```
\pgfkeyssetvalue{/handlers/first char syntax/\meaning"}{\tikz@quote@parser}%
```
which uses whatever string the current TeX implementation uses.

This is related to #990.

### Minimal working example (MWE)

(this is ConTeXt)

```
\usemodule[tikz]
\usetikzlibrary[quotes,angles]

\starttext

\meaning"

\starttikzpicture
  \node ["abc" draw] {node};
\stoptikzpicture

\stoptext
```

**Comment by hmenke** [comment]
I think we need `\expandafter\meaning\string"` here, just in case `"` is active at that point.

**Comment by leahneukirchen** [comment]
Also in https://github.com/pgf-tikz/pgf/blob/0280303d03594e1ea13f95f116234a803591b4af/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibraryanimations.code.tex#L597

Thanks for the quick fixing!
