### ISSUE TITLE
`veclen()` description contains invalid MathJax code

### ISSUE THREAD

**Issue by VincentTam** [pgf-tikz/pgf#1200]
### Version

3.1.9a

### Details

![image](https://user-images.githubusercontent.com/5748535/195427271-3ae8744d-c264-4ae8-aa87-e52f869eeb1e.png)
https://tikz.dev/math-parsing#\pgfmathveclen

# Description

I opened the above link for the description of `veclen()`, which contains `\mvar`, which isn't a valid command supported by MathJax.

# Technical details

MS Win 10
Google Chrome Version 106.0.5249.103

**Comment by hmenke** [comment]
https://github.com/DominikPeters/tikz.dev-issues/issues
