### ISSUE TITLE
Minor error in the documentation for tikz-external

### ISSUE THREAD

**Issue by jonschz** [pgf-tikz/pgf#1201]
There is a minor error in the following lines:

https://github.com/pgf-tikz/pgf/blob/0280303d03594e1ea13f95f116234a803591b4af/doc/generic/pgf/pgfmanual-en-library-external.tex#L1092-L1093

Using the command as is may cause the final `}` to become part of the command output: On my Windows machine, the command
```
\tikzset{
	external/system call/.add=
		{}
		{&& dvisvgm -P --no-fonts "\image.pdf" -o "\image.svg"},
}
```
produces a file named `image.svg}`. This can be fixed by either removing the whitespace and line break between `{}` and `{&&`, or by adding a space between `.svg"` and `}`. I would therefore suggest to change the code in the example to
```
 {; convert -density 300 -transparent white "\image.pdf" "\image.png" }, 
```

**Comment by hmenke** [comment]
Impossible. If the brace was swallowed, TeX would crash with `missing }`. Make a MWE.

**Comment by jonschz** [comment]
I double checked, and the behaviour is exactly as I described above. Here is the MWE (full code below): [tikzexternal_bug.zip](https://github.com/pgf-tikz/pgf/files/9768745/tikzexternal_bug.zip)

I am using Windows 10, pdfTeX, Version 3.141592653-2.6-1.40.24 (MiKTeX 22.8)

**Expected behaviour**

A file called `tikzexternal_bug-figure0.svg` should be created in `.\tikz`

**Actual behaviour**

A file called `tikzexternal_bug-figure0.svg}` is created in `.\tikz`.

Full code:
```latex
\documentclass{article}

\usepackage{tikz}
\usetikzlibrary{external}

\tikzset{
	external/system call/.add=
	{}
	{&& dvisvgm -P --font-format=woff "\image.pdf" -o "\image.svg"}, % use this line to trigger the bug
%	{&& dvisvgm -P --font-format=woff "\image.pdf" -o "\image.svg" }, % this line works fine
}

%% This also works fine:
%\tikzset{
%	external/system call/.add=
%	{}{&& dvisvgm -P --font-format=woff "\image.pdf" -o "\image.svg"},
%}

\tikzexternalize[
prefix=tikz/,
shell escape=-enable-write18
]

\begin{document}
	\begin{tikzpicture}
		\draw (0,0) rectangle (1,1);
	\end{tikzpicture}
\end{document}
```

**Comment by muzimuzhi** [comment]
A `pgfkeys` issue.

For any key or key handler defined with `/.code 2 args`, its expected value should be in form `<token or group 1><token or group 2>`, without any spaces in between. If, for example a space is there, then no error is raised but the 2nd argument (`#2`) will be `<space><token or group 2>`. See `ERROR: ...` in example below.

This is because for the underneath macro that holds the code a key (or key handler) will execute, its parameter text is always ended with `\pgfeov` (end of value), thus for `/.code 2 args` its `#2` is delimited by `\pgfeov`. See `INFO: ...` in example below.

```tex
\documentclass{article}
\usepackage{pgfkeys}

\begin{document}
\pgfkeys{/handlers/.add/.show code} % INFO: #2 is delimited by \pgfeov
% > \pgfkeysshower=\long macro:
% #1#2\pgfeov ->\pgfkeysaddvalue {\pgfkeyscurrentpath }{#1}{#2}.

\pgfkeys{key/.initial=init, key/.show value}
% > \pgfkeysshower=macro:
% ->init.

\pgfkeys{key/.add={pre<>}{<>post}, key/.show value}
% > \pgfkeysshower=macro:
% ->pre<>init<>post.

\pgfkeys{key/.add={pre2<>} {<>post2}, key/.show value}
% > \pgfkeysshower=macro:
% ->pre2<>pre<>init<>post {<>post2}. % <<< ERROR, extra pair of braces
\end{document}
```

> This can be fixed by either removing the whitespace and line break between `{}` and `{&&`, or by adding a space between `.svg"` and `}`.

I support the first way, or even use `/.append={<code>}` to replace `/.add={}{<code>}`.

```diff
diff --git a/doc/generic/pgf/pgfmanual-en-library-external.tex b/doc/generic/pgf/pgfmanual-en-library-external.tex
index f96dd42d..e7ddea78 100644
--- a/doc/generic/pgf/pgfmanual-en-library-external.tex
+++ b/doc/generic/pgf/pgfmanual-en-library-external.tex
@@ -1088,8 +1088,7 @@ with |pdflatex|, I can define the following style:
     % This style is not pre-defined, you may need to copy-paste and
     % adjust it.
     png export/.style={
-        external/system call/.add=
-            {}
+        external/system call/.append=
             {; convert -density 300 -transparent white "\image.pdf" "\image.png"},
         %
         /pgf/images/external info,
```

**Comment by hmenke** [comment]
@muzimuzhi Flawless analysis, as always! :+1:

**Comment by jonschz** [comment]
Great! I find `/.append={<code>}` to be the most natural choice. Should I create a PR, or will you simply change it?
