### ISSUE TITLE
replace 'illegal' with 'invalid'

### ISSUE THREAD

**Issue by lemzwerg** [pgf-tikz/pgf#1204]
### Version

3.1.9a

### Details

Please replace 'illegal' with 'invalid' in the documentation (together with warning and error messages of TikZ itself).  You won't come into jail if you use invalid TikZ syntax...

Apparently, it's a thing in the English language to sloppily mix up 'invalid' with 'illegal'.  In other languages, for example German, it would be unthinkable to ever replace 'ungültig' (invalid) with 'ungesetzlich' (illegal).

**Comment by hmenke** [comment]
“Illegal” is a perfectly fine term in the context of computing, see e.g. https://en.wikipedia.org/wiki/Illegal_opcode

**Comment by lemzwerg** [comment]
> “Illegal” is a perfectly fine term in the context of computing, see e.g. https://en.wikipedia.org/wiki/Illegal_opcode

IMHO, it's not 'perfectly fine', it's simply wrong usage of English – a bad example doesn't justify that everybody follows blindly.  If at all, you might use 'illegal opcode' as a special term.

FYI, the [GNU Coding Standards](https://www.gnu.org/prep/standards/standards.html) documentation says in section 6.1: "Please do not use the term “illegal” to refer to erroneous input to a computer program. Please use “invalid” for this, and reserve the term “illegal” for activities prohibited by law."

**Comment by hmenke** [comment]
But this is neither your nor a GNU project so none of this matters.

**Comment by muzimuzhi** [comment]
Just some random search results:

The [Online Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/illegal) shows illegal does has a meaning in IT (from [Cambridge Business English Dictionary](https://dictionary.cambridge.org/dictionary/english/) ©):

> used to describe a character (= letter, number, or symbol) that you cannot use in a particular place on a computer, because it may create problems:
> - The colon is the only illegal character for file and folder names.

The JavaScript language has a built-in exception `SyntaxError: illegal character`, see [related MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Illegal_character).
