### ISSUE TITLE
figure overflow in pdf manual

### ISSUE THREAD

**Issue by erusyd** [pgf-tikz/pgf#1208]
### Version

latest, 3.1.9a

### Details

![image](https://user-images.githubusercontent.com/1529102/196615140-1aadb8d3-2ab8-44d1-b2c8-5479d5ed6cf1.png)

**Comment by hmenke** [comment]
This is the problem.

https://github.com/pgf-tikz/pgf/blob/55d0e441f0ee2a1ca9ee751ab7d81b67995e170a/doc/generic/pgf/pgfmanual-en-library-circuits.tex#L93

**Comment by muzimuzhi** [comment]
This is something I reported when I was new (and even naive) to pgf repo, see https://github.com/pgf-tikz/pgf/pull/840#issuecomment-600973964.

I may have a local branch which tries to address all the large-enough overfull `\hbox` issues in `pgfmanual.log`, with the help of some log analyzer like [`texloganalyser`](https://ctan.org/pkg/texloganalyser)[^1]. But currently I lost access to that laptop built-in SSD. It has full backup so there will be no data loss. Just I'd like to see if that SSD will wake up again, in 1 or 2 days.

[^1]: The newer [`texlogfilter`](https://ctan.org/pkg/texlogfilter) may be better. I haven't compared them yet.

**Comment by muzimuzhi** [comment]
> Just I'd like to see if that SSD will wake up again, in 1 or 2 days.

Lucky, the built-in SSD wakes up again.

Log analyzer `texlogfilter` is not as configurable as `texloganalyser`. I'll provide a PR to resolve large-enough overflows in pgfmanual maybe tomorrow.

**Comment by ilayn** [comment]
A new tool written in Perl... smh

Not that I care but this can be done with terminal tools `awk` or `grep` or whatever tied to the Github Actions as a separate step. In fact, TeX is all about reading files line-by-line and doing stuff (regex included) so I'd bet L3 folks already have a native tool for this.
