### ISSUE TITLE
Graph edge label is drawn on the following edge as well

### ISSUE THREAD

**Issue by mbugert** [pgf-tikz/pgf#1222]
## Brief bug description
There's a scenario in which an edge label in a graph is drawn twice: once on the edge it was meant for, and then a second time on the edge specified right after, if that following edge happens to have the same target node as the first one. This shouldn't happen.

## MWE
```latex
\documentclass{standalone}
\usepackage{tikz}
\usetikzlibrary{graphs, quotes}

\begin{document}
\tikz \graph {
	a -> b [> "label"];
	c -> b;
};
\end{document}
```

![bug](https://user-images.githubusercontent.com/23331603/205744731-f8a5be4f-0ca6-43a4-a180-b93dbd0a40ed.png)

## Workaround
```latex
\documentclass{standalone}
\usepackage{tikz}
\usetikzlibrary{graphs, quotes}

\begin{document}
\tikz \graph {
	a -> b [> "label"];
	b <- c;
};
\end{document}
```

![workaround](https://user-images.githubusercontent.com/23331603/205744899-7a5fd391-b4e5-4d4b-a5bb-7968a48fd005.png)

## Environment
TeX version: `texlive 2021.20220204-1`
Tikz version: `3.1.9a`
OS: Linux Mint 21

**Comment by muzimuzhi** [comment]
This is the expected behavior, see pgfmanual, sec. 19.6.3 _Options For Incoming and Outgoing Edges_
![image](https://user-images.githubusercontent.com/6376638/205816238-2a6af14c-b20c-4f88-8d44-01d7b24de2b7.png)

You can use `target edge clear` or the equivalent `clear >` to reset it.

------
A simplified example
```tex
\documentclass{standalone}
\usepackage{tikz}
\usetikzlibrary{graphs}

\begin{document}
\tikz \graph {
  a -> b [target edge style=blue];
  c -> b;
};

\tikz \graph {
  a -> b [target edge style=blue];
  c -> b [target edge clear];
};
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/205816741-2c2c1d45-fceb-4f5a-b9cd-e11b185122cb.png)

**Comment by muzimuzhi** [comment]
(some more words)

Firstly, `> ...` is just a syntactic sugar of `target edge style=...`. To support chain groups both `target edge style` and `source edge style` have to act globally. The point is that when a node chain ends, these global styles are not reset.

I see use cases for both behaviors (reset per node chain or not). After reading the related source codes, it turns out that the `;` is simply replaced by `,` (see [`\tikz@lib@graph@semi`](https://github.com/pgf-tikz/pgf/blob/b79a019bdea7e37f0ff69f45c72b20336cec6d38/tex/generic/pgf/frontendlayer/tikz/libraries/graphs/tikzlibrarygraphs.code.tex#L474-L491)). Thus to add support to one-time `target/source edge style`, one need to insert some hook when replacing and maybe even patch the main parser `\tikz@lib@graph@main@parser` to handler and execute that hook.

**Comment by muzimuzhi** [comment]
The following example added three graph keys `one time source edge style`, `one time target edge style`, and `one time edge style`. The first two works like `source/target edge style`Note they're more like a toy than well-tested feature(s).

Usages:
- `a -> b [one time target edge style=blue]`, the edge style is reset when a new node chain starts
- `a -> b [> "label", one time edge style]`, the label is cleared when a new node chain starts

```tex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{graphs, quotes}

\makeatletter
% utilities
\long\def\pgfutil@expandonce#1{\pgfutil@unexpanded\expandafter{#1}}
\long\def\pgfutil@xappto#1#2{\xdef#1{\pgfutil@expandonce{#1}#2}}
\let\pgfutil@unexpanded=\unexpanded

\def\tikz@lib@graph@everychain@clearsourceedge{%
  \pgfutil@xappto\tikz@lib@graph@everychain@hook{%
    \pgfutil@expandonce{%
      % code of key /tikz/graphs/source edge clear
      \expandafter\global\expandafter\let\csname tikz@lgca@@\tikz@lib@graph@name\endcsname\relax
}}}
\def\tikz@lib@graph@everychain@cleartargetedge{%
  \pgfutil@xappto\tikz@lib@graph@everychain@hook{%
    \pgfutil@expandonce{%
      % code of key /tikz/graphs/target edge clear
      \expandafter\global\expandafter\let\csname tikz@lgcb@@\tikz@lib@graph@name\endcsname\relax
}}}

% new keys
\tikzgraphsset{
  % not really one-time, since the edge style still works in current node chain
  one time source edge style/.code={%
    \tikz@lib@graph@everychain@clearsourceedge
    \pgfkeysalso{source edge style={#1}}%
  },
  one time target edge style/.code={%
    \tikz@lib@graph@everychain@cleartargetedge
    \pgfkeysalso{target edge style={#1}}%
  },
  one time edge style/.code={% shorter name?
    \tikz@lib@graph@everychain@clearsourceedge
    \tikz@lib@graph@everychain@cleartargetedge
  }
}

% init internal
\def\tikz@lib@graph@everychain@reset{%
  \global\let\tikz@lib@graph@everychain@hook=\pgfutil@empty}
\tikz@lib@graph@everychain@reset

% patch
\def\tikz@lib@graph@main@parser{%
  \begingroup%
    \pgfkeyssetvalue{/tikz/graphs/placement/local depth}{0}%
    \pgfkeyssetvalue{/tikz/graphs/placement/local width}{0}%
    \let\tikz@lib@graph@stored@actions\pgfutil@empty%
    \let\tikz@lib@graph@node@list\pgfutil@empty% reset
    \tikz@lib@graph@everychain@hook\tikz@lib@graph@everychain@reset <<< added
    \tikz@lib@graph@main@parser@start%
}%
\makeatother

\begin{document}
Default behavior:\par
\tikz \graph { a -> b [target edge style=blue]; c -> b; };    \qquad
\tikz \graph { a -> b [> blue]; c -> b; };                    \qquad
\tikz \graph { a -> b [> "label" blue]; c -> b; };

Old tricks:\par
\tikz \graph { a -> b [target edge style=blue]; b <- c; };    \qquad % use "b <- c"
\tikz \graph { a -> b [> blue]; c -> b[target edge clear]; }; \qquad % use "target edge clear"
\tikz \graph { a -> b [> "label" blue]; b <- c; };            \qquad
\tikz \graph { a -> b [> "label" blue]; c -> b[target edge clear]; };

New tricks:\par
\tikz \graph { a -> b [one time target edge style=blue]; c -> b; }; \qquad
\tikz \graph { a -> b [> blue, one time edge style]; c -> b; };     \qquad
\tikz \graph { a -> b [> "label" blue, one time edge style]; c -> b; };
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/205844265-c601a978-a8f5-4695-a7b7-6956f5d96ad3.png)

**Comment by mbugert** [comment]
Great input, thanks a lot for clarifying! I find the continuation of the style beyond the semicolon to be unconventional, but that's just my opinion. I will consider your solutions for the one-time edge styles.
