### ISSUE TITLE
Adding multi-line text in latest version works different

### ISSUE THREAD

**Issue by libinxu01** [pgf-tikz/pgf#1225]
### Brief outline of the bug

We've upgraded texlive version from 2016 to 2022 and specified an align=left for node to enforce multi-line text, but the result is quite different. How to resolve it ?

here is the icon-normal-chapter-right-arrow.pdf of MWE:
[icon-normal-chapter-right-arrow.pdf](https://github.com/pgf-tikz/pgf/files/10213798/icon-normal-chapter-right-arrow.pdf)

### Minimal working example (MWE)

```
\documentclass{article}
\NeedsTeXFormat{LaTeX2e}
\usepackage{xcolor}
\usepackage{eso-pic}
\usepackage{etoolbox}
\usepackage{expl3}
\usepackage{l3keys2e}
\usepackage{tikz}
\usepackage{tikzpagenodes}
\usetikzlibrary{
    backgrounds,
    calc,
    intersections,
    shapes.geometric,
    shapes.misc,
    shapes.multipart,
    positioning,
    matrix
}
\usepackage[
    UTF8,
    12pt,
    scheme=chinese,
    autoindent=true,
    heading=false,
    fontset=none,
    linespread=1.5]{ctex}


\ExplSyntaxOn
\newcommand{\test}[1]{
                        \begin{tikzpicture}[node~distance=2mm]
                            \node[inner~sep=0pt,minimum~size=1pt] (NormalChapterNamePlaceHolder) {};
                            \begin{scope}[red]
                                \node[
                                    % align=left,
                                    below=56mm~of~NormalChapterNamePlaceHolder,
                                    inner~xsep=0pt,
                                    inner~ysep=0.5mm,
                                    node~font=\fontsize{18pt}{18pt}\selectfont
                                ] (NormalChapterName) {#1};
                            \end{scope}
                            \node[
                                baseline = NormalChapterName.center,
                                right = of~NormalChapterName,
                                inner~sep = 0pt
                            ] (NormalChapterRightArrow) {\includegraphics{icon-normal-chapter-right-arrow}};
                            \draw[red,line~width=0.15mm]
                                let
                                \p1 = ($(NormalChapterName.south~east)!0.5!(NormalChapterName.north~east) - (NormalChapterName.north~east)$), \n1 = {veclen(\x1, \y1)}
                                in
                                ($(NormalChapterName.north~east) + (2mm, 0pt)$) -- ($(NormalChapterName.north~east) + (3.5mm, 0pt)$)
                                arc[radius=\n1, start~angle=90, end~angle=-90]
                                ($(NormalChapterName.south~east) + (3.5mm, 0pt)$) -- (NormalChapterName.south~west);
                        \end{tikzpicture}
}
\ExplSyntaxOff


\begin{document}
\test{\\ \mbox{aaa}\\ \mbox{bbb}\\}
\end{document}
```

**Comment by hmenke** [comment]
Can you please make a *minimal* example, that does not use packages other than `tikz` and does not include graphics that we don't have?

**Comment by libinxu01** [comment]
> Can you please make a _minimal_ example, that does not use packages other than `tikz` and does not include graphics that we don't have?

MWE has updated, how can I achieve the effect as the first picture shows?

**Comment by muzimuzhi** [comment]
Please make your example _compilable_. Even after I 
- surrounded the definition of `\test` with `\ExplSyntaxOn` and `\ExplSyntaxOff`,
- deleted undefined `\SourceHanSansSCFamily{Medium}` and `\chaptertitlename`,
- replaced `\includegraphics`,
- corrected `\newcommand{\test}{m}` to `\newcommand{\test}[1]`, and
- loaded `ctex` and compiled with xelatex to typeset Chinese characters (or just replaced them with dummy [a-zA-Z] chars)

your example fails with (perhaps) some endless loop. Noted the tiny example below won't end as well:
```tex
\documentclass{article}
\usepackage{tikz}
\usepackage{xstring}

\begin{document}
\tikz \node[align=left] {\StrSubstitute{aa||bb}{\\}{cc}};
\end{document}
```

I also tested in overleaf.com's texlive mirrors, which range from 2014 to 2022. With `align=left`, your example compiles on none of them. Without `align=left`, your example compiles but I can't get your expected texlive-2016 output.

If you do care about why upgrading from texlive 2016 to 2022 caused such differences and errors, please first provide a compilable example that reproduces your expected (old) output on some overleaf's texlive version, or with more info, at least a version list generated by `\listfiles`. (Your example may have over-simplified. It's very unlikely the current last `\draw` will draw three distinct lines, as shown in your expected output.)

If you care more about how to achieve your expected output with texlive 2022, please head to some Q&A forum/mailing list, such as tex.stackexchange.com.

**Comment by libinxu01** [comment]
> Please make your example _compilable_. Even after I
> 
> * surrounded the definition of `\test` with `\ExplSyntaxOn` and `\ExplSyntaxOff`,
> * deleted undefined `\SourceHanSansSCFamily{Medium}` and `\chaptertitlename`,
> * replaced `\includegraphics`,
> * corrected `\newcommand{\test}{m}` to `\newcommand{\test}[1]`, and
> * loaded `ctex` and compiled with xelatex to typeset Chinese characters (or just replaced them with dummy [a-zA-Z] chars)
> 
> your example fails with (perhaps) some endless loop. Noted the tiny example below won't end as well:
> 
> ```
> \documentclass{article}
> \usepackage{tikz}
> \usepackage{xstring}
> 
> \begin{document}
> \tikz \node[align=left] {\StrSubstitute{aa||bb}{\\}{cc}};
> \end{document}
> ```
> 
> I also tested in overleaf.com's texlive mirrors, which range from 2014 to 2022. With `align=left`, your example compiles on none of them. Without `align=left`, your example compiles but I can't get your expected texlive-2016 output.
> 
> If you do care about why upgrading from texlive 2016 to 2022 caused such differences and errors, please first provide a compilable example that reproduces your expected (old) output on some overleaf's texlive version, or with more info, at least a version list generated by `\listfiles`. (Your example may have over-simplified. It's very unlikely the current last `\draw` will draw three distinct lines, as shown in your expected output.)
> 
> If you care more about how to achieve your expected output with texlive 2022, please head to some Q&A forum/mailing list, such as tex.stackexchange.com.

Thank you so much. I've choose another solution and solved the issue.
