### ISSUE TITLE
Allow `above=<coordinate> of <coordinate>` in relative positionning.

### ISSUE THREAD

**Issue by iago-lito** [pgf-tikz/pgf#1227]
### Brief outline of the proposed feature

I like how `\node[above=1mm of <coordinate>]` makes it possible to simplify x-alignment of nodes.

However, we cannot yet use it to *also* simplify y-alignment, which would be made possible if the following syntax were also accepted:

```tikz
\node[above=A of B]
```
.. with `A` and `B` being both *coordinates*.

This specification would unambiguously mean: position the node above `B` so that its y-coordinate matches the y-coordinate of `A`.

### Usage example

```latex
\documentclass{standalone}

\usepackage{tikz}
\usetikzlibrary{positioning}

\begin{document}

\tikz{

  \node (A) {A};
  \node[right=1 of A] (B) {B};
  \node[below=1 of A] (C) {C};

  % Instead of the following:
  \coordinate (temp) at (B |- C);
  \node (D) at (temp) {D};

  % The following could simply just work:
  \node[below=C of B] (D) {D};

  % Or, equivalently:
  \node[right=B of C] (D) {D};

}

\end{document}
```

**Comment by ilayn** [comment]
This is for `at (B|-C)`. Why are you using a temp coordinate for D? 

B of C is also not semantically readable. Note that above etc modifies the anchor of the placed node too. So I'm not sure what this syntax would solve.

**Comment by hmenke** [comment]
I think you can already do this with

```tex
\node[shift={(B|-C)},anchor=west] ...
```

**Comment by iago-lito** [comment]
Alright, I was also worried that "A of B" does not exactly read like natural languages.. and the workarounds seem pretty straightforward.

My use case is that it could make it possible to process `below=#1 of A` in a generic way, but maybe it's a niche need?

Should I close to temper the noise?

**Comment by hmenke** [comment]
BTW, there is also this syntax

```tex
\node[below right=1 and 1 of A] (D) {D};
```

Of course, this is only meaningful with the composite positioning directives like `below right` or `above left`, etc.
