### ISSUE TITLE
The default unit assumed by the 'angle radius' option of the 'angles' TikZ library is 'pt' rather than 'cm' as is the TikZ norm

### ISSUE THREAD

**Issue by EvanAad** [pgf-tikz/pgf#1234]
### Brief outline of the bug

When the `angle radius` option of the `angles` TikZ library is passed a number unaccompanied by an explicit unit, e.g. `1` rather than `1cm`, it assumes the units are points. 

This can be seen in the MWE provided below, which produces the following picture:

![AngleRadius](https://user-images.githubusercontent.com/22092671/217486615-b93496bc-5898-4c41-bf19-4628fc23f60f.png)

This behavior is inconsistent with the normal TikZ convention of assuming unspecified units to be `cm`, it is inconsistent with the canvas polar coordinate system, according to which, for instance, `(90:1)` denotes the point 1cm above the origin, and it is inconsistent with the behavior of the option `radius` of the `circle` path operation.

Furthermore, this behavior means that the `angle radius` is unaffected by a scaling of the TikZ picture and by the settings of its `/tikz/x` and `/tikz/y` keys.

***

See also [this related TeX Stack Exchange post](https://tex.stackexchange.com/q/674420/21685).

### Minimal working example (MWE)

```
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{angles}
\begin{document}
\begin{tikzpicture}
   \coordinate (a) at (1,0);
   \coordinate (b) at (0,0);
   \coordinate (c) at (0,1);

   \draw (a) -- (b) -- (c);

   \draw pic [draw, angle radius = 1cm] {angle=a--b--c};

   \coordinate (d) at (3,0);
   \coordinate (e) at (2,0);
   \coordinate (f) at (2,1);

   \draw (d) -- (e) -- (f);

   \draw pic [draw, angle radius = 1] {angle=d--e--f};
\end{tikzpicture}
\end{document}

**Comment by hmenke** [comment]
It's clearly documented that `angle radius` expects a dimension (and TeX treats `1` as `1pt`)

![Screenshot from 2023-02-08 14-30-06](https://user-images.githubusercontent.com/1903556/217544483-1b68f09a-e55b-42e1-94e6-1c3e3662749f.png)
