### ISSUE TITLE
Feature Request: "mark at" option for plot marks

### ISSUE THREAD

**Issue by e-duckworth** [pgf-tikz/pgf#1237]
When plotting using a function, it would be nice to pass a specific list of points to be marked. Something like the following
```
\begin{tikzpicture}
  \draw plot[domain=0:6, mark at ={1,2,3}] (\x, {sin(\x r)+0.5*\x});
\end{tikzpicture}
```
which would plot from 0 to 6, but add marks only at x =1, 2 and 3.

**Comment by hmenke** [comment]
Feature Request: Please read the documentation before opening issues.

If you have questions about how to use PGF/Ti*k*Z please consult the community forums like https://tex.stackexchange.com/

```tex
\draw plot[mark=x,mark indices={1,2,3}] ...
```

![Screenshot from 2023-02-11 21-43-23](https://user-images.githubusercontent.com/1903556/218280369-3787e7fc-0450-4a53-b7cf-12ee4de3f983.png)

**Comment by e-duckworth** [comment]
Thanks for looking, but I don't think that feature does what I asked.

Mark indices does not use the x-values that are used to calculate the plot.  As I said in the request I'd like it to mark at x=1,2,3, not the 1st, 2nd and 3rd values in the list of x values. The domain I chose may be making it more confusing.  

Suppose I had the domain -10:-5.  I'd like to be able to say "put a mark at x=-7" without figuring out which index corresponds to x = -7 (is the 13th value? Or the 11th?  etc.)

**Comment by muzimuzhi** [comment]
`mark indices` accepts a list of indices, while it seems the requested `mark at` is expected to accept a list of values in definition domain (x-values), which is harder to implement (need to insert these possibly x-values into the samples list and take tolerance into consideration).

**Comment by hmenke** [comment]
You could have a look at the `mark repeat` and `mark phase` which are literally next to `mark indices` in the documentation: https://pgf-tikz.github.io/pgf/pgfmanual.pdf#subsection.22.7

**Comment by e-duckworth** [comment]
I don't see a good way to use `mark repeat` and `mark phase` to produce the same results as the following
```
\begin{tikzpicture}
  \draw plot[domain=0:6] (\x, {sin(\x r)+0.5*\x});
  \draw plot[only marks, mark=*, samples at ={0,2.09,4.19,6}] (\x, {sin(\x r)+0.5*\x});
\end{tikzpicture}
```
This will mark the beginning and end of the plot, and then the local max and min.  It's not so bad with two lines, I just figured it would make sense to not have to repeat so much in the two lines, and just do it in one plot command with one set of options.
