### ISSUE TITLE
TikZ no longer loads in ConTeXt LMTX

### ISSUE THREAD

**Issue by apfelkuchen6** [pgf-tikz/pgf#1248]
### Brief outline of the bug

Since b53f0e06b55d6eb761cc3c480f7d7ecd7a99ce06, TikZ doesn't load in ConTeXT LMTX version 2023-03-20. ~MkIV works fine though.~

### Minimal working example (MWE)

```tex
\usemodule[tikz]
\starttext
  Hello World.
\stoptext
```

output ([full](https://gist.github.com/apfelkuchen6/09f1cfebe6a6d19c9cc0d16fe69cf213)):
```
open source     > level 4, order 33, name 'pgfcorepoints.code.tex'
tex error       > tex error on line 926 in file pgfcorepoints.code.tex: Missing control sequence inserted

<inserted text> 
    
    \inaccessible 
<to be read again> 
    
    "
<macro> \pgfsetzvec 
    \catcode `\==12 \catcode `\,=12 \catcode `\|=12 \catcode `\&=12 \let "
    \pgfmath@char@quote 
<macro> \pgfsetzvec 
    \begingroup \pgfmath@catcodes 
    \pgfmath@quickparsefalse \ifpgfmathfloat \let \pgfmath@parse@next =\pgfmathfloatparsenumber \else \let \pgfmath@parse@next =\pgfmathparse@ \fi \pgfmath@parse@next 
<argument> 
    \pgfmathparse 
    {1cm}\ifpgfmathmathunitsdeclared \pgf@x \pgfmathresult mu\relax \else \pgf@x \pgfmathresult pt\relax \fi 
<macro> \pgfmath@next 
    #1#2->#2
 ...

<line 7.926> 
    \pgfsetxvec{\pgfpoint{1cm}{0cm}}

<empty file>
Please don't say '\def cs{...}', say '\def\cs{...}'. I've inserted an
inaccessible control sequence so that your definition will be completed without
mixing me up too badly.
```

**Comment by muzimuzhi** [comment]
I don't know why but below seems to work. Looks like an issue about loading order.
```tex
\usemodule[pgfrcs,pgfmat]
\usemodule[tikz]

\starttext
  Hello World.
\stoptext
```
Also to load `pgfmath` I have to use `\usemodule[pgfrcs, pgfmat]` to have `\pgfutil@ifundefined` defined before loading `pgfmathutil.code.tex`, otherwise I end with error
```tex
open source     > level 4, order 7, name 'pgfmathutil.code.tex'
tex error       > tex error on line 73 in file pgfmathutil.code.tex: Control sequence expected instead of undefined

<macro> \pgfmath@ifregister 
    #1#2->\pgfutil@IfUndefined 
    {pgfmath@if#1@extract}{\errmessage {Package PGF Math Error: Cannot test for #1 register}}{\pgfutil@IfUndefined {\csname pgfmath@if#1@extract\endcsname {#2}}{\pgfutil@secondoftwo }}{\pgfmath@ifregister@unguarded {#1}{#2}}
<macro> \pgfmath@ensureregister 
    #1#2->\pgfmath@ifregister {#1}{#2}
    {}{\csname new#1\endcsname #2}
<line 7.73> 
    \pgfmath@ensureregister{dimen}{\pgf@x}

<empty file>
You injected something that confused the parser, maybe by using some Lua call.
```
Something on ConTeXt's side has changed?

**Comment by apfelkuchen6** [comment]
Thanks, this really helps a lot.

It appears that around four weeks ago, `m-tikz.mkiv` in texlive has been [drastically altered](https://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/context/modules/mkiv/m-tikz.mkiv?r1=58167&r2=66178). The new version no longer uses pgf's `t-pgf.tex` but loads the files themselves, in a order that is incompatible with recent pgf versions.

The new version is similar (identical?) to the files [m-tikz.mkiv](https://github.com/contextgarden/context/blob/main/tex/context/modules/mkiv/m-tikz.mkiv) and [m-tikz.mkxl](https://github.com/contextgarden/context/blob/main/tex/context/modules/mkxl/m-tikz.mkxl) in the context distribution, which have been like this for almost two years.

We can probably close this here as the issue is not in pgf/tikz.
