### ISSUE TITLE
Default for text format delimiters incorrect

### ISSUE THREAD

**Issue by aendie** [pgf-tikz/pgf#1260]
### Version

3.1.10

### Details

I detect what appears to be a documentation error in versions 3.1.3 (page 648), 3.1.9a (page 657), 3.1.10 (page 656).

The definition reads as follows:
![tikz_decorations](https://github.com/pgf-tikz/pgf/assets/13238632/32d5c6c5-d797-4a22-8d18-69ed37c1d062)

However I believe the default is: (no default, initially **{|}{|}**)
... as there has to be an _after_ delimiter (and it is initially a vertical bar).
Even in the example below both delimiters ('before' and 'after') are employed:
![tikz_decorations2](https://github.com/pgf-tikz/pgf/assets/13238632/92ee1e34-75e0-43c8-8593-6c0408f42b3e)

Funny that no one has noticed this since version 3.1.3 but my thanks to all who have contributed to an absolutely marvelous package that enables me to create beautiful charts and diagrams. (I am competing for fun with the US Naval Observatory Astronomical Applications Department and the HM Nautical Almanac Office in the UK ... with outside help, of course. :-)

**Comment by muzimuzhi** [comment]
From source code, `/pgf/decoration/text format delimiters` _is_ initially `{|}{}`.
https://github.com/pgf-tikz/pgf/blob/9cc2617304cf3c6e7a1f5b21fc049f404f23d3e7/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.text.code.tex#L19
https://github.com/pgf-tikz/pgf/blob/9cc2617304cf3c6e7a1f5b21fc049f404f23d3e7/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.text.code.tex#L170

Actually it's documented that
> If `<after>` is empty, then `<before>` will be used for both delimiters.

see doc for `/pgf/decoration/text format delimiters` ([tikz.dev link](decorations/pgflibrarydecorations.text.code.tex)) and related source lines 161--163 below.
https://github.com/pgf-tikz/pgf/blob/9cc2617304cf3c6e7a1f5b21fc049f404f23d3e7/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.text.code.tex#L158-L170
