### ISSUE TITLE
`\verb` is omitted from `anchor` example code?

### ISSUE THREAD

**Issue by hbghlyj** [pgf-tikz/pgf#1267]
### Version

3.1.10

### Details

In [manual &sect;13.2.3 anchor](https://pgf-tikz.github.io/pgf/pgfmanual.pdf#pgf.anchor) example code:
```tex
\usetikzlibrary {arrows.meta}
\begin{tikzpicture}
\node (shape) at (0,2) [draw] {|class Shape|};
\node (rect) at (-2,0) [draw] {|class Rectangle|};
\node (circle) at (2,0) [draw] {|class Circle|};
\node (ellipse) at (6,0) [draw] {|class Ellipse|};
\draw (node cs:name=circle,anchor=north) |- (0,1);
\draw (node cs:name=ellipse,anchor=north) |- (0,1);
\draw [arrows = -{Triangle[open, angle=60:3mm]}]
(node cs:name=rect,anchor=north)
|- (0,1) -| (node cs:name=shape,anchor=south);
\end{tikzpicture}
```
I compile this code with PDFLaTeX, the output is different from the manual:
![image](https://github.com/pgf-tikz/pgf/assets/53823634/fcc2d989-6665-47d2-9129-095fe4709a7f)

After replacing `|` with `\verb|` the output is same as the manual:
![canvas](https://github.com/pgf-tikz/pgf/assets/53823634/680162c2-8f26-4f28-ae46-2ecc17c3a840)

**Comment by muzimuzhi** [comment]
> I compile this code with PDFLaTeX, the output is different from the manual:

Which document class did you use?

[`pgfmanual.tex`](https://github.com/pgf-tikz/pgf/blob/master/doc/generic/pgf/pgfmanual.tex) loads `ltxdoc.cls` which sets
```tex
\AtBeginDocument{\MakeShortVerb{\|}}
```

An `ltxdoc` example
```tex
\documentclass{ltxdoc}

\begin{document}
normal text
|verb text|
\end{document}
```
![image](https://github.com/pgf-tikz/pgf/assets/6376638/fd619e2b-b591-45e8-8d79-b1feeff1559e)


PS: The command `\MakeShortVerb` is provided by `doc.sty`. It's also available from a sole package `shortvrb` (see `texdoc doc` (v3.0m, 2022/11/13), sec. 2.14 "Short input of verbatim text pieces".
```tex
\documentclass{article}
\usepackage{shortvrb}
\MakeShortVerb{\|}

\begin{document}
normal text
|verb text|
\end{document}
```

**Comment by muzimuzhi** [comment]
When used as part of a node text, both the short verb `|...|` and (long) verb `\verb|...|` forms can't really typeset the content in verbatim (the content is already tokenized), but only in (the current) typewriter font family.

For the sake of
- #640 and
- #1116

using `node font=\ttfamily` here (and for all similar `codeexample`s) seems better. @hmenke opinions?

```tex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{arrows.meta}

\begin{document}
\begin{tikzpicture}[node font=\ttfamily]
  \node (shape)   at (0,2)  [draw] {class Shape};
  \node (rect)    at (-2,0) [draw] {class Rectangle};
  \node (circle)  at (2,0)  [draw] {class Circle};
  \node (ellipse) at (6,0)  [draw] {class Ellipse};

  \draw (node cs:name=circle,anchor=north) |- (0,1);
  \draw (node cs:name=ellipse,anchor=north) |- (0,1);
  \draw [arrows = -{Triangle[open, angle=60:3mm]}]
           (node cs:name=rect,anchor=north)
        |- (0,1) -| (node cs:name=shape,anchor=south);
\end{tikzpicture}
\end{document}
```

**Comment by hmenke** [comment]
Verbatim material inside node text does work. The parser uses `\setbox` specifically to work around the tokenization problem.

https://github.com/pgf-tikz/pgf/blob/425b03d0279717d4a1cdaaac016b70ea02665c30/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex#L3865-L3916

**Comment by muzimuzhi** [comment]
Ah you're right! Then the `codeexample`(s) using `|...|` as short verb may need sth like
```tex
\begin{codeexample}[preamble={\usepackage{shortvrb} \MakeShortVerb{\|}}]
```
Or, as originally suggested, use `\verb|...|` instead.

**Comment by hmenke** [comment]
Since no actual verbatim is required for the example, I prefer your proposal of simply changing the node font to `\ttfamily`.
