### ISSUE TITLE
Irrelevant extra space

### ISSUE THREAD

**Issue by MinooErho** [pgf-tikz/pgf#1291]
### Brief outline of the bug

Hi,
in this simple code, you see Irrelevant extra space in output. when you remove line 7, you get correct output.

![image](https://github.com/pgf-tikz/pgf/assets/135517407/7c8d630d-ada9-4db7-8154-004d99926017)

### Minimal working example (MWE)

\documentclass{standalone}
\usepackage{tikz}

\begin{document}
\parindent0pt
\newbox\A
\setbox\A\hbox{A}
\begin{tikzpicture}
\node(n)[draw,text width=15,inner sep=0,minimum height =6]at (0,0){120};
\end{tikzpicture}\end{document}

**Comment by muzimuzhi** [comment]
It's caused by a space character converted from the newline character for line `\setbox\A\hbox{A}`, by TeX.

```tex
\documentclass{standalone}
\usepackage{tikz}

\begin{document}
\parindent0pt
\newbox\A
\setbox\A\hbox{A}%
\begin{tikzpicture}
  \node(n)[draw,text width=15,inner sep=0,minimum height =6]at (0,0){120};
\end{tikzpicture}
\end{document}
```
![image](https://github.com/pgf-tikz/pgf/assets/6376638/903503fb-9d5b-4e12-ac41-9a8e77041f66)

**Comment by MinooErho** [comment]
no, tikz/pgf should control this.

**Comment by MinooErho** [comment]
there's no newline character.

![image](https://github.com/pgf-tikz/pgf/assets/135517407/353db68f-18ef-4018-9095-5f352a43aeb3)

**Comment by muzimuzhi** [comment]
Some more words.

@MinooErho The "irrelevant extra space" you got is more relevant to `standalone` document class, which by default changes the starting mode of content of `document` environment from vertical to horizontal. In v-mode, initial space is skipped, while in h-mode it is kept.

These ways also remove the extra space:
- Move `\newbox\A \setbox\A\hbox{A}` into preamble.
- Use `\documentclass[tikz]{standard}`, which will collect every `tikzpicture` in an `\hbox`, typeset it on a single page, and crop the page. (You may also be interested in `standalone` class option `ignorerest`.)
  `\documentclass[tikz]{standard}` is equivalent to `\documentclass{standalone} \usepackage{tikz} \standaloneenv{tikzpicture}`.

**Comment by MinooErho** [comment]
Muzi you are a very good friend in GitHub. 👍
i'm not alone. :)
Thanks for your tryings.

[ilayn](https://github.com/ilayn) is a poor dumb refugee turk.
