### ISSUE TITLE
Right angle without a dot in Angle library

### ISSUE THREAD

**Issue by quark67** [pgf-tikz/pgf#1301]
### Brief outline of the proposed feature

On several countries, the right angle is marked by a square without a dot on its center (as a non-right angle is also marked without a point, simply by an arc).
See https://en.wikipedia.org/wiki/Right_angle#Symbols
 Perhaps you can add a pic type `non german right angle`, or `international right angle` or `standard right angle` or `universal right angle` or `non dotted right angle` or an other name so in other country we can use the Angle library for displaying a right angle with the Angle library on geometric constructions.

### Usage example

```
\draw pic  {non german right angle = A--O--B}
```

**Comment by muzimuzhi** [comment]
There's no dot by default. In the example for `pic` type `right angle`, the dot in red is added manually by setting `pic text=.` (near the end of line 99 below).

https://github.com/pgf-tikz/pgf/blob/14ef7f3494766f3df4c9b177bec1e5695ec980f5/doc/generic/pgf/pgfmanual-en-library-angles.tex#L88-L103

**Comment by quark67** [comment]
Oh, sorry for the mistake. I will close then this issue.

**Comment by muzimuzhi** [comment]
> In the example for `pic` type `right angle`, the dot in red is added manually by setting `pic text=.` (near the end of line 99 below).

Along with `angle eccentricity=.5` which controls position of `pic text`.
