### ISSUE TITLE
Minor typo in documentation of calendar /tikz/every day key

### ISSUE THREAD

**Issue by user202729** [pgf-tikz/pgf#1325]
### Version

3.1.9a

### Details

![image](https://github.com/pgf-tikz/pgf/assets/25191436/36a8723f-bd8e-4ccf-bb8a-d5fb7894183b)

The formatting seems

**Comment by muzimuzhi** [comment]
After
![image](https://github.com/pgf-tikz/pgf/assets/6376638/54b934e9-b749-4284-84ba-42ec61bf42c0)
