### ISSUE TITLE
Suggestion: raise an error if `\path` is used in `\pgfextra` without `\pgfinterruptpath`

### ISSUE THREAD

**Issue by user202729** [pgf-tikz/pgf#1328]
As in the title.

Disadvantage is that it will incur an additional check i.e. runtime penalty. Advantage is that it will prevent inadvertent errors in the code which can save user/developer's time.

**Comment by muzimuzhi** [comment]
Or, in a more general way, execute `\tikz@uninstallcommands` and `\tikz@installcommands` at the beginning and ending of `\pgfextra` code, respectively? In this way, `\path` and other tikz commands used in `\pgfextra` code would take their definitions outside of `tikzpicture`.
https://github.com/pgf-tikz/pgf/blob/12f17834c849a659b8829bbc9122bc459f585917/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex#L2558-L2566

Related to
- #1327

**Comment by muzimuzhi** [comment]
> Or, in a more general way, execute `\tikz@uninstallcommands` and `\tikz@installcommands` at the beginning and ending of `\pgfextra` code, respectively?

Hmm, No. The suggested way would disable (at least make it harder) use of
```tex
\pgfextra{\pgfinterruptpath \path ...; \endpgfinterruptpath}
```

**Comment by hmenke** [comment]
This would break existing documents, therefore unfortunately rejected.

**Comment by user202729** [comment]
I think a document that issues `\path` without `\pgfinterruptpath` is **buggy** and should be fixed anyway.

[Adding Tikz node in pgfextra triggers double drawing of containing path - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/131077/adding-tikz-node-in-pgfextra-triggers-double-drawing-of-containing-path) (not exactly the same issue but related)

That said, we can just make it a warning. I see no harm (cf. `pgfplots` run in stable mode by default, but upgrading `pgfplots` may make the document issue an extra warning)
