### ISSUE TITLE
TikZ creates <-> arrow when -> is specified when using node angles

### ISSUE THREAD

**Issue by el-sambal** [pgf-tikz/pgf#1343]
### Brief outline of the bug

I tried drawing a -> arrow between two specified points (at angles w.r.t. a node), but a <-> arrow was created instead. The MWE produces this:

![image](https://github.com/pgf-tikz/pgf/assets/115483969/d2a06f39-8308-45e5-aa42-dc18214b397b)

An arrowhead appears both in the top and the bottom of the arrow, but my intended result was that it would only appear in the bottom.

(The use case is to produce two parallel edges, in a way similar to the first solution contained in user121799's answer to [this question](https://tex.stackexchange.com/questions/448655/parallel-edges-between-states-in-tikz).)

Thank you!

### Minimal working example (MWE)

```latex
\documentclass{article}
\usepackage{tikz}

\begin{document}

\begin{tikzpicture}
	\node[circle,fill=cyan] (a) at (0,1) {$a$};
	\node[circle,fill=cyan] (b) at (0,-1) {$b$};
	\draw[->] (a.-120) edge (b.120);
\end{tikzpicture}

\end{document}

```

**Comment by el-sambal** [comment]
I noticed that changing
`
\draw[->] (a.-120) edge (b.120);
`
to
`
\draw (a.-120) edge[->] (b.120);
`
fixes the issue.

But I don't think this is how Ti<i>k</i>Z should behave; please correct me if I'm wrong.

**Comment by ilayn** [comment]
edge is a special path with its own settings. If you don't need it just use the regular path command which is `--`.

**Comment by hmenke** [comment]
You need to use `\path[->] (a.-120) edge (b.120);`. Otherwise you are drawing a path with no segments. To see what I mean, try `\draw[->] (a.-120) edge[red] (b.120);` and observe that the “wrong” arrow tip remains black.

**Comment by el-sambal** [comment]
Ah I see, thanks a lot for your help!
