### ISSUE TITLE
Non-commuting draw options

### ISSUE THREAD

**Issue by AndrewMathas** [pgf-tikz/pgf#1346]
### Brief outline of the bug

My understanding is that the MWE below should produce two circles with a green boundary and a yellow fill. However, swapping the order of the style commands inside the `\draw` command results in the `fill=yellow` style being ignored:

<img width="261" alt="Screenshot 2024-07-07 at 09 31 36" src="https://github.com/pgf-tikz/pgf/assets/26611383/df267509-6f33-4a6a-9e0e-e5590de7ba05">

### Minimal working example (MWE)

```tex
\documentclass{article}
\usepackage{tikz}
\begin{document}

  \begin{tikzpicture}
    \draw[green,fill=yellow] (0,0) circle [radius=1];
    \draw[fill=yellow,green] (2,0) circle [radius=1];
  \end{tikzpicture}

\end{document}
```

**Comment by muzimuzhi** [comment]
This is expected behavior.

Using `<color>` as option key is equivalent to `color=<color>` (see https://tikz.dev/tikz-scopes#sec-12.4.1), which

> sets the color that is used for fill, drawing, and text inside the current scope. Any special settings for filling colors or drawing colors are immediately “overruled” by this option.
> <sub>_see https://tikz.dev/tikz-actions#pgf./tikz/color_</sub>
