### ISSUE TITLE
No clickable links with hyperref and tikzexternalize

### ISSUE THREAD

**Issue by amblafont** [pgf-tikz/pgf#1356]
### Brief outline of the bug

Cross-references are not clickable when using the hyperref package with the tikzexternalize feature (texlive 2024).

### Minimal working example (MWE)

```latex
\documentclass{article}


\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize
\usepackage{hyperref}


\begin{document}
\begin{equation}
A
\label{eq:eq}
\end{equation}

\begin{tikzpicture}
% The reference is not clickable
\node {\ref{eq:eq}};
\end{tikzpicture}

\end{document}
```

**Comment by hmenke** [comment]
This is a natural limitation of `\includegraphics` and can only be worked around with external tooling.
See https://tex.stackexchange.com/questions/26128/embedding-a-pdf-file-with-clickable-external-links-into-a-latex-document
