### ISSUE TITLE
Wrong explanation

### ISSUE THREAD

**Issue by un-lo-so** [pgf-tikz/pgf#1374]
### Version

3.1.10

### Details

Hi!
In section 12.2.1 - Creating a Picture Using an Environment i read this 

/tikz/baseline=〈dimension or coordinate or default〉 (default 0pt)
Normally, the lower end of the picture is put on the baseline of the surrounding text. For example,
when you give the code \tikz\draw(0,0)circle(.5ex);, pgf will find out that the lower end of
the picture is at −.5ex − 0.2pt (the 0.2pt are half the line width, which is 0.4pt) and that the upper
end is at .5ex + **.5pt**. 

but it should be

/tikz/baseline=〈dimension or coordinate or default〉 (default 0pt)
Normally, the lower end of the picture is put on the baseline of the surrounding text. For example,
when you give the code \tikz\draw(0,0)circle(.5ex);, pgf will find out that the lower end of
the picture is at −.5ex − 0.2pt (the 0.2pt are half the line width, which is 0.4pt) and that the upper
end is at .5ex + **.2pt**.

Regards.

**Comment by muzimuzhi** [comment]
Nice catch, thank you!
