### ISSUE TITLE
Probalby a wrong assumption in the dvisvgm driver

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#327]
*Migrated from SourceForge*
Author: respawned
Timestamp: 2014-07-31 18:41:58.374000

It seems that the brand new dvisvgm driver isn't quite generating output according to the current design/contract of dvisvgm's specials. Basically those are currently excluded from a lot of dvisvgm's interanl processing, including the determination of bounding boxes. According to its http://dvisvgm.sourceforge.net/Manpage, dvisvgm expects that the DVI will contain explicit calls to dvisvgm:bbox for any material added via dvisvgm specials.

So PGF output using the current dvisvgm driver will always results bad SVG viewport (width/height) and view boxes, clipping out anything that's actually drawn with PGF and doesn't have some extra text in it. In the very example from the PGF manual, the blue dot gets left out, as you can see at http://imgur.com/a/1JPmW (Inkscape does show SVG contents outside the viewport, which it depicts as by a rectangle there, but web browsers just clip out the extra material.)

This is the kind of issue whose resolution is probably best coordinated with the main author on the other side. I've actually tried to convince him that it's not unreasonable to implement the same kind of processing (including bbox determination) for dvisvgm's own specials as he does for PostScript etc. See discussion at https://answers.launchpad.net/dvisvgm/+question/252461 But technically PGF's driver is the part containing a bug for now.

**Comment by dcpurton** [comment]
I don't know whether it's due to changes in `dvisvgm` or `pgf`, but this no longer seems to happen.

**Comment by hmenke** [comment]
I think this refers to the really old `dvisvgm` driver which was in place at that point.  I will mark it as fixed. Thanks for checking!
