### ISSUE TITLE
Cannot use pgf-blur twice with XeLaTex

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#374]
*Migrated from SourceForge*
Author: symbol-1
Timestamp: 2015-12-18 04:44:16.986000

I asked before on
http://tex.stackexchange.com/questions/206947/cannot-use-pgf-blur-twice-with-xelatex

The following code

````
\documentclass{article}
%\def\pgfsysdriver{pgfsys-dvipdfmx.def} %this line does not matter
\usepackage{tikz}\usetikzlibrary{shadows.blur}
\begin{document}
    \begin{tikzpicture}
        \draw[blur shadow](-2,0)circle(1);
        \draw[blur shadow](0,0)rectangle(3,2);
    \end{tikzpicture}
\end{document}
````

gives obviously different result under `pdftex` and `xelatex`.

I checked `tikzlibraryshadows.blur.code.tex` and all I can found is that on line 142
````
\def\pgfbs@usefadepath#1{%
  \pgfsyssoftpath@setcurrentpath{\pgfbs@fadepath}%
  \pgfsyssoftpath@flushcurrentpath%
  \pgfusepath{#1}%
}
````
the `\pgfbs@fadepath` seems to be the correct path. But the result is not correct.

**Comment by hmenke** [comment]
In TeX Live 2019 the output of the MWE is the same with pdf-, xe-, and luatex.  I'm closing this for now.
