### ISSUE TITLE
bug when trying to store `\pgfplotstablegetrowsof` with `\pgfmathsetmacro`

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#382]
*Migrated from SourceForge*
Author: mo-gul
Timestamp: 2016-03-29 15:38:24.013000

For simplicity here I only copy some lines of emails in German which should act as a reminder for Christian.

My email:

[...] könntest du mal einen kurzen Blick auf
	<http://tex.stackexchange.com/a/299200/95441>
werfen und mir sagen, ob es ein Bug ist, dass ich `\NoOfRows` nicht in `\pgfplotstablegetelem` verwenden kann. [...]

His answer:

[...] das mit `\NoOfRows` ist eine Mischung aus der komplizierten Nutzung der FPU engine und einem fehlenden sanity check (=bug).

Was passiert ist dass `\NoOfRows` auf `1Y4.0e0` gesetzt wird, was soviel heisst wie "+ 4.0 * 10^0". Als Zeilennummer interpretiert scheint der aber nur die "1" genommen zu haben und den Rest stillschweigend weggeworfen zu haben. [...]

**Comment by hmenke** [comment]
@Mo-Gul Isn't this a `pgfplots` bug?  Can you provide a MWE?

**Comment by Mo-Gul** [comment]
Most likely you are right. I created a new ticket in the PGFPlots Tracker (https://sourceforge.net/p/pgfplots/bugs/230/).
