### ISSUE TITLE
user error leading to unexpected loop

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#408]
*Migrated from SourceForge*
Author: davidcarlisle
Timestamp: 2016-11-13 13:52:40.263000

this arises from a user question at

http://tex.stackexchange.com/questions/338869/pdflatex-hangs-on-a-pending

after

```
\documentclass{article}
\usepackage{tikz}
\makeatletter
\protected\def\tikz@signal@path{\tikz@signal@path}%
\makeatother
\begin{document}
  \begin{tikzpicture}[
    \draw[blue] (0,0) -- (1,1);
  \end{tikzpicture}
\end{document}
```

tex loops  exanding \tikz@signal@path forever.
```

\def\tikz@signal@path{\tikz@signal@path}
\tikz@signal@path
```

In the answer I suggested an etex \protected def but I wasn't totally sure why the test is using the recursive definition, here it seems:

`\def\tikz@lib@matrix@check#1{% evil hackery to find out about start of path`

so \protected may be wrong or there are of course non e-tex alternatives

David

**Comment by hmenke** [comment]
This was coincidentally fixed by 967233884 because [this additional assignment](https://github.com/pgf-tikz/pgf/commit/967233884eff8a17eb7a538569936ee51981bf90#diff-a4488c97a111c6d672db09732df61e6fR2021) explodes on expansion with `! Undefined control sequence`
