### ISSUE TITLE
topaths ending with at end

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#412]
*Migrated from SourceForge*
Author: jetlund
Timestamp: 2017-01-03 10:16:05.648000

I suspect this is a bug

    \documentclass{article}
    \usepackage{tikz}
    \usetikzlibrary{circuits}

    \begin{document}
    \begin{tikzpicture}[circuit]
    \draw (0,0) to [circuit handle symbol={draw,shape=rectangle,at start}] (0,3);
    \draw (1,3) to [circuit handle symbol={draw,shape=rectangle,at end}] (1,0);
    \end{tikzpicture}
    \end{document}
    
Compiled with expected output before upgrading pgf. The two lines ending in a small rectangle should be identical. In the case of at end it seems that the rectangle is rotated and thus moving the paths end point from the expected end point.

**Comment by schtandard** [comment]
I suspect the spurious lines inside the symbols is the same bug? Or should I open a separate ticket for that?

**Comment by schtandard** [comment]
This issue disappears with

	\tikzset{
		at start/.style={pos=0.0},
		at end/.style={pos=1.0},
	}

So the bug seems to be that `pos=1` and `pos=1.0` are treated differently.

**Comment by hmenke** [comment]
@schtandard The comparison was too literal.  It compared the value of `pos` with the string literal `0.0` and if `pos=0` the comparison was false.  I replaced it by an `\ifdim` comparison which should work for any representation of zero, regardless of the number of decimal digits.
