### ISSUE TITLE
rotate around rectangle with named coordinates

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#456]
*Migrated from SourceForge*
Author: schiticioppi
Timestamp: 2017-08-20 18:05:46.133000

If I name `\coordinate (b) at (1,2)` and try to `rotate around` a rectangle drawn with `(a) rectangle (b)` I get wrong results:

```
\documentclass[tikz]{standalone}

\begin{document}

\begin{tikzpicture}
	\fill (0,-1) circle [radius=2pt];
	\draw[red,rotate around={90:(0,-1)}] (0,0) rectangle (1,2);
	
	\coordinate (a) at (0,0);
	\coordinate (b) at (1,2);
    \draw (a) rectangle (b);
    
	\draw[blue,rotate around={45:(0,-1)}] (a) rectangle (b);
	\draw[yellow,rotate around={60:(0,-1)}] (a) rectangle (b);
	\draw[red,rotate around={89:(0,-1)}] (a) rectangle (b);
\end{tikzpicture}
    
\end{document}
```

It... keeps fixed the coordinates I gave for the rectangle, and sort of rotates the rest. That's certainly not what I was expecting, and anyway is not consistent with the behaviour in `(0,0) rectangle (1,2)`.

(My first ticket, hope it's done correctly)

**Comment by hmenke** [comment]
What is going on here is that `\coordinate (a) at (0,0);` associates the point `(0,0)` *in the current coordinate system* to `(a)`.  So when you rotate the coordinate system but request `(a)`, you will get the point `(0,0)` in the coordinate system that was active when `(a)` was assigned.

In fact, PGF is going out of its way to undo any transformation when determining node anchors.  You can of course disable this, such that node anchors always rotate with the coordinate system but that will of course wreak havoc elsewhere.
```patch
diff --git a/tex/generic/pgf/modules/pgfmoduleshapes.code.tex b/tex/generic/pgf/modules/pgfmoduleshapes.code.tex
index a80804e7..189e4923 100644
--- a/tex/generic/pgf/modules/pgfmoduleshapes.code.tex
+++ b/tex/generic/pgf/modules/pgfmoduleshapes.code.tex
@@ -551,8 +551,6 @@
       % Add inter picture transformation
       \pgf@shape@interpictureshift{#1}%
       % Undo current transformation
-      \pgftransforminvert%
-      \pgf@pos@transform@glob%
     }%
   }%
 }%
```

The correct way to achieve what you want is of course to put everything in a scope and rotate the scope.
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}

\begin{tikzpicture}
  \begin{scope}[rotate around={90:(0,-1)}]
    \coordinate (a) at (0,0);
    \coordinate (b) at (1,2);
    \draw (a) rectangle (b);
  \end{scope}
\end{tikzpicture}
    
\end{document}
```

Therefore I'm marking this as wont-fix.
