### ISSUE TITLE
Add support for spot colors

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#603]
*Migrated from SourceForge*
Author: gaborit
Timestamp: 2013-11-15 12:46:10.844000

Can you add support for spot colors in TikZ/Pgf ?

A very good first attempt is visible here: <http://tex.stackexchange.com/a/145127>.

Thanks.

**Comment by hmenke** [comment]
@polgab From the linked thread it looks like support for spot colors is provided in a nice fashion by the `xspotcolor` package.  I don't see a reason why we should integrate this functionality in TikZ.

**Comment by polgab** [comment]
Two reasons:
1. My request dates from 2013. The `xsptocolor` package only exists since 2016.
2. The `xspotcolor` patches some `pgf` internal macros...
