### ISSUE TITLE
Accept the … (unicode) symbol in \foreach command

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#608]
*Migrated from SourceForge*
Author: yoblanco
Timestamp: 2014-03-23 17:46:43.292000

That's it. I would like to be able to use `…` in `\foreach` constructions, instead of `...` (three dots).

    \foreach \x in {1,…,10}{\x~}

This is my first ticket, and I don't know if this is the right way of doing this features requests.

**Comment by hmenke** [comment]
PGF has to work with non-Unicode engines.  Also having an extra branch in the parsing code just makes it slower without adding any real functionality.
