### ISSUE TITLE
Add transformation matrix to pattern definition

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#612]
*Migrated from SourceForge*
Author: vibrovski
Timestamp: 2014-10-01 08:22:52.857000

Provide means of adding a transformation matrix to a pattern. It is supported by the PDF specification (see sections 4.6.1 and 4.6.2 of the 3rd edition). 

It is easy to hack the system layer to achieve this, what is required is a "nice" or "sensible" way of doing it.

**Comment by hmenke** [comment]
This is already there.  It just needs to be documented.
