### ISSUE TITLE
Provide a configure script which searches lua and other pathes automatically and validates presence of build dependencies

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#615]
*Migrated from SourceForge*
Author: krichter722
Timestamp: 2014-12-20 03:54:14.301000

In conjunction with change to git (https://sourceforge.net/p/pgf/feature-requests/72/) the possibility for developers/people interested in the source would be completed and a lot of time saved to get started.

**Comment by hmenke** [comment]
PGF is now in TDS format, so you can use the [`usertree`](https://tex.stackexchange.com/questions/448263/is-there-a-way-to-create-tex-live-or-latex-virtual-environment) method of TeX Live to use the development version alongside the installed version.
```console
$ git clone https://github.com/pgf-tikz/pgf
$ tlmgr init-usertree --usertree pgf
$ TEXMFHOME=`realpath pgf` pdflatex test.tex
```
