### ISSUE TITLE
Add latex' and stealth' arrow tips to arrows.meta

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#617]
*Migrated from SourceForge*
Author: petobens
Timestamp: 2015-03-29 21:51:03.477000

I've recently started using the new `arrows.meta` library and discovered that the `stealth'` and `latex'` arrow tips were not ported. 
Is it possible to add these arrow tips to `arrows.meta` libray?

See also this [question](http://tex.stackexchange.com/questions/150289/how-do-you-accomplish-stealth-with-the-new-arrows-meta) and this [one](http://tex.stackexchange.com/questions/234084/latex-arrow-tip-with-arrows-meta-library?noredirect=1#comment557788_234084) on tex.stackexchange.

Thank you!

**Comment by hmenke** [comment]
I don't see a reason why.  Just load the old `arrows` library to access `stealth'` and `latex'`.
