### ISSUE TITLE
missing every xx styles

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#621]
*Migrated from SourceForge*
Author: tobiasweh
Timestamp: 2015-12-31 09:34:06.938000

Hi,

could you please add `every edge node` and `every edge node label`?

Best,
Tobi

**Comment by hmenke** [comment]
@tweh Can you please explain in more detail what this is good for?

**Comment by hmenke** [comment]
No response, closing for now.

**Comment by tweh** [comment]
Sorry for the late response!

I think those style could help to set some general things on nodes on edges, so they have basically the same purpose as all of the `every …` styles. In the following example the code would be much cleaner if the requested styles where available.

```tex
\documentclass[tikz,border=5mm]{standalone}

\begin{document}
\begin{tikzpicture}[
   every node/.style = {
      draw,
      minimum size = 15mm,
      ultra thick,
      font = \bfseries\LARGE,
   },
   every edge node/.style = {
      circle,
      minimum size = 10mm,
      text = white,
      draw = none,
      fill = black,
      font = \bfseries\sffamily,
   },
   label distance = -5mm,
   every edge node label/.style = {
      font = \footnotesize,
   },
   every edge/.style = {draw, ->, double},
]
   \node (A) at (0,0) {A};
   \node (B) at (2.5,5) {B};
   \node (C) at (5,0) {C};
   \draw (A) edge node [every edge node, label={[every edge node label]180:1}] {ab} (B);
   \draw (A) edge node [every edge node, label={[every edge node label]270:1}] {ac} (C);
   \draw (B) edge node [every edge node, label={[every edge node label]0:2}] {bc} (C);
\end{tikzpicture}
\end{document}
```

Of course on could define own style with shorter names, which would also provide a logical markup, but for smaller graphics the use of `every …` is the better way in my eyes.

**Comment by hmenke** [comment]
I just tested this:
```diff
diff --git a/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex b/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
index 99a478eb..453915e1 100644
--- a/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
+++ b/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
@@ -3067,7 +3067,15 @@
               \let\tikz@options=\pgfutil@empty%
               \tikz@clear@rdf@options%
               \let\tikz@tonodes=\tikz@collected@onpath%
-              \def\tikztonodes{{\pgfextra{\tikz@node@is@a@labeltrue}\tikz@tonodes}}%
+              \def\tikztonodes{{%
+                \pgfextra{%
+                  \tikzset{
+                    every node/.append style={every edge node},
+                    every label/.append style={every edge node label}
+                  }%
+                  \tikz@node@is@a@labeltrue
+                }%
+                \tikz@tonodes}}%
               \let\tikz@collected@onpath=\pgfutil@empty%
               \tikz@options%
               \tikz@do@rdf@pre@options%
```
It doesn't work and it can't work, because labels are nodes themselves, which results in `every edge node` and `every edge node label` overwriting each other.  If you have a different solution which works properly, please submit a pull request.  I am closing this for now.

**Comment by tweh** [comment]
Sorry for the late reply …

I see the problem but don’t have a solution, so just keep this issue closed an I’ll stick to custom styles, which is better for a clear markup anyway … thanks!
