### ISSUE TITLE
Provide a derivative and integral function in pgfmath 

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#623]
*Migrated from SourceForge*
Author: student357
Timestamp: 2016-06-21 11:21:53.602000

Some time ago there were two questions on TeX.sx of about how to plot the derivative of a function and how to plot the integral function numerically: 

- http://tex.stackexchange.com/questions/73920/get-derivative-of-a-function/73924#73924
- http://tex.stackexchange.com/questions/103569/can-pgf-plot-the-integral-of-any-specified-function?lq=1

As suggested in a comment to the second question by Matthew Leingang, a simple solution just to provide the functions diff and int in pgfmath, as defined as follows:

diff(f(x)) = (f(x + h) - f(x))/h

where h is a small constant, say h = 0.001 by default.

Similar int should return the numerical integral. See Jakes answer in the second link for an example.

**Comment by hmenke** [comment]
There can be no general-purpose integral or derivative function because it would have to account for singularities and such.
