### ISSUE TITLE
Better SVG path parser

### ISSUE THREAD

**Issue by pgf-tikz-bot** [pgf-tikz/pgf#628]
*Migrated from SourceForge*
Author: kpymtzanev
Timestamp: 2017-04-01 06:56:46.798000

The `svg.path` library can't parse some valid paths when spaces are missing. For example the valid svg path `M0,0 l0.5.5` (that is equivalent to `M0,0 l0.5 .5` with space before the `.5`) generates an error.

The parser should parse a number until it is a valid (in the case of `0.5.5` it should read the number `0.5` because there is no valid number starting with `0.5.`) and then continue like if the last symbol was space.

Another problem is that `svg.path` library can't parse scientific notations. For example the path `M0,0 l0.5 .1e1` (that is equivalent to `M0,0 l0.5 1`) is not understood by the library.

Here is a link to the [official svg path grammer](https://www.w3.org/TR/SVG/paths.html#PathDataBNF).

**Comment by hmenke** [comment]
Parsing SVG is rather non-trivial and the PGF SVG parser is rather to play around with than a standard-conforming fully functional SVG parser.  There are many tools that can export SVG paths to TikZ, so if you need standard-conformity, that is the route to go.

**Comment by Skillmon** [comment]
Got a fix. Currently dependent on my new parser PR. Can port it to the old parser if needed.

**Comment by Skillmon** [comment]
Just noticed that the link in the initial comment doesn't specify scientific notation to be part of the coordinate grammar, so strictly speaking `0.1e1` would result in an error in SVG. My fix allows those in PGF.

**Comment by hmenke** [comment]
No need to port it to the old parser, just make it part of your PR.  If the grammar doesn't allow scientific notation, PGF shouldn't either.  The SVG parser it not standard-conforming already, let's not make it deviate even more.

**Comment by Skillmon** [comment]
The problem is that the number definition used in that particular source wouldn't allow decimal values at all. Because of that I searched for another manual (https://www.w3.org/TR/SVG11/paths.html#PathDataBNF) and that one allows scientific notation. I somehow trust the second one more :) I'll leave the scientific notation in.

**Comment by Skillmon** [comment]
Found another related bug, `+` wasn't handled at all, now it should be handled correctly. Also I forgot about a possible sign after `e` (also fixed in 8a7d45a).

**Comment by kpym** [comment]
Thanks for fixing this !
About the SVG grammer, there was a [bug](https://github.com/w3c/svgwg/issues/286) in the [SVG specifications](https://github.com/w3c/svgwg) that was finally [corrected](https://github.com/w3c/svgwg/pull/697) : so the scientific notation is, and always has been, part of the SVG.

**Comment by Skillmon** [comment]
@kpym as I suspected :) Thanks for sharing that information.
