### ISSUE TITLE
Feature request: is coordinate defined

### ISSUE THREAD

**Issue by daleif** [pgf-tikz/pgf#646]
Often when I do trace images for people, I make a lot of helper coordinates. It is useful to be able to mark them. But I do not want to maintain a list of my defined coordinates, nor do I want to number my coordinates sequentially. At one point I came up with the MWE below. It works for normal coordinates, but not for things like node positions.

So I'm requesting a feature one can use to determine whether a coordinate/.. is defined.

```latex
\documentclass[tikz]{standalone}
\makeatletter
% handy macro, then the loop does not need to be over only defined nodes
\def\ifcoordinatedefined#1#2#3{%
  \@ifundefined{pgf@sh@ns@#1}{#3}{#2}%
}
\makeatother

\newcommand\ShowPoints[1][0,1,...,200]{
  \begingroup
  \foreach\n in{#1}{
    \ifcoordinatedefined{T\n}{
      \fill[green,opacity=0.75] (T\n) circle (1pt) node[below,red] {\tiny\n};
    }{}
  }
  \endgroup
}

\begin{document}

\begin{tikzpicture}
  \draw (0,0) circle (1);
  \coordinate (T0) at (0,0);
  \coordinate (T1) at (1,0);
  \node[draw,anchor=west] (A) at (T1) {Test};

  % this works
  \ShowPoints

  % this does not work
  \ifcoordinatedefined{A.north east}{
    \fill[magenta] (A.north east) circle (2pt);
  }{}
  
  
\end{tikzpicture}

\end{document}
```

**Comment by hmenke** [comment]
`A.north east` is not a coordinate but a node anchor.

**Comment by daleif** [comment]
Thanks, I did not know the proper terminology for A.north east

**Comment by hmenke** [comment]
You can use this bit to check for the existence of an anchor.

https://github.com/pgf-tikz/pgf/blob/fcb8edbd888202e6842204300a1dae26f2fa33ed/tex/generic/pgf/modules/pgfmoduleshapes.code.tex#L487-L499

The problem is that `A.180` is a valid anchor, so if you try to reference a non-existent anchor, like `A.weest`, PGF will try to evaluate `weest` as a math function which will fail.

https://github.com/pgf-tikz/pgf/blob/fcb8edbd888202e6842204300a1dae26f2fa33ed/tex/generic/pgf/modules/pgfmoduleshapes.code.tex#L492

There is no way to check whether something is a valid math expression or not prior to evaluation.

**Comment by daleif** [comment]
Then it seems best to at least just check for existence on coordinates. Then users will just have to make aliases for anchors if they want to use the test.

Wouldn't that be doable?

(I have yet to actually need to test on an anchor)

**Comment by hmenke** [comment]
I have a possible patch ready here https://github.com/hmenke/pgf/commit/98b9d6bf661a069efa41b55cfbc02e3de07144b6 but I'm wondering whether this is so useful.

**Comment by daleif** [comment]
can that test coordinates as well? I don't quite understand it.

**Comment by hmenke** [comment]
This is just the same definition as you had for `\ifcoordinatedefined` but renamed to `\pgfifnamedshapeundefined` and with true and false branch flipped to match the new name.

**Comment by hmenke** [comment]
I figured that this is not really worth providing in the PGF core, because it ca be implemented by a user in literally a single line.
