### ISSUE TITLE
\pgfuseshading does not respect paragraph indent under xelatex and dvips

### ISSUE THREAD

**Issue by dcpurton** [pgf-tikz/pgf#655]
`\pgfuseshading` behaves differently under `xelatex` and  `dvips` as compared with `pdflatex` and `lualatex`. The normal paragraph indent is not respected under `xelatex` and `dvips`. I think this was present in older versions of `pgf` but I can't be sure now.

Consider this example:

```TeX
\documentclass{article}
\usepackage{pgf}
\begin{document}
Paragraph indent

\pgfdeclareradialshading{ballshading}{\pgfpoint{-10bp}{10bp}}
{color(0bp)=(red!15!white); color(9bp)=(red!75!white);
color(18bp)=(red!70!black); color(25bp)=(red!50!black); color(50bp)=(black)}
\pgfuseshading{ballshading}

Paragraph indent
\end{document}
```

# `xelatex` (and `dvips`) output

![psshadingregression](https://user-images.githubusercontent.com/6268044/56177933-94f80880-603f-11e9-8c89-2a3f32e0ef3c.png)

# `pdflatex` (and `lualatex`) output

![psshadingregression](https://user-images.githubusercontent.com/6268044/56178019-ca9cf180-603f-11e9-9933-e11f5907db0b.png)

**Comment by hmenke** [comment]
It's hard to say which one is “correct”.  I'll check out the history.

**Comment by hmenke** [comment]
I can reproduce this with versions as old as `version-2-00`.

**Comment by hmenke** [comment]
Patch pending https://github.com/hmenke/pgf/commit/05e9f49beb7564e774979dbb07ffe3cb1ec439e4

**Comment by dcpurton** [comment]
I just checked and the `dvisvgm` driver is also affected by this. Currently `dvisvgm` (and `tex4ht`) indent `\pgfuseshading`, (like `pdflatex` did in the original bug report).

**Comment by hmenke** [comment]
`dvisvgm` does the correct thing for me.  My browser seems to have some problems with the fonts but the indent looks correct.
![test](https://user-images.githubusercontent.com/1903556/56484545-969e5200-64bf-11e9-81b7-7897ee612276.png)
For `tex4ht` the situation is trickier. To me it seems as if `tex4ht` just wrapped everything in a `<p>` tag, but I can't find any reference to that in the PGF driver code, so I would say that this is not our department.

**Comment by hmenke** [comment]
I fixed `dvisvgm` in https://github.com/pgf-tikz/pgf/commit/c424685ad89f64bac13e36dd0a87386cc3c939c4.  That should have also fixed `tex4ht` but for some reason that still doesn't work.

**Comment by dcpurton** [comment]
That's weird. I don't get that output for `dvisvgm`. I'll investigate more.

**Comment by hmenke** [comment]
I forgot to switch the driver.  I have deleted my comment since.

**Comment by hmenke** [comment]
The “fix” broke everything else. I had to revert it.  The fundamental problem is that rather flushing the shading directly, the `dvisvgm` and `tex4ht` driver wrap it into a picture, so they transform a shading which originally appeared outside a picture into one that appears inside a picture.  On the other hand, I wonder whether it is even worth spending time on fixing this, because I don't think a lot of clients use `\pgfuseshading`.
