### ISSUE TITLE
Regression in dvips shading driver

### ISSUE THREAD

**Issue by dcpurton** [pgf-tikz/pgf#656]
The ball shading example in '§113.3 Using Shadings' of the manual no longer works as expected with the current git version of `pgf`.

Consider this example (latex, dvips, ps2pdf):

```TeX
\documentclass{article}
\usepackage{pgf}
\begin{document}
\pgfdeclareradialshading{ballshading}{\pgfpoint{-10bp}{10bp}}
{color(0bp)=(red!15!white); color(9bp)=(red!75!white);
color(18bp)=(red!70!black); color(25bp)=(red!50!black); color(50bp)=(black)}
\pgfuseshading{ballshading}
\hskip 1cm
\begin{pgfpicture}
  \pgfpathrectangle{\pgfpointorigin}{\pgfpoint{1cm}{1cm}}
  \pgfshadepath{ballshading}{0}
  \pgfusepath{}
  \pgfpathcircle{\pgfpoint{3cm}{0cm}}{1cm}
  \pgfshadepath{ballshading}{0}
  \pgfusepath{}
  \pgfpathcircle{\pgfpoint{6cm}{0cm}}{1cm}
  \pgfshadepath{ballshading}{45}
  \pgfusepath{}
\end{pgfpicture}
\end{document}
```

# Output with `pgf 3.1.1`

![psshadingregression](https://user-images.githubusercontent.com/6268044/56178380-3b90d900-6041-11e9-8a7e-1b863ce86095.png)

# Output with commit f7b2a4ac22981a3aa8c2062d0e481915725d8d34

![psshadingregression](https://user-images.githubusercontent.com/6268044/56178451-75fa7600-6041-11e9-824b-863696d076ec.png)

# Reference output from `lualatex` with commit f7b2a4ac22981a3aa8c2062d0e481915725d8d34

I'm not sure what is behind the difference in layout. But perhaps it's related to #655.

![psshadingregression](https://user-images.githubusercontent.com/6268044/56178491-99bdbc00-6041-11e9-823f-589b060ff208.png)

**Comment by hmenke** [comment]
Bisecting gave https://github.com/pgf-tikz/pgf/commit/350971220aa5f364db825f38060beaaf65a30854

**Comment by hmenke** [comment]
Patch pending https://github.com/hmenke/pgf/commit/ca0da2e07ebb2da1fc2d7b09b744c88a67a44aa7
