### ISSUE TITLE
Content lines in TOC of parts II and III look bad

### ISSUE THREAD

**Issue by joulev** [pgf-tikz/pgf#673]
In the Table of Contents, bottom of [page 4](https://pgf-tikz.github.io/pgfmanual-0004.svg):

![](https://i.stack.imgur.com/IASoW.png)

It is clearly better if the content line of Part II goes to the next page.

Consequently, the content line of Part III also looks bad:

![](https://i.stack.imgur.com/Q6yWs.png)

I think an approach [here](https://tex.stackexchange.com/q/103998/156344) to the content line of Part II only will make the content lines of these two parts _much_ better. Moreover, the whole Part II will be on the same page, which is very good IMHO.

**Comment by hmenke** [comment]
Did you also read [Enrico's comment](https://tex.stackexchange.com/questions/103998/how-to-force-a-table-of-contents-to-start-new-page#comment227047_103999) on that?

> Doing this only when the document is in "really final, no more changes, definitely" form. ;-)

**Comment by joulev** [comment]
Yes. However, to me it is now "almost completed", at least in near future there will be no new sections in Part I for example, so we can safely use Oberdiek's approach. When there is a new section in Part I or a new subsection in the Introduction, we will remove this single line &ndash; but I don't think such thing will happen in near future.

**Comment by hmenke** [comment]
You can always add such micro-optimizations by yourself and retypeset the manual from source.  Instructions are given in the [README](https://github.com/pgf-tikz/pgf#development).

**Comment by Jamiemcasa** [comment]
T
