### ISSUE TITLE
Spaces missing in “divide by zero” error message

### ISSUE THREAD

**Issue by PhelypeOleinik** [pgf-tikz/pgf#679]
The code:
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\tikz \draw (1/0,0) -- (1,1);
\end{document}
```
produces the error message:
```none
! Package PGF Math Error: You'veaskedmetodivide`1'by`0',butIcannotdivideanynumb
erby`0' (in '1/0').

See the PGF Math package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.4 \tikz \draw (1/0,0)
                        -- (1,1);
?
```

If I didn't know better I'd say someone loaded `expl3` in PGF--Ti*k*Z ;-)

**Comment by josephwright** [comment]
In a sense it is :) If you do a quick trace, you find
```latex
\pgfmath@declarefunction #1#2->\pgfmath@namedef {pgfmath@function@#1}{#1}\pgfma
th@namedef {pgfmath@operation@#1@type}{function}\pgfmath@namedef {pgfmath@opera
tion@#1@arity}{#2}\pgfmath@namedef {pgfmath@operation@#1@infix}{#1}\pgfmath@nam
edef {pgfmath@operation@#1@precedence}{1000}\expandafter \ifx \csname pgfmath@o
peration@#1@arity\endcsname \pgfmath@dots \pgfmath@namedef {pgfmath@operation@#
1@arity}{1}\else \ifnum \csname pgfmath@operation@#1@arity\endcsname >9\relax \
pgfmath@namedef {pgfmath@operation@#1@arity}{1}\fi \fi \edef \pgfmath@marshal {
\noexpand \pgfmath@@declarefunction {\expandafter \noexpand \csname pgfmath#1\e
ndcsname }{\expandafter \noexpand \csname pgfmath#1@\endcsname }{\csname pgfmat
h@operation@#1@arity\endcsname }}\begingroup \catcode `\	=9\relax \catcode `\ =
9\relax \catcode `\~=10\relax \endlinechar =`\ \relax \pgfmath@marshal 
```
which you'll see ends with setting space to ignore, `~` to a space and `\endlinechar` to a space.

**Comment by Maxtercam** [comment]
pics/axes/.style args={#1:#2;#3:#4}{
    code = {
      \path[grid] (#1-.5,#3-.5) grid (#2+.5,#4+.5);
      \draw[->,axis] (#1 - .5,0) -- (#2 + .5,0);
      \draw[->,axis] (0,#3 - .5) -- (0,#4 + .5);
      \foreach \x in {#1,...,#2} {
        \ifnum\x=0\else
        \draw[axis] (\x,0) -- (\x,-.2);
        \node[below left] at (\x+.1,-.2) {\(\x\)};
        \fi
      }
      \node[below] at (#2+.5,-.2) {\(x\)};
      \foreach \y in {#3,...,#4} {
        \ifnum\y=0\else
        \draw[axis] (0,\y) -- (-.2,\y);
        \node[below left] at (-.1,\y) {\(\y\)};
        \fi
      }
      \node[left] at (-.1,#4+.5) {\(y\)};
      \node[below left] at (0,0) {0};
    }
  },
pics/axes/.default={-6:6;-6:6},

**Comment by hmenke** [comment]
BTW, this broke when fixing this https://github.com/pgf-tikz/pgf/issues/508
