### ISSUE TITLE
Placing a node on a path with cycle applies a double transformation.

### ISSUE THREAD

**Issue by loopspace** [pgf-tikz/pgf#682]
MWE:

~~~latex
\documentclass{article}

\usepackage{tikz}

\begin{document}

\begin{tikzpicture}
\draw (0,0) -- node[auto] {a} (1,0) -- node[pos=0] {b} node[pos=1] {c} cycle;
\begin{scope}[xshift=2cm]
\draw (0,0) -- node[auto] {a} (1,0) -- node[pos=0] {b} node[pos=1] {c} cycle;
\end{scope}
\begin{scope}[yshift=2cm,scale=3]
\draw (0,0) -- node[auto] {a} (1,0) -- node[pos=0] {b} node[pos=1] {c} cycle;
\end{scope}
\end{tikzpicture}
\end{document}
~~~

In the second and third cases, the `c` is incorrectly placed.  This is because in the definition of the `\tikz@timer@end` in `\tikz@@close` then the end of the path is defined to be the coordinates saved from last moveto as recorded by the underlying soft path.  However, this has the current transformation applied to it which isn't what is needed in `\tikz@timer@end`.

One possible fix is to record the coordinates of a `moveto` at the TikZ level and use that instead.  I've had a go at implementing it at https://github.com/loopspace/pgf/commit/ffc197432ec5ad6e165549aa2c67970b3c56b383

One thing I'm not sure about in that is whether to use the soft path position when setting the last position within `\tikz@@close` or to use the new one.

(To be clear, I'm not proposing this as a fix that is ready - I'm asking if this looks like a reasonable way to fix this.  I suspect that there will be other changes that need making before it can be considered fixed.)

**Comment by loopspace** [comment]
This is the same issue as in https://github.com/pgf-tikz/pgf/issues/423

**Comment by hmenke** [comment]
Thanks for pointing it out.  I closed the old issue in favour of this one, because this one has a proper MWE.

**Comment by hmenke** [comment]
Merged https://github.com/pgf-tikz/pgf/commit/7a6b3e7465796c60159dff922762014cc907365d and https://github.com/pgf-tikz/pgf/commit/ffc197432ec5ad6e165549aa2c67970b3c56b383.
