### ISSUE TITLE
Straight quotes should not be rendered as smart quotes in the documentation

### ISSUE THREAD

**Issue by dbitouze** [pgf-tikz/pgf#683]
In the PDF file of the documentation, the straight quotes in code sample are rendered as smart quotes. This makes these samples fail to compile with the error:

> ! Missing \endcsname inserted.
>  ...
>                   \OT1\textquoteright

For instance, this is the case for the code to be found on page 568 of the documentation (version 3.1.3):

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{arrows, automata, positioning}

\begin{document}

\begin{tikzpicture}[->,>=stealth’,shorten >=1pt,%
                    auto,node distance=2cm,on grid,semithick,
                    inner sep=2pt,bend angle=45]
  \node[initial,state] (A)                    {$q_a$};
  \node[state]         (B) [above right=of A] {$q_b$};
  \node[state]         (D) [below right=of A] {$q_d$};
  \node[state]         (C) [below right=of B] {$q_c$};
  \node[state]         (E) [below=of D]       {$q_e$};

  \path [every node/.style={font=\footnotesize}]
        (A) edge              node {0,1,L} (B)
            edge              node {1,1,R} (C)
        (B) edge [loop above] node {1,1,L} (B)
            edge              node {0,1,L} (C)
        (C) edge              node {0,1,L} (D)
            edge [bend left]  node {1,0,R} (E)
        (D) edge [loop below] node {1,1,R} (D)
            edge              node {0,1,R} (A)
        (E) edge [bend left]  node {1,0,R} (A);
\end{tikzpicture}

\end{document}
```

**Comment by hmenke** [comment]
Why should copy-pasting from the PDF work?  It doesn't work for anything else in TeX (like math) and there is no way to preserve spaces.

**Comment by hmenke** [comment]
This is the offending line by the way:
https://github.com/pgf-tikz/pgf/blob/07959624c5e4c50f80ddf31a3b271885237b37cc/doc/generic/pgf/text-en/pgfmanual-en-main-preamble.tex#L156-L157
Another related issue is https://github.com/pgf-tikz/pgf/issues/385, which is another incarnation of the same problem but which I marked wont-fix.

**Comment by dbitouze** [comment]
>Why should copy-pasting from the PDF work? It doesn't work for anything else in TeX (like math) and there is no way to preserve spaces.

I don't see your point, except for _vertical_ blank spaces. Copy-pasting the code displayed in the PDF generated by the following `.tex` file is OK (tested with several PDF viewers on Linux) and the pasted code can be tested without any trouble:

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{textcomp}
\usepackage{listings}

\lstset{%
  basicstyle=\ttfamily,%
  upquote,
  columns=flexible
}

\begin{document}
\begin{lstlisting}
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{tikz}
\usetikzlibrary{arrows, automata, positioning}
\begin{document}
\section{A Ti\textit{k}Z picture}
\begin{tikzpicture}[->,>=stealth',shorten >=1pt,%
                    auto,node distance=2cm,on grid,semithick,
                    inner sep=2pt,bend angle=45]
  \node[initial,state] (A)                    {$q_a$};
  \node[state]         (B) [above right=of A] {$q_b$};
  \node[state]         (D) [below right=of A] {$q_d$};
  \node[state]         (C) [below right=of B] {$q_c$};
  \node[state]         (E) [below=of D]       {$q_e$};

  \path [every node/.style={font=\footnotesize}]
        (A) edge              node {0,1,L} (B)
            edge              node {1,1,R} (C)
        (B) edge [loop above] node {1,1,L} (B)
            edge              node {0,1,L} (C)
        (C) edge              node {0,1,L} (D)
            edge [bend left]  node {1,0,R} (E)
        (D) edge [loop below] node {1,1,R} (D)
            edge              node {0,1,R} (A)
        (E) edge [bend left]  node {1,0,R} (A);
\end{tikzpicture}

\section{A very nice math formula}
$e^{i\pi}+1 = 0$
\end{document}
\end{lstlisting}
\end{document}
```

**Comment by hmenke** [comment]
That's a cool story but your example code is completely irrelevant to the PGF manual, which does not use `listings`.

**Comment by dbitouze** [comment]
> your example code is completely irrelevant to the PGF manual, which does not use listings.

And? Is it a reason for closing the issue? Maybe it is however possible to improve the TikZ documentation from this point of view.

**Comment by joulev** [comment]
@dbitouze The `codeexample` environment in the manual, AFAIK, is based on `verbatim`. I do not think you can copy the code from `verbatim` in the right way.

If you want to "improve" the documentation using `listings` or `minted`, I totally disagree. There are many _special_ features offered by the `codeexample` environment, especially the automatic cross-reference, which I rely on literally everyday. and which, in my opinion, makes the PGF manual different from the rest. And do you think such a feature can be implemented easily using `listings`?

Of course you can make a pull request which redefines `codeexample` to a `listings`-based environment (and I will appreciate it), but `codeexample` is now perfect (or nearly perfect as the syntax highlighting doesn't always work well), in my point of view. IMHO you never have to (or should never) copy and paste code from the manual (why do you have to do so, when the output is exactly on the left of the code?), but you should _read_ it and try to _understand_ it. Ti*k*Z is like any other programming languages, where code-copying never gives a positive result. But when you have understood it, you will be able to code it from scratch by yourself...

**Comment by dbitouze** [comment]
@joulev Hmmm...

> I do not think you can copy the code from verbatim in the right way.

Of course it is possible. Please try:

```latex
\documentclass{article}
\begin{document}
\begin{verbatim}
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{tikz}
\usetikzlibrary{arrows, automata, positioning}
\begin{document}
\section{A Ti\textit{k}Z picture}
\begin{tikzpicture}[->,>=stealth',shorten >=1pt,%
                    auto,node distance=2cm,on grid,semithick,
                    inner sep=2pt,bend angle=45]
  \node[initial,state] (A)                    {$q_a$};
  \node[state]         (B) [above right=of A] {$q_b$};
  \node[state]         (D) [below right=of A] {$q_d$};
  \node[state]         (C) [below right=of B] {$q_c$};
  \node[state]         (E) [below=of D]       {$q_e$};

  \path [every node/.style={font=\footnotesize}]
        (A) edge              node {0,1,L} (B)
            edge              node {1,1,R} (C)
        (B) edge [loop above] node {1,1,L} (B)
            edge              node {0,1,L} (C)
        (C) edge              node {0,1,L} (D)
            edge [bend left]  node {1,0,R} (E)
        (D) edge [loop below] node {1,1,R} (D)
            edge              node {0,1,R} (A)
        (E) edge

 [bend left]  node {1,0,R} (A);
\end{tikzpicture}

\section{A very nice math formula}
$e^{i\pi}+1 = 0$
\end{document}
\end{lstlisting}
\end{document}
\end{verbatim}
\end{document}
```
The only drawback is the smart instead of the straight quote, but see below.

> If you want to "improve" the documentation using listings or minted, I totally disagree.

I never said that.

> There are many special features offered by the codeexample environment, especially the automatic cross-reference, which I rely on literally everyday. and which, in my opinion, makes the PGF manual different from the rest.

I totally agree.

> And do you think such a feature can be implemented easily using listings?

I guess it is possible but that's not the point: I'm just asking to have straight and not smart quotes in the copied-pasted code samples and BTW, it is possible with only the `verbatim` default environment and the `upquote` package:

```latex
\documentclass{article}
\usepackage{upquote}
\begin{document}
\begin{verbatim}
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{tikz}
\usetikzlibrary{arrows, automata, positioning}
\begin{document}
\section{A Ti\textit{k}Z picture}
\begin{tikzpicture}[->,>=stealth',shorten >=1pt,%
                    auto,node distance=2cm,on grid,semithick,
                    inner sep=2pt,bend angle=45]
  \node[initial,state] (A)                    {$q_a$};
  \node[state]         (B) [above right=of A] {$q_b$};
  \node[state]         (D) [below right=of A] {$q_d$};
  \node[state]         (C) [below right=of B] {$q_c$};
  \node[state]         (E) [below=of D]       {$q_e$};

  \path [every node/.style={font=\footnotesize}]
        (A) edge              node {0,1,L} (B)
            edge              node {1,1,R} (C)
        (B) edge [loop above] node {1,1,L} (B)
            edge              node {0,1,L} (C)
        (C) edge              node {0,1,L} (D)
            edge [bend left]  node {1,0,R} (E)
        (D) edge [loop below] node {1,1,R} (D)
            edge              node {0,1,R} (A)
        (E) edge

 [bend left]  node {1,0,R} (A);
\end{tikzpicture}

\section{A very nice math formula}
$e^{i\pi}+1 = 0$
\end{document}
\end{lstlisting}
\end{document}
\end{verbatim}
\end{document}
```
The resulting PDF is attached ([test.pdf](https://github.com/pgf-tikz/pgf/files/3207200/test.pdf)) and you can copy its content, paste it to your TeX editor and run `pdflatex`: everything works as expected.

> Of course you can make a pull request which redefines `codeexample` to a listings-based environment (and I will appreciate it), but `codeexample` is now perfect (or nearly perfect as the syntax highlighting doesn't always work well), in my point of view.

`codeexample` is also only nearly perfect because of these smart quotes.

> IMHO you never have to (or should never) copy and paste code from the manual (why do you have to do so, when the output is exactly on the left of the code?), but you should read it and try to understand it.

I totally disagree: it is quite useful, when an example in a package's documentation does almost what you need, to copy paste the code and to adapt it to your actual needs. This is especially true for TikZ code samples as the one above, which seem quite intricate at a first glance.

> TikZ is like any other programming languages, where code-copying never gives a positive result. But when you have understood it, you will be able to code it from scratch by yourself...

I totally disagree: being able to easily get the same code in your  test `.tex` file and play with it rather to have to retype everything is clearly an advantage, and I'm not the only one who thinks so: see issue  #640 which has been welcome and [SSCCE](http://sscce.org/).

**Comment by dbitouze** [comment]
@hmenke `\usepackage[T1]{fontenc}` is not the culprit:

```latex
\documentclass{article}
\usepackage[T1]{fontenc} % <--
\usepackage{upquote}
\begin{document}
\begin{verbatim}
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{tikz}
\usetikzlibrary{arrows, automata, positioning}
\begin{document}
\section{A Ti\textit{k}Z picture}
\begin{tikzpicture}[->,>=stealth',shorten >=1pt,%
                    auto,node distance=2cm,on grid,semithick,
                    inner sep=2pt,bend angle=45]
  \node[initial,state] (A)                    {$q_a$};
  \node[state]         (B) [above right=of A] {$q_b$};
  \node[state]         (D) [below right=of A] {$q_d$};
  \node[state]         (C) [below right=of B] {$q_c$};
  \node[state]         (E) [below=of D]       {$q_e$};

  \path [every node/.style={font=\footnotesize}]
        (A) edge              node {0,1,L} (B)
            edge              node {1,1,R} (C)
        (B) edge [loop above] node {1,1,L} (B)
            edge              node {0,1,L} (C)
        (C) edge              node {0,1,L} (D)
            edge [bend left]  node {1,0,R} (E)
        (D) edge [loop below] node {1,1,R} (D)
            edge              node {0,1,R} (A)
        (E) edge

 [bend left]  node {1,0,R} (A);
\end{tikzpicture}

\section{A very nice math formula}
$e^{i\pi}+1 = 0$
\end{document}
\end{lstlisting}
\end{document}
\end{verbatim}
\end{document}
```

**Comment by hmenke** [comment]
Yes, `\usepackage[T1]{fontenc}` *is* the problem.  Again, your example is of absolutely no use in the context of the PGF manual.  Please stop spamming the thread with unrelated code.
I also feel that you have no idea how any of those things work.  The `codeexample` environment uses `\scantokens` which immediately rules out the usage of any active characters.  If you look at the implementation of either the `upquote` package or the `verbatim` environment you will see that they attempt to solve the apostrophe vs single right quotation mark using an *active character*.

**Comment by hmenke** [comment]
https://github.com/pgf-tikz/pgf/commit/6f2a726cee4749d1b210e237735c5f9a60f07de9 should implement what you want.  I'm marking this as wont-fix anyway.

**Comment by dbitouze** [comment]
@hmenke Please do not confuse spamming and legitimate attempts to help. Hopefully there are many less rude contributors.
