### ISSUE TITLE
Possible tikz regression in combination with gnuplot

### ISSUE THREAD

**Issue by seijikun** [pgf-tikz/pgf#691]
Hey guys, 
I already opened an issue for this at gnuplot [here](https://sourceforge.net/p/gnuplot/bugs/2180/), but it seems to be either a tikz/pgf or a lualatex regression.

Here is a simplified version of the example, containing only tikz code (making use of the `gnuplot-lua-tikz` helper macros that come with gnuplot): [example.zip](https://github.com/pgf-tikz/pgf/files/3269675/example.zip)

When this example is compiled with `pdflatex`, everything works as expected. However, when it is compiled with `lualatex`, it only produces an empty page. Running this same example with an older TeX installation (same version of `gnuplot-lua-tikz`) seems to work.

The original full example for reproduction (using gnuplot) can be found in the gnuplot-issue. (Bear in mind, however, that that example is currently additionally hit by a gnuplot-bug)

Thank you for your awesome work!

**Comment by hmenke** [comment]
LuaTeX has its own driver file `pgfsys-luatex.def`.
The problem is that the`gnuplot-lua-tikz` macros lack support for the LuaTeX driver and therefore fall back to the default which is to produce HTML (someone must have thought that would be a good idea).
Workaround:
```latex
\let\actualpgfsysdriver\pgfsysdriver
\def\pgfsysdriver{pgfsys-pdftex.def} % We are producing PDF not HTML
\usepackage{gnuplot-lua-tikz}
\let\pgfsysdriver\actualpgfsysdriver
```
I will not comment any further on the quality of these macros.

**Comment by hmenke** [comment]
A fix has been committed upstream at gnuplot.
https://sourceforge.net/p/gnuplot/gnuplot-main/ci/e99a2e58ceb0c4f6179ea57105c3fbc8fbc9d9b3/

**Comment by seijikun** [comment]
Thank you very much for fixing this upstream!
