### ISSUE TITLE
Late node position callback used twice

### ISSUE THREAD

**Issue by projekter** [pgf-tikz/pgf#693]
When using late node positioning, at the end the temporary name is finally converted into the correct one:
https://github.com/pgf-tikz/pgf/blob/d5aca9fa743cd97a4688db48268bc0b7eab79230/tex/generic/pgf/modules/pgfmoduleshapes.code.tex#L309-L312
However, `\pgfnoderename` calls `\pgfnodealias`, which already makes use of the callback, resulting in a double callback. So unless I am mistaken, `\pgf@nodecallback` in this macro is actually superfluous (and, depending on the callback, _may_ even be harmful).

**Comment by hmenke** [comment]
No MWE.

**Comment by projekter** [comment]
This is a completely useless non-answer.  This is not some user-code problem but instead a possible bug that the one who wrote this can easily confirm or tell why there is a good reason to use the callback twice.

**Comment by hmenke** [comment]
I'm not the original developer of PGF/TikZ, so I treat it as a legacy code base, i.e. if something cannot be demonstrated to be a bug I do not touch it.

**Comment by projekter** [comment]
Ok, then I'll construct a MWE 
```LaTeX
\documentclass{article}

\usepackage{tikz}

\newcount\nodenumber

% Taken directly from the documentation
\newbox\mybox
\def\mysaver{
   \global\setbox\mybox=\box\pgfpositionnodelaterbox
   \global\let\myname=\pgfpositionnodelatername
   \global\let\myminx=\pgfpositionnodelaterminx
   \global\let\myminy=\pgfpositionnodelaterminy
   \global\let\mymaxx=\pgfpositionnodelatermaxx
   \global\let\mymaxy=\pgfpositionnodelatermaxy
}

\begin{document}
   \makeatletter
   \section*{Direct}
      \begin{tikzpicture}
         \def\pgf@nodecallback#1{\global\advance\nodenumber by 1\relax}
         \foreach \i in {0, ..., 9} {
            \node at (\i, 0) {\i};
         }
      \end{tikzpicture}\\
      We got \the\nodenumber{} named nodes.
   \section*{Deferred}
      \nodenumber=0\relax%
      \begin{tikzpicture}
         \def\pgf@nodecallback#1{\global\advance\nodenumber by 1\relax}
         \pgfpositionnodelater{\mysaver}
         \foreach \i in {0, ..., 9} {
            \node {\i};
            \let\pgfpositionnodelatername=\myname
            \let\pgfpositionnodelaterminx=\myminx
            \let\pgfpositionnodelaterminy=\myminy
            \let\pgfpositionnodelatermaxx=\mymaxx
            \let\pgfpositionnodelatermaxy=\mymaxy
            \setbox\pgfpositionnodelaterbox=\box\mybox
            \pgfpositionnodenow{\pgfqpoint{\i cm}{0pt}}
         }
      \end{tikzpicture}\\
      We got \the\nodenumber{} named nodes.
\end{document}
```

Always, I generate ten nodes and count them using the callback. However, when I count them directly, the number is correct, while for any late positioned node the counter is increased twice, though the nodes are only created once, of course.

At the moment, the callback (which is an undocumented feature) is used only in `pgfmodulematrix.code.tex`, which does not use the late positioning feature. For a package I'm developing, I use both and wondered why the callback was always used far too often.
However, since the callback itself is undocumented, there is no specification that says "it is called exactly once whenever a node is (finally) created (including aliasing/renaming)", so that I cannot say that this is strictly a bug, though it pretty much feels like one.
