### ISSUE TITLE
[manual] Replace deprecated arrows used in codeexamples

### ISSUE THREAD

**Issue by Mo-Gul** [pgf-tikz/pgf#698]
Although the `arrows` and `arrows.spaced` libraries are deprecated, still a lot of `codeexample`s use the arrow tips provided by these libraries. Because I am working anyway through the manual because of issue #640 this would be the chance to update the arrows to the `arrows.meta` library.

**Comment by hmenke** [comment]
You tend to get ahead of yourself.  How about you first address the 2000 other codeexamples before diving headfirst into other “optimizations”?

**Comment by hmenke** [comment]
I believe this was fixed in https://github.com/pgf-tikz/pgf/pull/746
