### ISSUE TITLE
log Missing character on certain bending library and arrows

### ISSUE THREAD

**Issue by kryde** [pgf-tikz/pgf#701]
Similar to my bug 700, in recent Debian PGF 3.1.1, a file

\documentclass[a4paper]{article}
\usepackage{tikz}
\usetikzlibrary{bending}
\begin{document}
\begin{tikzpicture}
  \node (A) at (0,0) {A};
  \node (B) at (10,0) {B};
  \draw[<->] (A) .. controls +(-45:7) and +(-135:7) .. (B);
\end{tikzpicture}
\end{document}

processed "latex foo.tex" gives in foo.log messages

Missing character: There is no p in font nullfont!
Missing character: There is no t in font nullfont!
Missing character: There is no p in font nullfont!
Missing character: There is no t in font nullfont!

The output seems about right, but I wondered if it indicated anything doubtful internally.

I struck this in an actual document, but with no obvious ill effect.  On chopping it down to a test case, it seemed to depend subtly on bending library loaded, and two way <-> arrow, and long enough control points, or some combination of such.

**Comment by hmenke** [comment]
Sorry, that one is not easy to backport.

**Comment by hmenke** [comment]
You could use the workaround proposed by Heiko, though: https://tex.stackexchange.com/questions/179297/lots-of-missing-character-messages-in-log-file/179313#179313
But after all, it's just a warning.
