### ISSUE TITLE
gcd does no longer work.

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#706]
The code `\pgfmathparse{gcd(4,9)}\pgfmathresult` yields 

> 4

but my math professor told me it should be 1.

**Comment by hmenke** [comment]
Works on latest `master`.  Most likely related to 1a3aad0aa8f759c333c2524376c9952a6053ee01

**Comment by hmenke** [comment]
You can work around it by adding some `\relax`.
```latex
\documentclass{article}
\usepackage{tikz}

\makeatletter
\pgfmathdeclarefunction*{gcd}{2}{%
  \begingroup
    \pgfmathcontinuelooptrue
    \pgfmath@xa=#1pt\relax % <-
    \pgfmath@xb=#2pt\relax % <-
    \ifdim\pgfmath@xa=0pt\relax
      \pgfmathcontinueloopfalse
      \pgfmath@xa=\pgfmath@xb
    \fi
    \ifdim\pgfmath@xb=0pt\relax
      \pgfmathcontinueloopfalse
      \pgfmath@xb=\pgfmath@xa
    \fi
    \ifdim\pgfmath@xa<0pt\relax
      \pgfmath@xa=-\pgfmath@xa
    \fi
    \ifdim\pgfmath@xb<0pt\relax
      \pgfmath@xb=-\pgfmath@xb
    \fi
    \loop
      \ifpgfmathcontinueloop
      \ifdim\pgfmath@xa=\pgfmath@xb
        \pgfmathcontinueloopfalse
      \else
        \ifdim\pgfmath@xa>\pgfmath@xb
          \advance\pgfmath@xa by-\pgfmath@xb\relax
        \else
          \advance\pgfmath@xb by-\pgfmath@xa\relax
        \fi
      \fi
    \repeat
    \pgfmathparse{int(\pgfmath@xa)}%
    \pgfmath@smuggleone\pgfmathresult
  \endgroup}
\makeatother

\begin{document}
\pgfmathparse{gcd(4,9)}\pgfmathresult
\end{document}
```

**Comment by Mo-Gul** [comment]
@hmenke, when I am not mistaken PGFPlots (already) has some tests for the math stuff. Maybe these can be added to PGF as well and hopefully also automatically run on Travis CI. Shall I ask Christian for his help on that?

**Comment by hmenke** [comment]
Yes please.  That is probably worthwhile, so we can avoid these kinds of problems in the future.

**Comment by Mo-Gul** [comment]
Christian answered that the tests **are** already located in the TikZ repository. I think I have found them under
https://github.com/pgf-tikz/pgf/tree/master/source/generic/pgf/testsuite/mathtest
