### ISSUE TITLE
Invalid PDF when including graphics with XeLaTeX

### ISSUE THREAD

**Issue by Wrzlprmft** [pgf-tikz/pgf#707]
My minimal example is unfortunately very big and looks like this:

``` TeX
\documentclass{article}
\usepackage{pgf}
\begin{document}
\includegraphics{triangle.pdf}

\begin{pgfpicture}%
{{lots and lots of PGF code}}
\end{pgfpicture}%

\end{document}
```
The full code can be found [in this gist](https://gist.github.com/Wrzlprmft/9aeea16c55c455e2556e66a35e27c8ea). The required file `triangle.pdf` is [attached](https://github.com/pgf-tikz/pgf/files/3387051/triangle.pdf), though every PDF seems to have the same effect.

When I compile this with `xelatex` (Version 3.14159265-2.6-0.99999 (TeX Live 2019/dev/Debian)), I get a corrupt PDF. There are no errors (except an overfull `\hbox`). This problem vanishes when I do the following:

* Compile this with `pdflatex` instead of `xelatex`.
* Remove the `includegraphics` line.
* Shorten the PGF code in almost any valid way.

In case it matters, the PGF code was created by Matplotlib and somewhat shortened by my attempts to find a minimal example.

**Comment by hmenke** [comment]
Can you please construct an actual minimal example?  I'm not going to debug 2600 lines of code.

**Comment by hmenke** [comment]
```console
$ xelatex bug.tex
$ qpdf --check bug.pdf
checking bug.pdf
PDF Version: 1.5
File is not encrypted
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect
```
When I add `\listfiles` to the preamble I get this.
```
 *File List*
 article.cls    2018/09/03 v1.4i Standard LaTeX document class
  size10.clo    2018/09/03 v1.4i Standard LaTeX file (size option)
     pgf.sty    2019/07/12 v3.1.4 (3.1.4-1-g7dae7bfc)
  pgfrcs.sty    2019/07/12 v3.1.4 (3.1.4-1-g7dae7bfc)
everyshi.sty    2001/05/15 v3.00 EveryShipout Package (MS)
  pgfrcs.code.tex
 pgfcore.sty    2019/07/12 v3.1.4 (3.1.4-1-g7dae7bfc)
graphicx.sty    2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
graphics.sty    2017/06/25 v1.2c Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
   xetex.def    2017/06/24 v5.0h Graphics/color driver for xetex
  pgfsys.sty    2019/07/12 v3.1.4 (3.1.4-1-g7dae7bfc)
  pgfsys.code.tex
pgfsyssoftpath.code.tex    2019/07/12 v3.1.4 (3.1.4-1-g7dae7bfc)
pgfsysprotocol.code.tex    2019/07/12 v3.1.4 (3.1.4-1-g7dae7bfc)
  xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
   color.cfg    2016/01/02 v1.6 sample color configuration
 pgfcore.code.tex
pgfcomp-version-0-65.sty    2019/07/12 v3.1.4 (3.1.4-1-g7dae7bfc)
pgfcomp-version-1-18.sty    2019/07/12 v3.1.4 (3.1.4-1-g7dae7bfc)
triangle.pdf    Graphic file (type pdf)
```
Update to the latest PGF version and try again.

**Comment by Wrzlprmft** [comment]
> Update to the latest PGF version and try again.

This indeed worked (after #708 was fixed). I was under the illusion to have the latest TeXLive.

> Can you please construct an actual minimal example? I'm not going to debug 2600 lines of code.

Note that the cited example was honestly as minimal as I could get with a reasonable effort. Given the nature of the error, I was expecting something like an overflow or similar, which could hopefully have been assessed without actually reading all the code.
