### ISSUE TITLE
inclusion of scaled graphics in a tikzpicture with xelatex broken in the newest pgf

### ISSUE THREAD

**Issue by u-fischer** [pgf-tikz/pgf#708]
pgf displaces scaled graphics when compiling with xelatex. See also
https://tex.stackexchange.com/questions/499784/included-graphics-in-tikz-with-xelatex-get-displaced

~~~~
\documentclass{article}
\usepackage{graphicx}
\usepackage{tikz}
\begin{document}
\newsavebox\mybox
\sbox\mybox{\includegraphics[scale=0.5]{example-image.pdf}}
\fbox{\usebox\mybox}

\begin{tikzpicture}
 \node{\fbox{\usebox\mybox}};
\end{tikzpicture}
\end{document}
~~~~

## output with previous pgf version:

![image](https://user-images.githubusercontent.com/4047173/61175449-1106db80-a5b0-11e9-97a8-2e0e77ddbf6f.png)

## output with current pgf version (Version:  3.1.4 2019-07-12)

![xelatex](https://user-images.githubusercontent.com/4047173/61175452-211ebb00-a5b0-11e9-8c28-132b9e34e1e8.JPG)

**Comment by hmenke** [comment]
Probably due to this one: https://github.com/pgf-tikz/pgf/commit/d0f66607f379dadd6d5a435fa86567fe36cfb842

**Comment by hmenke** [comment]
I reverted the broken commit and tagged a new release which will go live once the CTAN server stops timing out on my upload.

**Comment by hmenke** [comment]
The hotfix should trickle through in the next 24h.
