### ISSUE TITLE
[parser] Error when parameter character is parsed

### ISSUE THREAD

**Issue by Skillmon** [pgf-tikz/pgf#715]
In the `parser` module, parsing a character with category code 6 will throw an error `Illegal parameter number in definition of \pgfparserletter.`

Example code:

```latex
\documentclass[]{article}

\usepackage{pgf}
\usepgfmodule{parser}
\pgfparserdef{error}{initial}|{\pgfparserswitch{final}}
\pgfparserdef{error}{initial}{\meaning##}{category 6 read}
\pgfparserset{status=true}

\begin{document}
\pgfparserparse{error}#|
\end{document}
```

**Comment by Skillmon** [comment]
I already know how to fix this, but first wanted to ask whether fixing it only for `#` with category 6 is ok, or should I implement a more robust but slower code that should work for any character of category 6?

**Comment by hmenke** [comment]
Since you are probably the only user of the `parser` module at all, you can fix it at your discretion.
