### ISSUE TITLE
[manual] \usepgflibrary vs. \usetikzlibrary

### ISSUE THREAD

**Issue by Mo-Gul** [pgf-tikz/pgf#718]
I think a lot of libraries are documented wrong see attached MWE.

    \documentclass[border=5pt]{standalone}
    \usepackage{tikz}
        % documented as `\usepgflibrary`
        % but only work as `\usetikzlibrary`
        % (the libraries
        %  - shadows
        %  - turtle
        %  were already adapted while working on issue #640
        %  <https://github.com/pgf-tikz/pgf/issues/640>
        %  also see pull request #711
        %  <https://github.com/pgf-tikz/pgf/pull/711>)
        \usetikzlibrary{
            babel,
            circuits.logic.IEC,
            circuits.logic.US,
            circuits.logic.CDH,
        }
    \begin{document}
    \end{document}

**Comment by hmenke** [comment]
Good find :+1: If you didn't already, please add these fixes to your open PR.

**Comment by hmenke** [comment]
Please only close issues once the fix is merged.
