### ISSUE TITLE
"sub-library" should load "main library" by default

### ISSUE THREAD

**Issue by Mo-Gul** [pgf-tikz/pgf#720]
Loading the `graphs.standard` library without loading the `graphs` library as well leads to an error message. Wouldn't it be an improvement if the `graphs.standard` library would load the `graph` library itself (by default)?

    \documentclass{standalone}
    \usepackage{tikz}
        \usetikzlibrary{graphs.standard}
    \begin{document}
    \end{document}

Something similar holds for the `graphdrawing` library which also only makes sense when the `graph` library is loaded. In contrast to the previous MWE loading the `graphdrawing` only works fine, i.e. without raising an error.

    \documentclass{standalone}
    \usepackage{tikz}
        \usetikzlibrary{graphdrawing}
    \begin{document}
    \end{document}

**Comment by hmenke** [comment]
Excellent idea. I think the `decorations.<whatever>` libraries already do this and always load the `decorations` library, so it would just be consistent to have that for all others as well.

**Comment by Mo-Gul** [comment]
You are right regarding the `decorations` libraries. Shall I include this already in the current Pull Request or wait?

**Comment by Mo-Gul** [comment]
I added loading `graphs` in the `graphs.standard` library in my [last commit](https://github.com/Mo-Gul/pgf/commit/3d5a3d89f71e764c3979eff51f466c94750b4c25) to Pull Request #711. 

Up to now I decided not to load the `graphs` library when `graphdrawing` is loaded because of the text I just read here:

https://github.com/pgf-tikz/pgf/blob/f5d0ffd6e4a553d40855370c692fea6e33a0026d/doc/generic/pgf/text-en/pgfmanual-en-gd-usage-tikz.tex#L75-L80

I also could find some examples in the manual. One of them is

https://github.com/pgf-tikz/pgf/blob/f5d0ffd6e4a553d40855370c692fea6e33a0026d/doc/generic/pgf/text-en/pgfmanual-en-gd-overview.tex#L104-L120

I adapted the `codeexample`s accordingly in the above mentioned commit as well.
