### ISSUE TITLE
.cvsignore --> .gitignore

### ISSUE THREAD

**Issue by Mo-Gul** [pgf-tikz/pgf#721]
Since the repository was converted from CVS to GIT the IgnoreLists should be adapted as well. They are found here

- [ ]  doc/generic/pgf/version-for-dvipdfm/en/.cvsignore
- [ ]  doc/generic/pgf/version-for-dvips/en/.cvsignore
- [ ]  doc/generic/pgf/version-for-luatex/en/.cvsignore
- [ ]  doc/generic/pgf/version-for-luatex/en/plots/.cvsignore
- [ ]  doc/generic/pgf/version-for-pdftex/en/.cvsignore
- [ ]  doc/generic/pgf/version-for-pdftex/en/plots/.cvsignore 
- [ ]  doc/generic/pgf/version-for-tex4ht/en/.cvsignore
- [ ]  doc/generic/pgf/version-for-vtex/en/.cvsignore
- [ ]  source/generic/pgf/testsuite/mathtest/.cvsignore

(Maybe, instead of having multiple IgnoreLists they can be merged to only one?)

**Comment by hmenke** [comment]
Yes, there should only be a single top-level `.gitignore`.

**Comment by Mo-Gul** [comment]
It would be nice if you, @hmenke, could take care of this, at least give it a start, because I don't really know how to start. If I have a working example, then I can add more stuff if something is left.
