### ISSUE TITLE
bug in axis label position | following  pgf 3.1.3 -> 3.1.4a update |  .tex -> .dvi issue

### ISSUE THREAD

**Issue by ecooch** [pgf-tikz/pgf#722]
[I posted this originally on StackExchange: for more complete details and comments, which I think helpful, see [https://tex.stackexchange.com/questions/501617/possible-major-bug-with-pgfplot-axis-labeling](url)  As you'll see from the comments, this bug has been confirmed by a fair number of people.]

I tried compiling a bunch of files today, all of which use tikzpictures and pgfplots. Something truly odd is happening with how the y-axis label is being positioned, follwoing the update from pgf 3.1.3 -> 3.1.4a. 

I took the MWE from https://tex.stackexchange.com/questions/142120/positioning-of-pgfplot-axis-labels (copied below) as a starting point -- expecting the figure to be rendered looking just like the linked SE  (attached here as good.png)

![good](https://user-images.githubusercontent.com/4500611/61982685-8e2c4a80-afcb-11e9-91bf-2db6de35b718.png)

However, when I compile the MWE using latest and greatest MikTeX (crucially, by using the .tex -> .dvi -> .ps -> .pdf compilation sequence), and tikz and pgfplot packages, this is what I'm now getting -- notice that the y-axis label is waaay off to the left, and not centered wrt to the y-axis. At all...attached as bug.png

![bug](https://user-images.githubusercontent.com/4500611/61982694-94222b80-afcb-11e9-9f09-80579b8365ec.png)

Some key points:

1\ if I roll back to p[gf 3.1.3, bug disappears. Plots perfect

2\ if I use pgf 3.1.4a, bug only seems to appear if you comp[ile using ..tex -> .dvi -> ps -> .pdf (in fact, right at the first step: .tex -> .dvi. Using yap., the .dvi shows the bug). If you compile using 3.1.4a, anf pdfLaTeX, LuaLaTeX or XeLaTeX, no bug. So, the issue seems limited to .tex -> .dvi. 

But, that is a *huge* problem for all of us with loads of .eps images we're including, since we invariably compile .tex -> dvi -> ps -> PDF

Here is the MWE code:

     \documentclass[12pt,letterpaper,oneside]{article}

     \usepackage{tikz}
        \usetikzlibrary{decorations,shapes,arrows,positioning}
     \usepackage{pgfplots}

     \begin{document}

     \begin{tikzpicture}
     \begin{axis}[
        axis lines=middle,
       axis line style={->},
        x label style={at={(axis description cs:0.5,-0.1)},anchor=north},
        y label style={at={(axis description 
        cs:-0.1,.5)},rotate=90,anchor=south},
        xlabel={$u$ unemployment},
        ylabel={$\pi$ inflation}]
        \addplot[black,samples=100,domain=0:1] {120*(1-x)^(1/3)-1};
     \end{axis}
     \end{tikzpicture}

     \end{document}

**Comment by ecooch** [comment]
Similar issue just reported here: https://tex.stackexchange.com/questions/501625/updated-miktex-and-tikz-does-not-rotate-the-y-axis-properly[](url)

**Comment by hmenke** [comment]
You could try restoring the default definition of `\pgfsys@hboxsynced` but then position tracking will break again.  That is what happened in the XeTeX driver as well.
```latex
\makeatletter
\def\pgfsys@hboxsynced#1{%
  \pgfsys@beginscope\pgflowlevelsynccm\pgfsys@hbox#1\pgfsys@endscope%
}%
\makeatother
```

**Comment by ecooch** [comment]
Thanks -- I'll play with restoring trhe default, but as you intimate, not a robust or long-term solution.

**Comment by ecooch** [comment]
Just a question -- out of curiosity, when a clear bug like this is found (which seems fairly significant) -- what generally happens next at the dev end? Its easy enough for me to block any attempts by software to update from 3.1.3 -> 3.1.4a, but for other users who might nor be aweare of the issue...

Again, just curious.

**Comment by hmenke** [comment]
I've reverted the offending commit https://github.com/pgf-tikz/pgf/commit/a65310afad22747f2a7a5728e4caa900c5fe4ec9
It will be deployed soon but of course breaks position tracking again.

**Comment by ecooch** [comment]
For us (mere) mortals, meaning...what? ;-)
