### ISSUE TITLE
style key does not work properly in datavisualization

### ISSUE THREAD

**Issue by schtandard** [pgf-tikz/pgf#726]
The `style` key does not always produce the correct output, as can be seen using examples given in section 82.4.7 "Styling Ticks and Grid Lines: The Style and Node Style Keys" of the manual (MWE below).

- In the example for `/tikz/data visualization/node style` (top of page 884), the difference to `/tikz/data visualization/style` is emphasized:
    > Note that in the example the ticks themselves (the little thicker lines) are not red.

    However, replacing `node style` with `style` yields identical output (the ticks themselves are not red). (This can also be seen in the example for the latter key, here the ticks should be blue.)

- In the example for `/tikz/data visualization/every grid` (top of page 885), the grid lines should be dashed, but aren't.

Other modifications with the same options work (like `thick` for the ticks or colors for the grid lines), so I guess that the problem is some of the default appearance being set after `styling`.

----

```
\documentclass{article}

\usepackage{tikz}
\usetikzlibrary{
  datavisualization,
  datavisualization.formats.functions,
}

\begin{document}

Ticks should be red:

\tikz \datavisualization [
    scientific axes,
    all axes={ticks={style=red}, length=3cm},
    visualize as line,
  ]
  data [format=function] {
    var x : interval [5:10];
    func y = \value x * \value x;
  };

Grid lines should be dashed:

\tikz \datavisualization [
    scientific axes,
    all axes={length=3cm, grid},
    every grid/.append style={style=densely dashed},
    visualize as line,
  ]
  data [format=function] {
    var x : interval [5:10];
    func y = \value x * \value x;
  };

\end{document}
```

**Comment by hmenke** [comment]
Does anyone actually use `datavisualization` instead of `pgfplots`?

**Comment by schtandard** [comment]
Well, this is not a comment I expected. I was going to.

If you don't think I should (or have thoughts on both options), maybe post an answer [here][sequestion]?

[sequestion]: https://tex.stackexchange.com/questions/502905/pgfplots-vs-datavisualization-2019-review

**Comment by hmenke** [comment]
I was half joking, but `pgfplots` is undeniably more feature-rich and offers in my opinion a simpler syntax than `datavisualization`.  Of course I'll take a look at this issue.

**Comment by hmenke** [comment]
The fix to `ticks={style=...}` should not cause any trouble but to fix `every grid/.append style={style=...}` I have to change the order of evaluation and therefore the precedence.  So setting `style` in `every grid` will now override settings for `style` in `every major grid` and `every minor grid`, but that is also documented.
