### ISSUE TITLE
\pgfmathfloatparse is a copy of \pgfmathparse when /pgf/fpu=false

### ISSUE THREAD

**Issue by schtandard** [pgf-tikz/pgf#727]
When the `fpu` library is not "installed", i.e. `\pgfmathparse` and friends have their normal behavior, `\pgfmathfloatparse` is a copy of `\pgfmathparse`, i.e. it does not parse floating point numbers.

```latex
\documentclass{article}

\usepackage{tikz}
\usetikzlibrary{fpu}

\begin{document}

\pgfmathparse{1.234e-56}\pgfmathresult

\pgfmathfloatparse{1.234e-56}\pgfmathresult

\pgfkeys{/pgf/fpu}

\pgfmathparse{1.234e-56}\pgfmathresult

\pgfmathfloatparse{1.234e-56}\pgfmathresult

\end{document}
```
outputs
> 0.0
> 0.0
> 1Y1.234e-56]
> 1Y1.234e-56]

but should output
> 0.0
> 1Y1.234e-56]
> 1Y1.234e-56]
> 1Y1.234e-56]

**Comment by hmenke** [comment]
Well, it *does* parse floating point numbers, it just doesn't output them as FPU floats.  I'm not sure what the correct behaviour should be here, because FPU floats are pretty much useless when the `fpu` is not enabled.

**Comment by schtandard** [comment]
Does it?
```
\pgfmathfloatparse{1.234e-56 * 5.25e57}\pgfmathresult
```
does not work with `fpu` disabled either, so it can't _just_ be the output formatting.

I don't agree that the `fpu` functions are useless separately. They can be used to parse floating point numbers without disturbing the usual drawing functions (when the floating point numbers are not to be used for drawing directly). In the current state, one has to locally activate `fpu` for each calculation.

I thought that this was the whole point of having the `float` versions of all the math macros. If `\pgfmathparse` and `pgfmathfloatparse` do the same thing regardless of if `fpu` is loaded or not, what's the point of having both names?
