### ISSUE TITLE
positioning library: error when using coordinates with numbers

### ISSUE THREAD

**Issue by u-fischer** [pgf-tikz/pgf#728]
The documentation claims (on page 237) that the `of` part of a positioning spec can be a coordinate without parentheses  but with numbers:

> An example would be `of somenode.north` or `of 2,3`.

But `of 2,3`  errors with 

~~~~
 Package pgf Error: No shape named 2 is known.`
~~~~

It works if one adds braces:

~~~~
\documentclass{article}
\usepackage{tikz} 
\usetikzlibrary{positioning}
\begin{document}
\begin{tikzpicture}
\draw[help lines](0,0)grid(5,5);
%\node [above=1mm of  2,3]{x}; %error
\node [above=1mm of {2,3}]{x}; %works
\end{tikzpicture}
\end{document}
~~~~

**Comment by hmenke** [comment]
Ehm, comma is the list separator, so you have to use braces around it.  It's the same for `[]`, which will also not work.  For example:
```
\node[label=[red]center:foo] {};
```
So this is definitely a wont-fix.

**Comment by u-fischer** [comment]
Sorry I didn't meant that this should be fixed, but that the documentation  should be corrected: if explicitly shows the wrong `of 2,3`.

**Comment by hmenke** [comment]
Aha! That should of course be fixed.  Sorry for the misunderstanding.

**Comment by Mo-Gul** [comment]
Maybe it's even worse to add a sentence *why* the curly braces are needed as you did in your [above comment](https://github.com/pgf-tikz/pgf/issues/728#issuecomment-519684158).

So something like:

> For the latter case the curly braces are needed, because the comma is the list separator and thus Ti*k*Z cannot distinguish if you provided a coordinate or another optional argument.
