### ISSUE TITLE
\node foreach does not work with points in list

### ISSUE THREAD

**Issue by siemer** [pgf-tikz/pgf#735]
```latex
\documentclass{article}
\usepackage{tikz}

\begin{document}

\begin{tikzpicture}
    \foreach \thing in {(0,0), (0,1)} \node[green, draw] at \thing {bla};
    \node foreach \thing in {(1, 0), (1, 1)} [red, draw, at=\thing] {foo};
    \node foreach \thing in {(2, 0), (2, 1)} [blue, draw] at \thing {tf};
\end{tikzpicture}

\end{document}
```

The third `foreach` line does not work as I would expect (throws error). The fact that the first two invocations with `foreach` execute fine suggests that the third should do as well.

**Comment by hmenke** [comment]
That is very tricky, because at the point where TikZ parses `at \thing`, its meaning is undefined.  The `foreach` is only executed later.  I would say that `foreach` on a path is in general a bad idea.

Also please don't include packages that the MWE does not depend on, in this case `xltxtra`, which by the way really only loads `fontspec`.

**Comment by hmenke** [comment]
When you look at the code
https://github.com/pgf-tikz/pgf/blob/3ec5292f8bf9453e2baf9654fca94c877a4e89dd/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex#L4347-L4413
you can also see that when TikZ encounters a node foreach, what it does is convert it to regular foreach, but has to first do all the parsing.

**Comment by hmenke** [comment]
This “works” but is *way* too fragile.
```latex
\documentclass{article}
\usepackage{tikz}

\makeatletter

% Look ahead whether the next character is a (.  If that is the case, we scan
% until ), otherwise, we grab a single token and append.
\def\tikz@nodes@at at{\pgfutil@ifnextchar({\tikz@nodes@at@}{\tikz@nodes@at@@}}
\def\tikz@nodes@at@#1){%
  \expandafter\def\expandafter\tikz@nodes@collect\expandafter{\tikz@nodes@collect at#1)}%
  \tikz@nodes@scan}%
\def\tikz@nodes@at@@#1{%
  \expandafter\def\expandafter\tikz@nodes@collect\expandafter{\tikz@nodes@collect at#1}%
  \tikz@nodes@scan}%

\makeatother

\begin{document}

\begin{tikzpicture}
    \foreach \thing in {(0,0), (0,1)} \node[green, draw] at \thing {bla};
    \node foreach \thing in {(1, 0), (1, 1)} [red, draw, at=\thing] {foo};
    \node foreach \thing in {(2, 0), (2, 1)} [blue, draw] at \thing {tf};
\end{tikzpicture}

\end{document}
```

**Comment by siemer** [comment]
Thanks for the quick answer. For the time being I use the `at=\thing` workaround.
