### ISSUE TITLE
\path options do not propagate to nodes

### ISSUE THREAD

**Issue by hmenke** [pgf-tikz/pgf#738]
Options which are only specified on a path do not propagate to nodes on that path.  The following MWE only produces a blank page.  I'm not sure right now, whether options should be propagated or not.
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}[dot/.style={draw,fill,circle,inner sep=2pt}]
  \path[dot] node {};
\end{tikzpicture}
\end{document}
```

**Comment by Rmano** [comment]
I am not sure if they should propagate or not, but it would be a big change to the current  behavior: 

```
\documentclass[border=10pt]{standalone}
\usepackage{tikz}
\usetikzlibrary{arrows.meta,positioning,calc}
\begin{document}
\begin{tikzpicture}
    \path[red, fill] (0,0) node{\color{blue}test}
        -- ++(1,1) -- ++(1,0) -- cycle;
    \path[red, fill] (2,0) node[fill]{\color{blue}test}
        -- ++(1,1) -- ++(1,0) -- cycle;
\end{tikzpicture}
\end{document}
```
![image](https://user-images.githubusercontent.com/6414907/64429139-a48ef100-d0b5-11e9-8650-3a7e976b6b3b.png)

so I think it is better not to change it unless you add a specific key (like `propagate to nodes`) or similar.

**Comment by hmenke** [comment]
Good point.
