### ISSUE TITLE
should `\tikz@text@width` be reset inside a node?

### ISSUE THREAD

**Issue by u-fischer** [pgf-tikz/pgf#743]
When the `text width` key is used the value is stored in `\tikz@text@width`. This confuses tikz commands inside the node. An example is chemfig which uses tikz for the arrows:

~~~~
\documentclass{article}
\usepackage{chemfig}
\usepackage{tikz}

\begin{document}
\makeatletter
\begin{tikzpicture}
\node[text width=6cm]{
%\let\tikz@text@width\pgfutil@empty
\tikz[->]{\node(a){A};\draw(a)--(1,0);}
};
\end{tikzpicture}

\begin{tikzpicture}
\node[text width=6cm]{
\let\tikz@text@width\pgfutil@empty
\tikz[->]{\node(a){A};\draw(a)--(1,0);}
};
\end{tikzpicture}

\begin{tikzpicture}
\node[text width=6cm]{\chemfig{C-C}};
\end{tikzpicture}

\begin{tikzpicture}
\node[text width=6cm]{%
\let\tikz@text@width\pgfutil@empty
\chemfig{C-C}};
\end{tikzpicture}

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/64803473-233fce80-d58d-11e9-8793-4ab6d7328017.png)

**Comment by hmenke** [comment]
TikZ pictures can't be nested.  Sometimes it works but that is a pure coincidence.

**Comment by hmenke** [comment]
What about the zillions of other parameters that aren't reset?
