### ISSUE TITLE
TikZ trims spaces from named points only sometimes

### ISSUE THREAD

**Issue by PhelypeOleinik** [pgf-tikz/pgf#747]
From this TeX.SX thread: https://tex.stackexchange.com/q/508391/134574
Ti*k*Z trims spaces around node names, but only sometimes. Apparently when the node name is followed by a `)` the space is not removed:
```tex
\input tikz
\tikz{
  \coordinate (A) at (0,0);
  \coordinate (B) at (1,1);
  \draw ( A ) -- (B);
  %        ^ No shape named 'A ' is known;
  \draw ( A -| B ) -- (B-|A);
  %             ^ No shape named 'B ' is known;
}
\bye
```
But leading spaces apparently are always removed.

I would say Ti*k*Z should _always_ trim the spaces around the node name.

One could argue that this can break existing code which relies on this feature, but relying on trailing spaces is weird, I think :-)

If not, then perhaps the error message could be changed to add quotes around the node name so that the trailing space is more easily seen (suggested here: https://tex.stackexchange.com/q/389388/134574).

**Comment by hmenke** [comment]
> One could argue that this can break existing code which relies on this feature, but relying on trailing spaces is weird, I think :-)

That is the reason why I will probably not fix this in the core.  I'm already breaking too much stuff.  However, I could provide a fix as a library.

**Comment by hmenke** [comment]
I've implemented the suggestions with the quotes but I will not change the core behaviour.  I'm thus marking it as fixed.
