### ISSUE TITLE
Plot option `smooth` and decorations.markings

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#748]
There is an interesting interplay between the plot option `smooth` and `decorations.marking` (but most likely not only for `markings` decorations). Consider the MWE

```latex
\documentclass[tikz,border=3.14mm]{standalone}
\usetikzlibrary{calc,decorations.markings}
\begin{document}
\begin{tikzpicture}[scale=2,pics/coordsys/.style = {
    code = {
        \draw [->,pic actions] (0,0) -- +(1,0)[red] node[pos=1.1]
		{$x$};
        \draw [->,pic actions] (0,0) -- +(0,1)[blue] node[pos=1.1,
		%rotate=00,
		%transform shape,
		%transform shape=false
		]
		{$y$};
    }},rotated coordsys at/.style={postaction={decorate,decoration={markings,
mark=at position #1 with {
\path (0,0) coordinate (O') (1,0) coordinate (X');
\path let \p1=($(X)-(O)$),\p2=($(X')-(O')$) in \pgfextra{%
\pgfmathsetmacro{\myangle}{atan2(\y1,\x1)-atan2(\y2,\x2)}
\xdef\myangle{\myangle}};
\pgftransformresetnontranslations
 \path (O') pic[solid,rotate=-\myangle]{coordsys};
}}}}]
 \path (0,0) coordinate (O) (1,0) coordinate (X);
 \draw[rotated coordsys at/.list={0.1,0.3,0.5,0.7,0.9}] 
	plot[variable=\x,domain=-2:2] (\x,{sin(\x*45)});
 \draw[rotated coordsys at/.list={0.1,0.3,0.5,0.7,0.9}] 
  plot[variable=\x,domain=-2:2,samples=25,smooth] (\x+5,{sin(\x*45)});
\end{tikzpicture}
\end{document}
```
![image](https://user-images.githubusercontent.com/35985244/64933848-f80ee680-d7fb-11e9-86f1-2ae704d6f7cc.png)

As one can see, on the left side, where a nonsmooth plot is employed, the `y` is upright. On the other hand, on the right side where the plot has the `smooth` key, it is not. The difference in behavior is already surprising to me. However, what is worse, I am unable to cure it (other than explicitly computing the rotation angle that rotates it back to upright). I played with the usual suspects like `tansform shape`, `rotate`, `\pgftransformresetnontranslations` in all combinations I could think of but could not fix it. 

P.S. It does not seem to be related to the usage of a `pic`.

```latex
\documentclass[tikz,border=3.14mm]{standalone}
\usetikzlibrary{calc,decorations.markings}
\begin{document}
\begin{tikzpicture}[scale=2,rotated coordsys at/.style={postaction={decorate,decoration={markings,
mark=at position #1 with {
\path (0,0) coordinate (O') (1,0) coordinate (X');
\path let \p1=($(X)-(O)$),\p2=($(X')-(O')$) in \pgfextra{%
\pgfmathsetmacro{\myangle}{atan2(\y1,\x1)-atan2(\y2,\x2)}
\xdef\myangle{\myangle}};
%\pgftransformresetnontranslations
 \draw [->] (O') -- +(1,0)[red] node[pos=1.1]
		{$x$};
 \draw [->] (O') -- +(0,1)[blue] node[pos=1.1,
		%rotate=00,
		%transform shape,
		%transform shape=false
		]
		{$y$};
}}}}]
 \path (0,0) coordinate (O) (1,0) coordinate (X);
 \draw[rotated coordsys at/.list={0.1,0.3,0.5,0.7,0.9}] 
	plot[variable=\x,domain=-2:2] (\x,{sin(\x*45)});
 \draw[rotated coordsys at/.list={0.1,0.3,0.5,0.7,0.9}] 
  plot[variable=\x,domain=-2:2,samples=25,smooth] (\x+5,{sin(\x*45)});
 \draw[rotated coordsys at/.list={0.1,0.3,0.5,0.7,0.9}]  (-2,-1) to[bend right] 
  (2,-1);
\end{tikzpicture}
\end{document}
```
has the same issue.

**Comment by hmenke** [comment]
I don't remember touching any decorations or plot code, so if this is a regression it must be really old.

**Comment by ghost** [comment]
@hmenke  OK, I remove the parentheses.

**Comment by hmenke** [comment]
This is the plot handler that is used when the `smooth` option is active:
https://github.com/pgf-tikz/pgf/blob/ee17ca51395308d7df7d8fe6f805c20ec69f8017/tex/generic/pgf/libraries/pgflibraryplothandlers.code.tex#L13-L88

**Comment by ghost** [comment]
@hmenke  I do not think it is the plot handler but Bezier vs. straight lines. 
```latex
 \draw[rotated coordsys at/.list={0.1,0.3,0.5,0.7,0.9}]  (-2,-1) to[bend right] 
  (2,-1);
```
has the same issue.

**Comment by hmenke** [comment]
Which is kind of the same statement, because the plot handler looks pretty innocent, so it probably comes from `\pgfpathcurveto`.  Do you have an old version at hand with which you could test whether this is a regression?

**Comment by ghost** [comment]
@hmenke  I agree that it is the same thing. All I wanted to say is that it is not the plot handler but the way Ti*k*Z switches to the tangent system.  And I do not have an old version at hand at the moment.

**Comment by hmenke** [comment]
I quickly tested with TeX Live 2015 and 2016 and they both exhibit the same broken behaviour as the latest master.

**Comment by ghost** [comment]
@hmenke  OK, thanks! (I did not see this issue in the various tangent solutions on the TeX-SE site.)

**Comment by hmenke** [comment]
I just realized that you are using a `pic`.  There are some known issues with `pic`, so that might be the source of the problem.

**Comment by ghost** [comment]
@hmenke  Does not seem like it. If you replace the pic by its code , the same issue arises.

**Comment by Mo-Gul** [comment]
Regarding "old versions": You can find all -- or at least most of them -- on https://sourceforge.net/projects/pgf/files/pgf/.

**Comment by hmenke** [comment]
Here is your fix.
```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{decorations.markings}
\begin{document}
\begin{tikzpicture}[
    rotated coordsys at/.style={
        postaction={
            decorate,
            decoration={
                markings,
                mark=at position #1 with {
                    \pgfslopedattimefalse % <---
                    \draw (0,0) -- (1,0) node[pos=1.1] {$x$};
                    \draw (0,0) -- (0,1) node[pos=1.1] {$y$};
                }
            }
        }
    }]
    \draw[rotated coordsys at/.list={0.1,0.3,0.5,0.7,0.9}]  (-2,-1) .. controls (0,-2) .. (2,-1);
\end{tikzpicture}
\end{document}
```

**Comment by hmenke** [comment]
Possible patch, please test.
```diff
diff --git a/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.markings.code.tex b/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.markings.code.tex
index 9d18797d..23b7ff67 100644
--- a/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.markings.code.tex
+++ b/tex/generic/pgf/libraries/decorations/pgflibrarydecorations.markings.code.tex
@@ -89,6 +89,7 @@
     \pgfinterruptpath%
       \pgfscope%
         \let\pgf@lib@dec@mark@marks=\pgfutil@empty%
+        \pgfslopedattimefalse
         \pgf@lib@dec@computed@action%
       \endpgfscope%
     \endpgfinterruptpath%
```
