### ISSUE TITLE
Table of Contents has wrong page numbers

### ISSUE THREAD

**Issue by 3geek14** [pgf-tikz/pgf#749]
I found the documentation from [CTAN's page](https://ctan.org/pkg/pgf?lang=en) to look up the decorations library. In the table of contents on page 10, it says Chapter 24, Decorated Paths, starts on page 339. In actuality, it starts on page 361.  Many other page numbers are off, but this was the first one I noticed.

**Comment by hmenke** [comment]
At least the hyperlink resolves to the correct page, so I think this is a minor problem.  I hope you are not printing out the manual.

**Comment by Ndolam** [comment]
I don't know about 3geek14, but although I don't print the manual, there are times when I do want the page numbers to match up.  Does this look like a hard problem to solve?

**Comment by hmenke** [comment]
Not a hard problem at all, however, I'm planning to solve this issue by rolling out a new build system altogether, which will take some more time.

**Comment by Ndolam** [comment]
OK, thanks very much.

**Comment by ghost** [comment]
I confirm. And I did print out the manual (with wrong page numbers :()

**Comment by hmenke** [comment]
I have rolled out the new build system.  Can you please check that page numbers are resolved correctly? https://pgf-tikz.github.io/pgf/pgfmanual.pdf

**Comment by 3geek14** [comment]
I'm not going to pretend that I checked every page number, but I checked a couple, and they were all correct.  Thanks!
