### ISSUE TITLE
Beginning space in argument of \pgfdeclarepattern raises error: do not know the key

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#753]
When I try to compile the example provided in tikz manual, sec. 62.3 _User-Defined Patterns_, I found that a beginning space in argument of `\pgfdeclarepattern` will raise an error:
```
! Package pgfkeys Error: I do not know the key '/pgf/patterns/ name',
```
The tex file has something like `\pgfdeclarepattern{ name=...}`, in which there is an un-trimmed space before the key `name`. This is the origin of problem.

<details>
  <summary>Full example</summary>
  
```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{patterns.meta}

\begin{document}

\pgfdeclarepattern{ %  <<< this space causes the problem <<<
  name=hatch,
  parameters={\hatchsize,\hatchangle,\hatchlinewidth},
  bottom left={\pgfpoint{-.1pt}{-.1pt}},
  top right={\pgfpoint{\hatchsize+.1pt}{\hatchsize+.1pt}},
  tile size={\pgfpoint{\hatchsize}{\hatchsize}},
  tile transformation={\pgftransformrotate{\hatchangle}},
  code={
    \pgfsetlinewidth{\hatchlinewidth}
    \pgfpathmoveto{\pgfpoint{-.1pt}{-.1pt}}
    \pgfpathlineto{\pgfpoint{\hatchsize+.1pt}{\hatchsize+.1pt}}
    \pgfpathmoveto{\pgfpoint{-.1pt}{\hatchsize+.1pt}}
    \pgfpathlineto{\pgfpoint{\hatchsize+.1pt}{-.1pt}}
    \pgfusepath{stroke}
  }
}

\tikzset{
  hatch size/.store in=\hatchsize,
  hatch angle/.store in=\hatchangle,
  hatch line width/.store in=\hatchlinewidth,
  hatch size=5pt,
  hatch angle=0pt,
  hatch line width=.5pt,
}

\begin{tikzpicture}
  \draw [pattern=hatch] (0, 0) rectangle ++(2,2);
\end{tikzpicture}

\end{document}
```
</details>

I found trimming spaces from the left side of `\pgf@pat@options` solves the problem. For example, use
```latex
\usepackage{etoolbox}
\usepackage{trimspaces}

\makeatletter
\patchcmd{\pgfdeclarepattern}
  {\def\pgf@pat@options{#1}}
  {\def\pgf@pat@options{#1}\trim@pre@space@in\pgf@pat@options}
  {}{\fail}
\makeatother
```

I have tikz v3.1.4b installed. There may be some inner utility macro of pgf which does the similar thing as `\trim@pre@space@in` from `trimspaces` package. But I am not familiar with pgf.

**Comment by Mo-Gul** [comment]
Interestingly `\tikzdeclarepattern` doesn't raise that error. But I found two more as can be seen in the code given in https://github.com/pgf-tikz/pgf/issues/602#issuecomment-527564693 at the first `\draw` command in the document.

**Comment by muzimuzhi** [comment]
By using `\tikzdeclarepattern`, the beginning space in arg never happens.
```tex
\def\tikzdeclarepattern#1{%
  ...
  \pgfdeclarepattern{/tikz/patterns/.cd,#1}%
}
```

Related lines of source codes
https://github.com/pgf-tikz/pgf/blob/b26565670b822c292e706cf5c9d426a7099be6bd/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarypatterns.meta.code.tex#L63-L81
https://github.com/pgf-tikz/pgf/blob/b26565670b822c292e706cf5c9d426a7099be6bd/tex/generic/pgf/libraries/pgflibrarypatterns.meta.code.tex#L85-L107

**Comment by muzimuzhi** [comment]
Thanks.
