### ISSUE TITLE
Typo in the minimal introduction to Tikz (minimaltikz.pdf)

### ISSUE THREAD

**Issue by AlexDikelsky** [pgf-tikz/pgf#754]
On page 11 of minimaltikz.pdf, it says "which is equal to 3:141592654". The colon there should be a period.

**Comment by joulev** [comment]
I believe this is not where you should report this. `minimaltikz.pdf` is not maintained by the PGF team.

The latest version is officially [here](https://cremeronline.com/LaTeX/minimaltikz.pdf), which also includes the typo. The author said in Section 1:

> There are certainly mistakes left in this document. Be careful and if you find a mistake, drop me an e-mail!

Therefore, I think you should send an email to [jacques.cremer@tse-fr.eu](mailto:jacques.cremer@tse-fr.eu).

**Comment by AlexDikelsky** [comment]
Thanks! I just sent him an email.
