### ISSUE TITLE
Manual leaves out \usegdlibrary

### ISSUE THREAD

**Issue by Volker-Weissmann** [pgf-tikz/pgf#755]
In the [manual](http://pgf.sourceforge.net/pgf_CVS.pdf), in section 19.2.2 at the bottom of page 265 we can find the line
`For instance, adding tree layout to the above code results in the
following somewhat more pleasing rendering`
. If you have a "\usegdlibrary{trees}" somewhere in your code it works fine, but without it compilation fails with the message:
> ! Package pgfkeys Error: I do not know the key '/tikz/graphs/binary tree layout
> ' and I am going to ignore it. Perhaps you misspelled it. ...

I don't have a Problem with the fact that you need this command, but the documentation does not say that you need this command in this chapter (only 200 pages later) and the error message does not indicate it. It would be nice if you could add a note to the documentation or to the error message

**Comment by hmenke** [comment]
This has been fixed some time ago.

**Comment by Volker-Weissmann** [comment]
Ich wusste gar nicht, dass du hier Maintainer bist Henri Menke. Dann besteht ja noch Hoffnung für das Projekt.  :-)
