### ISSUE TITLE
\draw circle[radius=rand]; gives ellipses

### ISSUE THREAD

**Issue by TorbjornT** [pgf-tikz/pgf#756]
This was reported in https://tex.stackexchange.com/questions/389920/tikz-drawviolet-0-0-circle-rand2-is-an-oval#comment1296666_512741, and as requested by Henri I'm making a bug report.

My guess was that because `radius` sets `x radius` and `y radius` separately, they get different random numbers, and hence you get an ellipse with `\draw circle[radius=rand];`.

```
\documentclass[tikz]{standalone}    
\begin{document}
\begin{tikzpicture}
\draw[help lines,step=0.5] (-1,-1) grid (1,1);
\foreach \x in {0,...,10}
   \draw[violet] circle[radius=rand];

\node [fill=white,above right] at (-1,-1) {\tiny\pgfversion};
\end{tikzpicture}
\end{document}
```

![image](https://user-images.githubusercontent.com/3189311/67113337-86023680-f1d9-11e9-9c47-ac7536d5d17a.png)

**Comment by hmenke** [comment]
This is actually a combination of two race conditions.  I've fixed it on my own branch but I'll wait for the CI before merging.
