### ISSUE TITLE
[fpu] Drawing a rectangle with rounded corners with fpu enabled throws an error.

### ISSUE THREAD

**Issue by exelian** [pgf-tikz/pgf#766]
I have an issue with the latest versions of pgf/tikz and fpu working working correctly. This problem occurs on multiple platforms (Windows 10, Freebsd 12.0) using MikTex and TexLive 2019 respectively.

I reduced the testcase to the following code:
```
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{fpu}

\begin{document}
\begin{tikzpicture}
\pgfkeys{/pgf/fpu=true}
\draw[rounded corners](0, 0) rectangle (1cm, 1cm);
\end{tikzpicture}
\end{document}
```

By adding or removing the `\pgfkeys{/pgf/fpu=true}` you can make the test work or fail.

[output.log](https://github.com/pgf-tikz/pgf/files/3797923/output.log)

**Comment by hmenke** [comment]
Probably a duplicate of https://github.com/pgf-tikz/pgf/issues/678.  Keep in mind that drawing with FPU enabled is *not supported*.  The FPU is only made for plotting functions.

**Comment by exelian** [comment]
You're right, I missed the other ticket. I'll close this one.
