### ISSUE TITLE
Something is wrong with the manual version on pgf-tikz.github.io

### ISSUE THREAD

**Issue by joulev** [pgf-tikz/pgf#768]
On page 34

![image](https://user-images.githubusercontent.com/44609036/68080332-dc06e900-fe2b-11e9-908b-a1ff9e583d70.png)

This problem is in both https://pgf-tikz.github.io/pgf/pgfmanual.pdf and https://pgf-tikz.github.io/pgfmanual-0034.svg (current version, as of 4:22 AM 3 November 2019 UTC time).

And this is not the only example.

Apparently there are some problems with the way length units are processed by the compiler.

**Comment by hmenke** [comment]
Probably due to this: https://github.com/pgf-tikz/pgf/commit/1302de8a99834bb0e30ffc214a7350952c446ab6

**Comment by hmenke** [comment]
[![fixed](https://user-images.githubusercontent.com/1903556/68092576-8563e280-fef1-11e9-8c49-18553c1f3325.png)](https://pgf-tikz.github.io/pgfmanual-0032.svg)
