### ISSUE TITLE
pgf/doc/generic/pgf/text-en/pgfmanual-en-installation.tex: Using the ConTeXt format claims that 'ConTeXt restricts the length of module names to 6 characters'. Is this still true?

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#769]
ConTeXt Garden has the following disclaimer:

https://www.contextgarden.net/Modules

Legacy modules disclaimer
Prior to release 2005.05.25, ConTeXt silently truncated all file names in \usemodule commands to 8 characters long and lowercased them to "prevent cross platform problems with filenames". Thus, module files that are to be used with older versions of ConTeXt must have filenames that fit those restrictions, or they will (somewhat cryptically) not be found.

Is this still relevant? I mean, is has been almost years since that version of ConTeXt was released.

**Comment by hmenke** [comment]
I don't know whether it still applies.  I don't even know whether PGF still works with ConTeXt MkII (it definitely works with MkIV).  All the installation instructions and package version requirements in the manual are horribly outdated anyway.  I think all this stuff should be removed.  The only reliable way to figure out whether PGF works with your system is by trying it out.
