### ISSUE TITLE
Label anchors get set "too early"

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#774]
Setting label anchors with `every label/.style` has no effect since the anchor gets overwritten. One way to resolve this is to add "late options" for labels, something like
```

\def\tikz@@parse@label@nonactive[#1]#2:#3:\pgf@nil{%
  \tikzset{%
    append after command = {%
      \bgroup
        [current point is local=true]
        \pgfextra{\let\tikz@save@last@fig@name=\tikz@last@fig@name\tikz@node@is@a@labelfalse}
        node [every label,
              tikz@label@angle = #2,
              anchor=@auto,
              every label add,%<- added
              #1,
              tikz@label@post = \tikz@label@distance] {\iftikz@handle@active@nodes\expandafter\scantokens\else\expandafter\pgfutil@firstofone\fi{#3\noexpand}}
        \pgfextra{\global\let\tikz@last@fig@name=\tikz@save@last@fig@name}
      \egroup}}}%
\tikzset{every label add/.style={}}
```

and something analogous for the active case. Then the user could set the anchors labels with `every label add/.style={anchor=...}`. This has been discussed in https://tex.stackexchange.com/a/515662/194703.  (Moving `every label` to a later position will also work, but possibly break some existing codes.)

**Comment by ghost** [comment]
@hmenke  Before you get mad at me: I also see that there is this post: https://github.com/pgf-tikz/pgf/issues/773 submitted a few seconds before this. However, I feel that the other post is not fully to the point, yet the issue is the same.

**Comment by hmenke** [comment]
Related? #643

**Comment by ghost** [comment]
@hmenke  Yes, it is. It is the same problem for pins. The above proposal would also work there. Of course, there could be pit falls. But adding a separate key for the late options, combined with a warning that this  may change the expected behavior, may be sufficiently clean.

**Comment by hmenke** [comment]
Actually I can't really see a reason why we can't simply reorder
```
every label,
tikz@label@angle = #2,
anchor=@auto,
```
to
```
tikz@label@angle = #2,
anchor=@auto,
every label,
```
You say that it will break existing documents.  Can you give a convincing example for that?

**Comment by hmenke** [comment]
In fact, I believe the correct order would be
```
tikz@label@post = \tikz@label@distance
tikz@label@angle = #2,
anchor=@auto,
every label,
#1,
```
i.e. private keys (those with `@`) first, then defaults for public keys, then `every <whatever>`, and last keys passed by argument.

EDIT: `tikz@label@post` actually executes code based on the previously set parameters, so the order has to be
```
tikz@label@angle = #2,
anchor=@auto,
every label,
#1,
tikz@label@post = \tikz@label@distance
```

**Comment by ghost** [comment]
@hmenke  I fully agree that this is the appropriate order. What I meant by something may break is that obviously so far setting an anchor with `every label` has had no effect. So if this is going to be changed, existing document in which the users have added the anchor that way may now yield different results. Maybe I am just overly cautious.

**Comment by hmenke** [comment]
Okay, but I am not aiming to be as compatible as LaTeX2e such that relying on buggy behaviour is supported.

**Comment by ghost** [comment]
@hmenke  OK, sounds good! Maybe one should still mention in the manual that this has changed.
