### ISSUE TITLE
[patterns.meta] add `shift` to `(new) lines` example

### ISSUE THREAD

**Issue by Mo-Gul** [pgf-tikz/pgf#775]
Please add a `shift` key to the `(new) lines` pattern as requested in https://github.com/pgf-tikz/pgf/issues/602#issuecomment-527564693 item 4.

**Comment by hmenke** [comment]
Hm.  Currently `patterns.meta` is a PGF library for maximum flexibility.  I don't want to restrict it to only work with TikZ, but to parse `Lines[shift={(1,2)}]` I need to invoke `\tikz@scan@one@point`.  I'll have a look whether I can extend patterns from TikZ.

**Comment by Mo-Gul** [comment]
If it helps:  
It does not necessarily have to be the classical `shift` that is needed here. Optimally it would be a key --  e.g. `offset` -- that accepts values between `0` and `1` which will be a multiplier of `/pgf/pattern keys/size` (and of course respects/accounts for `/pgf/pattern keys/angle`).

**Comment by ghost** [comment]
Sorry to interfere, but it seems that the examples under [this comment](https://github.com/pgf-tikz/pgf/issues/602#issuecomment-527564693)  use `\tikzdeclarepattern`. This suggests that it requires Ti*k*Z to work. So `shift={(x,y)}` should be OK. Am I missing something?

**Comment by hmenke** [comment]
Yes, you are missing the fact that I implemented them with `\pgfdeclarepattern` now: https://github.com/pgf-tikz/pgf/commit/6fa03ff6b31e47e2d820eda206775ea55f0dec85

**Comment by hmenke** [comment]
All the new patterns now have a `xshift` and `yshift` key.  These two dimension are just passed to `\pgftransformshift`.  The shift is applied before rotation.
https://github.com/pgf-tikz/pgf/blob/b2bbefdafe79bbff8f5e9eab9877a980db36eaef/doc/generic/pgf/text-en/pgfmanual-en-library-patterns.tex#L242-L250
