### ISSUE TITLE
[patterns.meta] implement "most used patterns"

### ISSUE THREAD

**Issue by Mo-Gul** [pgf-tikz/pgf#776]
This is a copy of https://github.com/pgf-tikz/pgf/issues/602#issuecomment-527573213.

---

What do you think about providing either an additional sub-libraries with some general implementation of the "most used patterns" or providing them directly with `patterns.meta`. I think that the "most used patterns" will be the ones that are already given in the `pattern` library. So that would be something like

- `horizontal lines`, `vertical lines`, `north east lines`, `north west lines` --> `Lines`
- `grid`, `crosshatch` --> `Hachures`
- `dots`, `crosshatch dots` --> `Dots`
- `fivepointed stars`, `sixpointed stars` --> `Stars`
- `bricks` --> `Bricks`
- `checkerboard` --> `Checkerboard`

I suggest to use capital names, because this would be consistent to the `arrows.meta` library. What do you think?

**Comment by hmenke** [comment]
I haven't implemented `Bricks` and `Checkerboard` but I don't think they are widely used anyway.
https://tex.stackexchange.com/search?q=[tikz-pgf]+bricks brings up 37 hits
https://tex.stackexchange.com/search?q=[tikz-pgf]+checkerboard brings up 31 hits
Considering that the total number of questions tagged [tikz-pgf] is 24,295 this seems negligible.

**Comment by Mo-Gul** [comment]
I am ok with this. Thank you for the implementations!!
