### ISSUE TITLE
Babel and ngerman incompatibility

### ISSUE THREAD

**Issue by proteusGIT** [pgf-tikz/pgf#786]
It was recently discussed on de.comp.text.tex https://groups.google.com/forum/#!topic/de.comp.text.tex/OCdOU_etJ7U that the catcodes are not reset at the beginning of the tikzset command.
While this seems to be stated like this in the documentation, it might still not be the desirable behavior.
Then, tikzset must be in the preamble, inside a tikzpicture, or some catcode management has to be done by the user.

        \documentclass[]{minimal}

        \usepackage[ngerman,english]{babel}
        \usepackage{tikz}
        \usetikzlibrary{babel}

        \begin{document}

        \tikzset{
            FOOBAR/.style={minimum height=height("a123456789")+depth("a123456789")}
        }
        \begin{tikzpicture}
        \node[FOOBAR] at (0,0) {s};
        \end{tikzpicture}

        \end{document}

**Comment by hmenke** [comment]
Sorry, but won't fix.  It would lead to things like this:
```latex
\documentclass{article}
\usepackage[ngerman]{babel}
\usepackage{tikz}
\begin{document}
\tikzset{
  foo/.style={node contents={compound"=word}},
  bar/.style={node contents={\detokenize{compound"=word}}}, % simulate restting of catcodes
}
\begin{tikzpicture}
  \path (0, 0) node[foo]{} % empty {} needed because of #335
        (0,-1) node[bar]{};
\end{tikzpicture}
\end{document}
```
![broken](https://user-images.githubusercontent.com/1903556/69278194-b1e46200-0c46-11ea-8c6b-81031d135036.png)

**Comment by proteusGIT** [comment]
I am not expert enough to have an opinion here.
Since it is a bit difficult to figure out a solution, it would be great to have a warning/error message whenever a user with that setup uses tikzset outside of preamble and tikzpicture.

**Comment by hmenke** [comment]
No, I don't think I will do that.  There is absolutely no advantage from issuing a warning.  It will only spam people's log file.  As you mentioned, this behaviour is documented, which in this case I believe is sufficient.

BTW, you can apply the same trick that I used above to simulate resetting of catcodes, to make your example work as well:
```latex
\tikzset{
    FOOBAR/.style={minimum height=\detokenize{height("a123456789")+depth("a123456789")}}
}
```
or, if there is something you don't want to have detokenized, just detokenize the quotes:
```latex
\tikzset{
    FOOBAR/.style={minimum height=height(\string"\textbf{a123456789}\string")+depth(\string"a123456789\string")}
}
```
