### ISSUE TITLE
The function value about *ln(2^(-11.9))*

### ISSUE THREAD

**Issue by QJLc** [pgf-tikz/pgf#788]
The MWE is:
```
\documentclass{article}
\usepackage{tikz}
\begin{document}
\pgfmathparse{ln(2^(-11.9))}\pgfmathresult

\pgfmathparse{ln(0.000261663)}\pgfmathresult
\end{document}
```
the output:
```
-8.08588
-8.08588
```
`0.000261663` is an approximation to `2^(-11.9)`.

On other calculator, such as *Excel*, `ln(0.000261663)` produces `-8.248453142`.

In file *pgfmathfunctions.basic.code.tex*, the numbers in line **437** and line **457**  are same. After I noted the comment in line **437**, I changed the number in line **437** into `0.00048828125`, which is  an approximation to `2^(-11)`, the output of above MWE is:
```
-8.23672
-8.23672
```

**Comment by hmenke** [comment]
Bug reports **MUST** include a MWE!

**Comment by hmenke** [comment]
Thank you for this bug report.  The hardcoded constant is indeed wrong.  Now it is much closer to the IEEE value:
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\pgfmathparse{ln(2^(-11.9))}\pgfmathresult

\pgfmathparse{ln(0.000261663)}\pgfmathresult

\directlua{token.set_macro("pgfmathresult", string.format("\csstring\%.5f", math.log(2^(-11.9))))}\pgfmathresult
\end{document}
```
```none
-8.23672
-8.23672
-8.24845
```
It's still not exactly there, but the precision of TeX is also very limited.
