### ISSUE TITLE
Turtle's forward does not parse its argument

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#789]
Turtle's forward does not parse its argument. As a consequence, if you pass an expression with brackets, say, this leads to an error. The other turtle keys seem to parse their arguments. The following MWE shows the issue and has a suggestion for a fix.

**Minimal working example (MWE)**

```latex
\documentclass[tikz,border=3mm]{standalone}
\usetikzlibrary{turtle}
\begin{document}
\begin{tikzpicture}
   % works
   \draw[turtle={home,how/.style={color=blue},lt=180,fd,rt={180-atan(2)},
   fd={2.23607cm}}]; 
   % doesn't work
   %\draw[xshift=2cm,turtle={home,how/.style={color=blue},lt=180,fd,rt={180-atan(2)},fd={sqrt(5)*1cm}}]; 
\makeatletter
\tikzset{%
  turtle/forward/.default=\pgfkeysvalueof{/tikz/turtle/distance},%
  turtle/forward/.style={/utils/exec=\pgfmathsetlengthmacro\pgfutil@tempdima{#1},%
  /tikz/insert path={to[/tikz/turtle/how]++(\tikz@lib@turtle@dir:\pgfutil@tempdima)}}%
}%
\makeatother
   % works now
   \draw[xshift=4cm,turtle={home,how/.style={color=blue},lt=180,fd,rt={180-atan(2)},fd={sqrt(5)*1cm}}];    
\end{tikzpicture}
\end{document}
```

**Comment by hmenke** [comment]
The fix is much simpler than what you propose:
```patch
-  turtle/forward/.style={/tikz/insert path={to[/tikz/turtle/how]++(\tikz@lib@turtle@dir:#1)}}
+  turtle/forward/.style={/tikz/insert path={to[/tikz/turtle/how]++({\tikz@lib@turtle@dir}:{#1})}}
```
I also don't like `/utils/exec` and you should be aware that you can only have a single `/utils/exec` on the whole path, because it doesn't stack.

**Comment by ghost** [comment]
@hmenke  I agree that your fix is simpler.

**Comment by hmenke** [comment]
Also `how/.style={color=blue}` does not work (and cannot work) because you cannot have different colors for segments of a path.  That is a PDF limitation.  Maybe it should throw an error, but that is relatively hard to do consistently and also doesn't occur too often.

**Comment by ghost** [comment]
@hmenke  Yes, I kept this `how` from an answer on TeX.SE. And I agree. This was to mention the issue, and I am glad you fixed it. (BTW, the search engine on GitHub is pretty poor. It is nontrivial to check whether this issue has already been reported.)

**Comment by hmenke** [comment]
This is mainly to avoid people spamming duplicates of the same issue right after a release like #675, #680, #697.  Don't bother with it too much.  In the present case, if searching for `turtle` doesn't bring up a dupe, you can just open a new one.

**Comment by hmenke** [comment]
BTW, there is another possibility to fix this.  Add this to your preamble:
```latex
% magic
\pgfkeys{
  /handlers/.evaluated/.code={
    \pgfmathparse{#1}%
    \expandafter\pgfkeysalso\expandafter{\expandafter\pgfkeyscurrentpath\expandafter=\expandafter{\pgfmathresult}}%
  }
}
```
and then use
```latex
fd/.evaluated={sqrt(5)*1cm}}
```
This new handler will be built into the next release.  I just added it a few days ago: https://github.com/pgf-tikz/pgf/commit/09c0e86b3b12bcdb16c96e5ccfd73fdbb95ffc7f

**Comment by ghost** [comment]
@hmenke  That's actually a *really* great tool to have! Apart from the applications you highlight, you could imagine adding an fpu version which only switches for the evaluation of these keys to fpu.
