### ISSUE TITLE
ConTeXt: \AtBeginDocument is defined as {#1}

### ISSUE THREAD

**Issue by flying-sheep** [pgf-tikz/pgf#790]
**Brief outline of the bug**

Pgfplots [uses `\AtBeginDocument`](https://github.com/live-clones/pgfplots/blob/f1eca1919d73d7b7bcaaad9506ea21d6b6ba4fd5/tex/generic/pgfplots/sys/pgfplotssysgeneric.code.tex#L82) to display a message unless it’s disabled.

Despite setting `\pgfplotsset{compat=1.14,compat/show suggested version=false}`, I still see:

> Package pgfplots notification 'compat/show suggested version=true': document has been generated with the most recent feature set (\pgfplotsset{compat=\mostrecent})

(note that I really do see `\mostrecent`, it’s not being expanded)

This is the result of the stub implementation of `\AtBeginDocument` in this project:

https://github.com/pgf-tikz/pgf/blob/88d7f561eee62cde1adaf7c85212659ae25e79ef/tex/generic/pgf/utilities/pgfutil-context.def#L362

I think there might be hints to a proper implementation [here](https://tex.stackexchange.com/q/151248/2867), something using `\appendtoks...\to\everystarttext` and maybe some `\expandafter` magic.

**Minimal working example (MWE)**

```tex
\usemodule[pgfplots]
% now \pgfplots@show@suggested@compat@value is already expanded and the message displayed
\pgfplotsset{compat=1.14,compat/show suggested version=false}

\starttext
% the contents of \AtBeginDocument{...} should be expanded here
\stoptext
```

**Comment by hmenke** [comment]
Moved to https://sourceforge.net/p/pgfplots/bugs/229/
