### ISSUE TITLE
Permalinks are broken in recent versions of the manual

### ISSUE THREAD

**Issue by astoff** [pgf-tikz/pgf#796]
Until at least version 3.0.1a, the PGF manual used to have "permalinks", that is, named destinations like `pgf./tikz/dash:pattern` or `pgf.<CS>draw` that wouldn't change across versions.

In version 3.1.4b, those permalinks are gone, and are replace by things like `pgfmanual-pos-84`, which don't seem to be durable. See for instance [this link](http://texdoc.net/texmf-dist/doc/generic/pgf/pgfmanual.pdf#pgfmanual-pos-84), and compare with [this link](http://texdoc.net/texmf-dist/doc/generic/pgf/pgfmanual.pdf#pgf./tikz/dash:pattern), which used to work.

With this change, it's impossible to reliably point to a specific spot of the manual on an online forum, among other interesting use cases.

**Comment by hmenke** [comment]
That is likely a problem in `hyperref`.

**Comment by davidcarlisle** [comment]
I don't think we have intentionally changed anything in hyperref there in recent years, however anything's possible. If an example that's a bit smaller than the tikz manual could be posted to
https://github.com/latex3/hyperref/issues
we'd certainly look....

**Comment by hmenke** [comment]
I quickly browsed through the macros and it seems that the manual is overriding `hyperref` there to make the manual compatible with `dvisvgm` which does not support “permalinks”, although I don't even think that this is supported by PDF and rather just a viewer feature that there is some kind of link name translation.

**Comment by hmenke** [comment]
For reference:
https://github.com/pgf-tikz/pgf/blob/d8ae2fc6295699ca7747d181bc8ed50136b6e6a3/doc/generic/pgf/macros/pgfmanual-en-macros.tex#L18-L33

**Comment by hmenke** [comment]
@davidcarlisle Would it be possible to have `hyperref` [percent-encode](https://en.wikipedia.org/wiki/Percent-encoding) links when using `dvisvgm`?  Then I could get rid of all the extra code.

**Comment by davidcarlisle** [comment]
@hmenke  the answer must be yes, I'll have to have a look what it's currently doing. A dvisvgm test case in a hyperref repo issue  would be appreciated (otherwise I might simply forget:-)

**Comment by hmenke** [comment]
It seems as if `dvisvgm` has changed and does not use the label directly anyway.  I have removed all the `\cleanuplink` bullshit and now the links in the SVG look like this
```html
<a xmlns="http://www.w3.org/2000/svg" xlink:href="pgfmanual-0227.svg#loc1449" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:title="pgf.back/coordinate">...</a>
```
Note how the label is actually in `xlink:title` and not in `xlink:href`.

@astoff The PDF manual should have human readable link labels again.  You can check here: https://pgf-tikz.github.io/pgf/pgfmanual.pdf
However, I don't want to make any guarantees about the long-term stability of these links, because there are way too many factors that influence them.  I can promise you though that I won't break them deliberately.

**Comment by astoff** [comment]
Great! The command hyperlinks changed from, say, `pgf.<CS>draw` to `pgf.back/draw`. This is a minor issue, but it would be nice to try to stabilize around one convention.
