### ISSUE TITLE
ConTeXt, remember picture and lastxpos

### ISSUE THREAD

**Issue by jeanprey** [pgf-tikz/pgf#797]
Using remember picture with ConTeXt produces a fatal error.

The problem seems to be that \lastxpos and \lastypos are strings, so they don't need \the to be written out.

I patched the file `pgfutil-context.def` according to bug report #742 and commit 47f8725 before reporting this problem.

With TeXLive 2019 (ConTeXt 20190321 MKIV) and pgf 3.1.4b, the minimal working example

```tex
\usemodule[tikz]
\starttext
\starttikzpicture[remember picture]
\stoptikzpicture
\stoptext
```

produces (see complete log attached)

```
tex error       > tex error on line 1 in file /Users/jprey/Desktop/MWE-remember-picture.tex: ! You can't use `the character 4' after \the

l.1 4
   661756
\lastxpos ->\clf_lastxpos 
                          
<write> \noexpand \pgfsyspdfmark {pgfid1}{\the \lastxpos 
                                                 }{\the \lastypos }
<inserted text> 
}\endwrite 
<argument> \shipoutscratchbox 
                   
\page_shipout_box #1->\clf_shipoutpage #1
                                         \relax \setbox #1\emptybox \global ...
...
l.5 \stoptext
```
[MWE-remember-picture.log](https://github.com/pgf-tikz/pgf/files/3912330/MWE-remember-picture.log)

**Comment by hmenke** [comment]
That is a bug in ConTeXt.  It's fixed in beta (I think) but not in TeX Live 2019.  To work around it, add this to your document:
```latex
\unexpanded\def\lastxpos{\numexpr\clf_lastxpos\relax} 
\unexpanded\def\lastypos{\numexpr\clf_lastypos\relax}
```
See also:
- https://tex.stackexchange.com/questions/492097/cannot-remember-picture-with-tikz-in-context
- https://mailman.ntg.nl/pipermail/dev-context/2019/003602.html
