### ISSUE TITLE
\pgfmathparse breaks with uppercase letter O

### ISSUE THREAD

**Issue by PhelypeOleinik** [pgf-tikz/pgf#798]
**Brief outline of the bug**

(from [here](https://tex.stackexchange.com/q/518980/134574)) `\pgfmathparse` breaks with an uppercase letter `O`, I believe, because of a missing `O` here:

https://github.com/pgf-tikz/pgf/blob/633e4b36fc3ce6a8783ff52eafec3d22994e7208/tex/generic/pgf/math/pgfmathparser.code.tex#L241

**Minimal working example**

```tex
\input tikz.tex
% \catcode`\@=11
% \def\pgfmath@token@functional@O{O}
\tikzset{declare function={Oh_No = 3;}}
\pgfmathparse{Oh_No}
\pgfmathresult
\bye
```

**Comment by hmenke** [comment]
Oh, that is embarrassing.

**Comment by PhelypeOleinik** [comment]
What I find most amusing is that this seems to be the first time in 11 years (according to [this](https://github.com/pgf-tikz/pgf/blame/633e4b36fc3ce6a8783ff52eafec3d22994e7208/tex/generic/pgf/math/pgfmathparser.code.tex#L241)) that someone tries to use an `O` in `\pgfmathparse`!
