### ISSUE TITLE
Can not use addition in foreach header

### ISSUE THREAD

**Issue by nolyn** [pgf-tikz/pgf#799]
I like defining the step size I use in foreach before I use it the first time. I then basically add my step size in the foreach header in order to make it work correcty. See the example below. This used to work until recently. 
I'm using arch linux. I suspect this broke in the update from texlive-core-2019.50917-1-any.pkg.tar.xz  
 to texlive-core-2019.52579-1-any.pkg.tar.xz, which I did recently. 
Let me know if this is a bug or if setting the step size in this way is simply not supported (any longer).

```latex
\documentclass{scrartcl}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

\usepackage{tikz} 

\begin{document}

\begin{tikzpicture}

  \def\stepsize{0.1} 

  \pgfmathsetmacro{\firstStep}{-1+\stepsize}
  % this works
  \foreach \x in {-1,\firstStep,...,1}
  {
    \draw (\x,0) -- (\x,1);
  }

  % this does not 
  \foreach \x in {-1,-1+\stepsize,...,1}
  {
    \draw (\x,0) -- (\x,1);
  }

\end{tikzpicture}
      
\end{document}
```

**Comment by hmenke** [comment]
This “feature” was rather buggy and now requires explicit activation, see #506 and https://github.com/pgf-tikz/pgf/commit/d7770565
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
  \def\stepsize{0.1}
  \foreach \x [parse=true] in {-1,-1+\stepsize,...,1} {
    \draw (\x,0) -- (\x,1);
  }
\end{tikzpicture}
\end{document}
```
BTW, this is documented, so reading the manual would have helped.
![test](https://user-images.githubusercontent.com/1903556/70178322-ef65e680-1740-11ea-95a7-07296fdf39cb.png)

**Comment by nolyn** [comment]
Thanks! I did check the manual, but gave up after the first dozen examples of foreach did nothing like I wanted.
