### ISSUE TITLE
Inconvenience/bug when adding a matrix node to a path.

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#801]
If one wants to use a matrix node inside (with inside being specified below) a path, one currently has to use an `ampersand replacement`. 

Probably it is easier to understand what that means from the MWE:

**Minimal working example (MWE)**
```latex
\documentclass[tikz,border=3mm]{standalone}
\usetikzlibrary{matrix}
\begin{document}
\begin{tikzpicture}
 % works:
 \draw (0,0) -- (5,0) node[pos=0.2,above,matrix of nodes] {1 & 2\\};
 % doesn't work:
 %\draw (0,-2) --  node[pos=0.2,above,matrix of nodes] {1 & 2\\}(5,-2);
 % works:
 \draw (0,-4) --  node[pos=0.2,above,matrix of nodes,ampersand replacement=\&]
 {1 \& 2\\}(5,-4);
\end{tikzpicture}
\end{document}
```

As one can verify by uncommenting the line `\draw (0,-2) --  node[pos=0.2,above,matrix of nodes] {1 & 2\\}(5,-2);` there is a small issue. A workaround is to use `ampersand replacement`, as in the last `\draw` command.

Clearly, the analogue of the first construction does not work for `to` paths, and when one uses the workaround there are other issues, which however do not relate to the ampersand.  It is safer to place coordinates along the path and use those to add the matrices. 

I am not necessarily convinced that it is mandatory to fix the issue but it might make sense to mention the workaround in the manual. If you think it is a good idea to fix it, I will be happy to have a closer look.

**Comment by hmenke** [comment]
That is problematic and I don't think there is an easy fix.  Nodes on a path are collected into a macro and placed once the path is finished, so tokenization is inevitable.  Of course I could just `\scantokens` the collected label text, which comes with all the horrible problems... It's maybe worth trying it out.  I'll have a look.

**Comment by ghost** [comment]
I am not convinced that this is to be fixed. It is easy enough to work around this issue. Matrices are special in many regards (for instance, they cannot be rotated) so from my point of view a short remark in the manual would do.

**Comment by hmenke** [comment]
I've followed your suggestion and document the existing behaviour.
