### ISSUE TITLE
Illustrations in chapter "Animations" (26) extend beyond the printable region on the pages. 

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#802]
Version: 3.1.4b-108-g0ee48dc5

There is a margins problem in the whole Chapter 26, in particular in Sections 26.4 and 26.5. The illustrations extend beyond the standard (for the manual) page margin on 15mm, and on my printer even extend beyond the printable region (by 1-2 mm). This effect is particularly prominent on pages 411 and 412.

![image](https://user-images.githubusercontent.com/2077025/70200718-54283d80-174f-11ea-80a1-8cdd69dd7313.png)

**Comment by hmenke** [comment]
Till says they are allowed to go into the margin by 2cm.
https://github.com/pgf-tikz/pgf/blob/0ee48dc560679e7afdb6accce81a364bfdd9c730/doc/generic/pgf/macros/pgfmanual-en-macros.tex#L1732
If you really want to waste thousands of pages of paper on printing out this manual, which changes constantly, then choose the setting “[shrink to printable region](https://helpx.adobe.com/acrobat/kb/scale-or-resize-printed-pages.html)” in your print dialog.

**Comment by hmenke** [comment]
If you really want to have the margins shrunk, apply this patch and build the manual yourself.
```patch
diff --git a/doc/generic/pgf/macros/pgfmanual-en-macros.tex b/doc/generic/pgf/macros/pgfmanual-en-macros.tex
index 314ebd3b..da4c0cd8 100644
--- a/doc/generic/pgf/macros/pgfmanual-en-macros.tex
+++ b/doc/generic/pgf/macros/pgfmanual-en-macros.tex
@@ -1729,7 +1729,7 @@
         \ifdim\wd\codeexamplebox>\codeexamplewidth%
         \else%
           \hsize\codeexamplewidth%
-          \advance\hsize by2cm%
+          %\advance\hsize by2cm%
         \fi%
         \leavevmode\catcode`\^^M=9%
         \foreach \pgfmanualtime/\pgfmanualtimehow in\code@animation@list{%
@@ -1743,7 +1743,7 @@
           \lower\ht\codeexampleboxanim\box\codeexampleboxanim\hfil\penalty0\hskip0ptplus-1fil%
         }%
       }%
-      \setbox\codeexampleboxanim=\hbox{\hbox{}\hskip-2cm\box\codeexampleboxanim}%
+      %\setbox\codeexampleboxanim=\hbox{\hbox{}\hskip-2cm\box\codeexampleboxanim}%
       \fi%
       \ifdim\wd\codeexamplebox>\codeexamplewidth%
         \def\code@start{\par}%
```

**Comment by ghost** [comment]
No, I don't understand this. The whole document is typeset with the 15mm margin. If the illustrations were allowed to "advance" by 15mm (that is tightly matching the page border), this I would understand. Not very beautiful, but saves space. But 2cm=20mm I don't understand. This is literally outside of the page.

UPD: Moreover, there is _a lot_ of blank space on those pages. 

![image](https://user-images.githubusercontent.com/2077025/70202858-fa774180-1755-11ea-80ea-f4bd0f65ed03.png)
