### ISSUE TITLE
More intuitive interaction with the translator package

### ISSUE THREAD

**Issue by keinstein** [pgf-tikz/pgf#804]
**Move/Add the definition of `\pgfutil@translate` to \begin{document}**

Playing around with the `calendar` tikz library in a LaTeX document I had some problems to get the translations to work.
Actually I have loaded the packages in the following order:
```
\usepackage[ngerman]{babel}
\usepackage{tikz}
\usepackage{translator}
\usetikzlibrary{calendar}
```

Even though I loaded the translator package before the calendar library the translations of months and days names did not work. Intutively the translation of the calendar should work also in this setting, as the `translator` package is loaded before the package that shall be translated (the TikZ calendar library). This impression is also triggered by the fact that the pgf calendar library provides the macro `\translate` if it is not defined in `tex/generic/pgf/utilities/pgfcalendar.code.tex`:
```
% Translation stuff

\ifx\translate\@undefined
  \def\translate#1{#1}
\fi

% Load month dictionary, if possible

\ifx\usedictionary\@undefined
\else
  \usedictionary{translator-months-dictionary}
\fi

```

I see different possible solutions (some of them may be useful in combination):
1. Make `\pgfutil@translate` dynamically check for `\translate`
2. Redefine `\pgfutil@translate` directly after loading `translator.sty`
3. Redefine `\pgfutil@translate` at the beginning of each library that uses the translation mechanism.
4. Redefine `\pgfutil@translate` at `\begin{document}`

*Note:* This is not a duplicate of #725 , as loading `translator` before `tikz` works in my case.

**Comment by hmenke** [comment]
What's the problem with loading `translator` before `tikz`?  Does it not work?

**Comment by hmenke** [comment]
I have documented the required loading order in the manual.

**Comment by keinstein** [comment]
Sorry, the source code example above from `tex/generic/pgf/utilities/pgfcalendar.code.tex` does not suggest that this is the *right* solution. There is no call to `\translate` in that file. So I conclude that the original author considered the my loading order to be correct.

**Comment by keinstein** [comment]
Sorry I didn't get the notification for your last question.
BTW. The original author probably intented the 3rd solution from my List.
