### ISSUE TITLE
[doc] Wrong library annotations in graph, on cover page of Part IV

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#818]
Version: 3.1.5b

On page 415, the cover page of Part IV _Graph Drawing_, the library annotations of graph is wrong.

In documentation of 3.1.5b and the latest source code, library `arrows.meta` is loaded, and this leads to `! Package pgf Error: Unknown arrow tip kind 'spaced stealth''.`. But `arrows.spaces` is actually needed.
https://github.com/pgf-tikz/pgf/blob/478d9d4b29154c52f52448399e46b0f0cd6f1045/doc/generic/pgf/text-en/pgfmanual-en-main-body.tex#L398-L420

Full example:
```tex
% !TeX program = lualatex
\documentclass{article}
\usepackage{tikz}
%\usetikzlibrary {arrows.meta,graphs,graphdrawing} % in doc
\usetikzlibrary{arrows.spaced, graphs, graphdrawing}
\usegdlibrary{layered}

\begin{document}
\tikz[
  nodes={
    text height=.7em, text depth=.2em, draw=black!20, thick, fill=white, font=\footnotesize
  },
  >=spaced stealth', rounded corners, semithick
]
  \graph[layered layout, level distance=1cm, sibling sep=.5em, sibling distance=1cm] {
    "5th Edition" -> { "6th Edition", "PWB 1.0" };
    "6th Edition" -> { "LSX" [>child anchor=45], "1 BSD", "Mini Unix", "Wollongong", "Interdata" };
    "Interdata" -> { "Unix/TS 3.0", "PWB 2.0", "7th Edition" };
    "7th Edition" -> { "8th Edition", "32V", "V7M", "Ultrix-11", "Xenix", "UniPlus+" };
    "V7M" -> "Ultrix-11";
    "8th Edition" -> "9th Edition";
    "1 BSD" -> "2 BSD" -> "2.8 BSD" -> { "Ultrix-11", "2.9 BSD" };
    "32V" -> "3 BSD" -> "4 BSD" -> "4.1 BSD" -> { "4.2 BSD", "2.8 BSD", "8th Edition" };
    "4.2 BSD" -> { "4.3 BSD", "Ultrix-32" };
    "PWB 1.0" -> { "PWB 1.2" -> "PWB 2.0", "USG 1.0" -> { "CB Unix 1", "USG 2.0" }};
    "CB Unix 1" -> "CB Unix 2" -> "CB Unix 3" -> { "Unix/TS++", "PDP-11 Sys V" };
    { "USG 2.0" -> "USG 3.0", "PWB 2.0", "Unix/TS 1.0" } -> "Unix/TS 3.0";
    { "Unix/TS++", "CB Unix 3", "Unix/TS 3.0" } -> "TS 4.0" -> "System V.0" -> "System V.2" -> "System V.3";
  };
\end{document}
```

**Comment by muzimuzhi** [comment]
In commit https://github.com/pgf-tikz/pgf/commit/c29b79a0d3543fbe8309304a00e9bc9e23cde768, `arrows.spaced` was substituted by `arrows.meta`, which brings problem to the reported code example. There may exist other code examples having similar problem.

**Comment by hmenke** [comment]
I have no idea where you got `spaced stealth'` from.  The version you are looking at must be inconsistent, because the commit you linked does not only replace `arrows.spaced` with `arrows.meta` but also replaces `spaced stealth'` with `Stealth[round,sep]`, so there is no inconsistency.

**Comment by muzimuzhi** [comment]
I was careless. That `spaced stealth'` was from my previous local file. So sorry.
