### ISSUE TITLE
Should `stealth'` arrow tip should be replaced by `stealth` in "Tutorial: A Petri-Net for Hagen"?

### ISSUE THREAD

**Issue by KZiemian** [pgf-tikz/pgf#819]
Version: 3.1.4b.

Chapter 3 "Tutorial: A Petri-Net for Hagen", pages 57, 59.

In styles definition arrow tip is given by command ">=stealth'". From what I understand this is command from deprecated `arrows` library and we should using `stealth` from `arrows.meta`.

If this is right and changes are needed I will create appropriate pull request.

**Comment by hmenke** [comment]
Is it `stealth` or `stealth'`?  The former is a built-in tip whereas the latter is from `arrows` and should be replaced by `Stealth[round]` (I think, please double-check).

**Comment by hmenke** [comment]
Already fixed in c29b79a0d3543fbe8309304a00e9bc9e23cde768
I would really appreciate if you checked more carefully if the issue actually still existed, because this is just a waste of time.
