### ISSUE TITLE
Add explicit information about loading `angles` library

### ISSUE THREAD

**Issue by KZiemian** [pgf-tikz/pgf#820]
Version: 3.1.4b.

Section "18.2.1 The Quotes Syntax", pages 263-264.

Since to draw example in this section you need to load `angles` library, I suggest to state this clearly in the text. In another situation new user may think that is part of "build-in" TikZ and feel very confused when he will get an error.

Also, this is no obvious way to guess that the name of this library is `angles`, not `angle` or `anglepic`.

**Comment by hmenke** [comment]
Already fixed by 66badb1184c81a7817663a432d6e08b5e5bc35bf
It's generally better to report bugs only against the latest version.
