### ISSUE TITLE
{command} environment does not work with starred command.

### ISSUE THREAD

**Issue by joulev** [pgf-tikz/pgf#830]
**Brief outline of the bug**

I am using the [`pgfmanual` package](https://github.com/pgf-tikz/pgf/tree/master/tex/latex/pgf/doc) and [pgfmanual-en-macros.tex](https://github.com/pgf-tikz/pgf/blob/master/doc/generic/pgf/macros/pgfmanual-en-macros.tex) to get a nice documentation style and automatic hyperlinks in one of my documents. While it is working very fine overall, the `{command}` environment doesn't seem to accept starred commands.

**Minimal working example (MWE)**

```latex
\documentclass{ltxdoc}
\usepackage{tikz}

% https://tex.stackexchange.com/a/73103

% necessary for the manual styles:
\usepackage{calc}

% for cross-references:
\usepackage[pdfborder=0 0 0,unicode]{hyperref}

\def\pgfautoxrefs{1}
\input{pgfmanual-en-macros.tex}

\makeatletter
\def\index@prologue{\section*{Index}\addcontentsline{toc}{section}{Index}}
\makeatother

% Automatic cross-referencing
\RequirePackage{pgfmanual}

% this here configures automatic cross referencing.
% It works for ANY package that uses pgfkeys and is independent on tikz/pgf. 
\pgfkeys{
  /pdflinks/search key prefixes in={/tikz/,/pgf/},
  /pdflinks/internal link prefix=pgfp,
  /pdflinks/codeexample links=true,
  /pdflinks/warnings=false,   % for debugging 
  /pdflinks/show labels=false,% for debugging
}

\begin{document}
\begin{command}{\hello}
  This command does some interesting things.
\end{command}
\begin{command}{\hello*}
  Starred version of the interesting command.
\end{command}
Test: |\hello|, |\hello*|.
\end{document}
```

![image](https://user-images.githubusercontent.com/44609036/73749140-59285e00-478d-11ea-9cf5-a911fa0e15f1.png)

The star is not formatted correctly. Also, both hyperlinks at the bottom line link to `\hello`, although one should link to `\hello*`.

**Comment by joulev** [comment]
Ah, starred commands don't exist in plain TeX. This can reproduce the issue in a non-pgfmanual way:

```tex
\def\foo#1{{\tt\string#1}}
\foo\bar\par
\foo\bar*
\bye
```

I think there should be a switch to check whether it is LaTeX or plain TeX. If it is in LaTeX something other than `\string` should be used, as the command will never accept starred variants.

**Comment by hmenke** [comment]
> starred commands don't exist in plain TeX

Exactly, in fact, starred commands also don't exist in LaTeX.  The star is actually an argument rather than part of the name.

**Comment by joulev** [comment]
Do you have any idea of how to fix this? Otherwise starred commands can't be documented this way. Of course, I can rewrite my macros to get rid of starred commands, but obviously this is not a good solution.

**Comment by hmenke** [comment]
What do you mean by “fixed”?  You have to realize that `\hello*` is not the same as `\csname hello*\endcsname`.

**Comment by joulev** [comment]
> You have to realize that `\hello*` is not the same as `\csname hello*\endcsname`.

Of course. However, imagine I have to document `\newcommand*`. It is *different* from `\newcommand`, so I can't put it to the same `{command}` environment, right? So, what to do?

Probably `fix' is not the right word here, but I am not good enough at English to find a better word :)

**Comment by davidcarlisle** [comment]
@joulev  as Henri already said `*` here is essentially an optional argument to `\newcomand` the use can be `\newcommand*`  or `\newcommand    *` the `*`  isn't part of the name, it is essentially a syntactic variant for `\newcommand [true]` that is, an option with just a boolean toggle star-or-not-star.  So it is quite natural to document a single `\newcommand` and document the `*` behaviour there along with documentation of other arguments.

**Comment by joulev** [comment]
> So it is quite natural do document a single `\newcommand` and document the `*` behaviour there along with documentation of other arguments.

@davidcarlisle Thanks for the suggestion. However the circumstance may be more complicated, like

```tex
\def\foo{\@ifstar\@@foo\@foo}
\def\@foo#1#2{Do something}
\def\@@foo#1#2#3#4{Do something else}
```

`\foo` and `\foo*` have different syntaxes, which make it impossible to document them in the same `{command}` environment. Probably this is not how `\@ifstar` and starred commands are intended to be used, but it is still possible that someone uses something like this.

**Comment by hmenke** [comment]
I think this is pointless and I don't have any use for this in PGF/Ti*k*Z.  If you want this feature you (or someone else) will have to implement this.  To this end I'm also applying the “help wanted” tag.

**Comment by hmenke** [comment]
@joulev I have found a workaround for this, which might be sufficient for your use-case:
```latex
\documentclass{ltxdoc}
\usepackage{tikz}

% https://tex.stackexchange.com/a/73103

% necessary for the manual styles:
\usepackage{calc}

% for cross-references:
\usepackage[pdfborder=0 0 0,unicode]{hyperref}

\def\pgfautoxrefs{1}
\input{pgfmanual-en-macros.tex}

\makeatletter
\def\index@prologue{\section*{Index}\addcontentsline{toc}{section}{Index}}
\makeatother

% Automatic cross-referencing
\RequirePackage{pgfmanual}

% this here configures automatic cross referencing.
% It works for ANY package that uses pgfkeys and is independent on tikz/pgf. 
\pgfkeys{
  /pdflinks/search key prefixes in={/tikz/,/pgf/},
  /pdflinks/internal link prefix=pgfp,
  /pdflinks/codeexample links=true,
  /pdflinks/warnings=false,   % for debugging 
  /pdflinks/show labels=false,% for debugging
}

\lccode`\*=`\*

\begin{document}
\begin{command}{\hello}
  This command does some interesting things.
\end{command}
\begin{command}{{\hello*}{}}
  Starred version of the interesting command.
\end{command}
Test: |\hello|, |\hello*|.
\end{document}
```
![test](https://user-images.githubusercontent.com/1903556/83207185-a5693500-a1a6-11ea-8b2a-95fc45ce5d36.png)

There are two parts to this workaround:

1. ``\lccode`\*=`\*``
    
    A control sequence in LaTeX is always made up of letters.  Usually you would distinguish letters by catcode 11, so naively one might be tempted to just use ``\catcode`\*=11``.  This will not work for two reasons: The first is that this will break normal usage of `*` in things like `\newcommand*` because this then suddenly becomes `\csname newcommand*\endcsname` which is not defined.  The other reason this will not work is that in the key parser which places the hyperlinks all the catcodes have been set to 12 (other) for verbatim printing.

    Hence the key parser cannot distinguish letters by catcode and falls back to another nasty trick.  Normal letters (A-Z, a-z) always have an upper and a lower case variant which is represented in TeX by the properties `\uccode` and `\lccode`.  All other characters have these codes set to zero and hence to distinguish between letters and other characters we can query the `\lccode`.  What the one line in the beginning does is settings `\lccode` of `*` to itself which is non-zero and should hopefully prevent weird surprises in corner cases like `\lowercase{\newcommand*\foo{}}` where the `\lccode` is actually used.

2. `\begin{command}{{\hello*}{}}`

    The way that the manual macros split the control sequence from the rest is pretty simple.  It just takes the first token and everything else is considered arguments.  By placing explicit grouping to separate the first “token” from the rest we can swiftly work around that.

**Comment by joulev** [comment]
@hmenke Oh, it looks great! Will try it out, thanks.

**Comment by hmenke** [comment]
I've asked on the TeX.SX chat whether anyone can think of a case where ``\lccode`\*=`\*`` would break something.

David Carlisle [replied](https://chat.stackexchange.com/transcript/message/54511954#54511954):

> break isn't the right word necessarily but it changes the hyphenation of `wibble*` (potentially)

So you might want to do something like
```latex
\makeatletter
\g@addto@macro\pgfmanualprettyprintstyles{\lccode`\*=`\*\relax}
\makeatother
```
to limit the scope of that definition to the pretty-printed regions only.

**Comment by hmenke** [comment]
@joulev If this workaround works for you, I would like to close this request.

**Comment by joulev** [comment]
@hmenke Oh, of course. Thank you very much.
