### ISSUE TITLE
Outdated circle syntax in manual

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#832]
Version: 3.1.5b

There are still many examples in the manual in which the circle construction is used in the old-fashioned way, i.e. with 

`circle(<radius>)`

as opposed to

`circle[radius=<radius>]
`

In the range up to p. 150 there are 20 such usage examples on pp. 38, 39, 40, 44, 64, 66, 68, 69, 137, 145, 148, 149.

In the plain Ti*k*Z world this is not a big problem. The real problem is that this syntax does no longer work in pgfplots. Of course, one may change things there. Yet I feel that it might make sense to completely switch to the new syntax in the manual. (Too bad that I cannot really deal with Github.)

**Comment by hmenke** [comment]
I had email communication with @cfeuersaenger recently.  As I understood it a fix is on the way.

**Comment by hmenke** [comment]
Just ping me if it's not fixed in a week, then I'll work around pgfplots's broken usage of TikZ internals on my side. You can expect pgfplots to break more often as TikZ progresses.

**Comment by hmenke** [comment]
I've submitted the following patch to the pgfplots maintainers.
```diff
diff --git a/tex/generic/pgfplots/pgfplots.paths.code.tex b/tex/generic/pgfplots/pgfplots.paths.code.tex
index 077a3a2b..e4f4a8fd 100644
--- a/tex/generic/pgfplots/pgfplots.paths.code.tex
+++ b/tex/generic/pgfplots/pgfplots.paths.code.tex
@@ -30,17 +30,39 @@
 \def\pgfplots@install@path@replacements{%
        \ifpgfplots@path@replace@ellipse
                \let\tikz@do@circle=\pgfplots@path@@tikz@do@circle
+               \let\tikz@do@ellipse=\pgfplots@path@@tikz@do@ellipse
                \expandafter\def\expandafter\pgfinterruptpicture\expandafter{\pgfinterruptpicture
                        \let\tikz@do@circle=\pgfplots@path@@tikz@do@circle@orig
+                       \let\tikz@do@ellipse=\pgfplots@path@@tikz@do@ellipse@orig
                }%
        \fi
 }%
 
 \let\pgfplots@path@@tikz@do@circle@orig=\tikz@do@circle
+\let\pgfplots@path@@tikz@do@ellipse@orig=\tikz@do@ellipse
 
 % This is a replacement for \tikz@do@circle which replaces the "xy"
 % coordinate system by one which is compatible with pgfplots.
-\def\pgfplots@path@@tikz@do@circle#1#2{%
+\def\pgfplots@path@@tikz@do@circle#1{%
+  \begingroup
+  \ifpgfplots@usefpu
+       \pgfkeys{/pgf/fpu,/pgf/fpu/output format=fixed}%
+  \fi
+  \pgfmathparse{#1}%
+  \let\tikz@ellipse@x=\pgfmathresult%
+  \ifpgfmathunitsdeclared
+    \pgfpathellipse{\pgfpointorigin}%
+      {\pgfqpoint{\tikz@ellipse@x pt}{0pt}}%
+      {\pgfpoint{0pt}{\tikz@ellipse@x pt}}%
+  \else
+    \pgfpathellipse{\pgfpointorigin}%
+      {\pgfplotspointaxisdirectionxy{\tikz@ellipse@x}{0}}%
+      {\pgfplotspointaxisdirectionxy{0}{\tikz@ellipse@x}}%
+  \fi
+  \endgroup
+}
+
+\def\pgfplots@path@@tikz@do@ellipse#1#2{%
   \begingroup
   \ifpgfplots@usefpu
        \pgfkeys{/pgf/fpu,/pgf/fpu/output format=fixed}%
```

**Comment by ghost** [comment]
@hmenke  Is this the complete patch? It does not seem to provide the complete (re)definition of `\pgfplots@path@@tikz@do@ellipse`.

**Comment by hmenke** [comment]
The patch only contains lines that actually changed.  You have to apply the patch to your copy of the `pgfplots` sources, see https://git-scm.com/docs/git-apply

**Comment by ghost** [comment]
@hmenke Thanks!

**Comment by hmenke** [comment]
This patch has landed in `pgfplots` officially now.
https://sourceforge.net/p/pgfplots/code/ci/b6b6111dec2c4e198837e45960dbea38e79045c1/
I can't tell when the new release will be published but it will be there eventually.  I'm closing this now.

**Comment by lesshaste** [comment]
Why does this have the tag closed-wont-fix? It seems it  has been fixed.

**Comment by Mo-Gul** [comment]
@lesshaste, yes, but it has been fixed PGFPlots and not in TikZ. That's why it is correct to state *here* that it wasn't fixed and won't be fixed.
