### ISSUE TITLE
bend right=<angle> ignores non-integer part of angle

### ISSUE THREAD

**Issue by PeterGrill** [pgf-tikz/pgf#837]
The MWE below uses a noninteger value `bend_right=9.5` and results in the following two message in the log file:

    Missing character: There is no . in font nullfont!
    Missing character: There is no 5 in font nullfont!

These two messages go away if an integer value is used.

This seems to be an issue in `tikzlibrarytopaths.code.tex` as per [Are non-integer values of bend right=<angle> allowed in TikZ?](https://tex.stackexchange.com/q/530861/4301).

**Minimal working example (MWE)**

```latex
\documentclass{article}
\usepackage{tikz}

\def\BendAngle{9}
\def\BendAngle{9.5}% <-- Commenting this out clears the two "Missing character" messages

\begin{document}
\begin{tikzpicture}
    \draw [ultra thick] (0,0) to [bend right=\BendAngle] (3,0); 
\end{tikzpicture}
\end{document}
```

**Comment by hmenke** [comment]
For some unknown reason there is also a striking asymmetry between the code paths for `bend left` and `bend right`.
https://github.com/pgf-tikz/pgf/blob/b5022401632df0de78c114c41707e56f68e43447/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytopaths.code.tex#L30-L58

**Comment by ghost** [comment]
@hmenke It is well known that the world is not left-right symmetric. ;-)

**Comment by hmenke** [comment]
BTW, here is how you backport the fix.
```latex
\documentclass{article}
\usepackage{tikz}

\makeatletter

\tikzoption{bend left}[]{%
  \def\pgf@temp{#1}%
  \ifx\pgf@temp\pgfutil@empty%
  \else%
    \pgfmathsetmacro\tikz@to@bend{#1}%
  \fi%
  \let\tikz@to@out=\tikz@to@bend%
  \pgfmathsetmacro\tikz@to@in{180-(\tikz@to@out)}%
  \tikz@to@switch@on%
  \tikz@to@relativetrue%
}

\tikzoption{bend right}[]{%
  \def\pgf@temp{#1}%
  \ifx\pgf@temp\pgfutil@empty%
  \else%
    \pgfmathsetmacro\tikz@to@bend{#1}%
  \fi%
  % Now, negate
  \pgfmathsetmacro\tikz@to@out{-(\tikz@to@bend)}
  \pgfmathsetmacro\tikz@to@in{180-(\tikz@to@out)}
  \tikz@to@switch@on%
  \tikz@to@relativetrue%
}

\makeatother

\def\BendAngle{9}
\def\BendAngle{9.5}

\begin{document}
\begin{tikzpicture}
    \draw [ultra thick] (0,0) to [bend right=\BendAngle] (3,0); 
\end{tikzpicture}
\end{document}
```
