### ISSUE TITLE
[doc] Some examples in Part IV lack codeexample info

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#839]
Version: 3.1.5b

 * All examples in Sec. 28.3 _Padding and Node Distances_, pp. 422--425. 
Corresponding source file: [`Distances.lua`](https://github.com/pgf-tikz/pgf/blob/master/tex/generic/pgf/graphdrawing/lua/pgf/gd/control/Distances.lua)
 * Sec. 28.4--28.7.3, pp. 426--436, 439--440
 * Sec. 28.8, pp. 442--443
 * Sec. 28.11, pp. 448--449
 * Sec. 30.1.1--30.2, pp. 460--464
 * Sec. 30.3, pp. 466--467
 * Sec. 31.1, pp. 469--470
 * Sec. 31.1.2, pp. 475--476
 * Sec. 31.1.4--31.1.4.5, pp. 477-479
 * Sec. 33--35, pp. 482--488

Related: https://github.com/pgf-tikz/pgf/issues/640#issuecomment-511471922

**Comment by hmenke** [comment]
@Mo-Gul

**Comment by Mo-Gul** [comment]
@hmenke, I would be happy to add the needed stuff, but currently I don't have a clue *how* (see also https://github.com/pgf-tikz/pgf/issues/640#issuecomment-511176605). If you would provide *one* example how to add options to `example` environments in Lua I'll hopefully be able to do the rest.

**Comment by hmenke** [comment]
I'm closing this in favour of #640.  We'll continue to track it over there.
