### ISSUE TITLE
`transform shape` as a label style interferes with `label position`

### ISSUE THREAD

**Issue by projekter** [pgf-tikz/pgf#843]
**Brief outline of the bug**

As soon as a `label` itself (and not just, as documented in the manual, the main node) gets the `transform shape` option, setting `label position` to any anchor will no longer work (`Unknown function: <anchor name>`). It does not matter whether the position is set via a global option, locally in the `label` via the colon syntax, or by using the `quotes` library. Using special keys such as `above`, `right`, or border angles, do work.
A perhaps more common situation (and this is how I found the bug) is to use `transform shape` on `every node`, which then of course also applies to the label.

**Minimal working example (MWE)**

```latex
\documentclass{article}

\usepackage{tikz}

\begin{document}

  \begin{tikzpicture}[every node/.style={transform shape}]
    \node[label=north:label] {main node};
  \end{tikzpicture}

\end{document}
```
(Though perhaps we should globally say something like `rotate=30` for `transform shape` to make any sense.)

**Comment by hmenke** [comment]
`north` is an anchor, not a direction.  You have to use `above`.
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}[every node/.style={transform shape}]
    \node[label=above:label] {main node};
\end{tikzpicture}
\end{document}
```
Sorry, not a bug.

**Comment by hmenke** [comment]
No, it's actually documented that anchors should work.

**Comment by ghost** [comment]
This is not a real solution but you can of course exclude labels from the transformations.

```
\documentclass{article}

\usepackage{tikz}

\begin{document}

  \begin{tikzpicture}[every node/.style={transform shape},
  	every label/.append style={transform shape=false}]
    \node[label=north:label] {main node};
  \end{tikzpicture}

\end{document}
```

**Comment by hmenke** [comment]
Possible patch, please test extensively.
```patch
diff --git a/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex b/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
index d0194f97..a371ddfc 100644
--- a/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
+++ b/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
@@ -790,13 +790,9 @@
       \pgf@xc=\pgf@x%
       \pgf@yc=\pgf@y%
       \tikz@label@simplefalse%
-      \iftikz@fullytransformed%
-        \tikz@label@simpletrue%
-      \else
-        \ifdim\pgf@xc=\pgf@xb\relax%
-          \ifdim\pgf@yc=\pgf@yb\relax%
-            \tikz@label@simpletrue%
-          \fi%
+      \ifdim\pgf@xc=\pgf@xb\relax%
+        \ifdim\pgf@yc=\pgf@yb\relax%
+          \tikz@label@simpletrue%
         \fi%
       \fi%
       \iftikz@label@simple%
```
In the old code the conditional `\iftikz@label@simple` was set to true when `transform shape` was in place.  I do not understand the reason for this at all.  Honestly I also don't really understand large parts of the rest of the code.  It seems as if `\iftikz@label@simple` will only ever be true when the label anchor coincides with the `center` anchor, which is only ever true for nodes of type `coordinate`.

This was introduced 12 years ago but the commit doesn't have sufficient explanation to really infer what is going on: https://github.com/pgf-tikz/pgf/commit/8db68657fea16e34dec7549ccf63cacf336832c8

Unfortunately there is still no proper testsuite for PGF/TikZ in place which would allow me to simply push this and see whether things start failing.  Maybe I'll hold this off until we have some testcases.
