### ISSUE TITLE
`\pgfpointtransformed` is mentioned, but not documented

### ISSUE THREAD

**Issue by projekter** [pgf-tikz/pgf#844]
Version: 3.1.5b

On page 1164, the documentation to `\pgfpointtransformednonlinear` reads:

> Works like `\pgfpointtransformed`, but also applies the current nonlinear transformation...

However, `\pgfpointtransformed` is not documented at all - but it really should be, I'd say it is rather a rather important function.

For developers, it would also be nice to know what the recommended way for generic code (i.e. without knowing what the user specifies as a transformation) is: Always call  the (more general?) nonlinear point transformation, or, as `\pgfpathmoveto` or `\pgfpathlineto`, always only call the linear one and execute special macros afterwards that deal with the nonlinear case (which probably then require some patching of `\pgftransformnonlinear` in order to install these commands.

**Comment by hmenke** [comment]
Ultimately only @tantau can tell, but it looks to me like `\pgfpointtransformed` is deprecated and you should use `\pgftransformrotate`, `\pgftransformshift`, etc. instead.  I'd argue the same applies to `\pgfpointtransformednonlinear` and you should use `\pgftransformnonlinear` instead.

**Comment by projekter** [comment]
Those macros fulfill a completely different purpose - `\pgftransformrotate` and the like install the given transformation, so that all future points are transformed by this specification. `\pgfpointtransformed` is the way how this is actually achieved internally - it applies all transformations that are currently known to the given point and returns what comes out. All path construction macros call `\pgfpointtransformed`, so I can hardly believe it is deprecated.
