### ISSUE TITLE
name prefix and name suffix vs. edge: starting point of edge paths are incorrect

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#846]
It seems that there is some problem using nodes with `name prefix` (or `name suffix` for that matter) and the `edge` path construction. When one switches on either of them, the edge will connect to the node center of the starting node.

```latex
\documentclass[tikz,border=3mm]{standalone}
\begin{document}
\begin{tikzpicture}[nodes={circle,draw},>=stealth]
 \begin{scope}[name prefix=L-]
  \path node (A) {A} (2,0) node (B){B};
  \path (A) edge (B);
 \end{scope}
 \begin{scope}[xshift=4cm]
  \path node (A) {A} (2,0) node(B){B};
  \path (A) edge (B);
 \end{scope}
\end{tikzpicture}
\end{document}
```

<img width="837" alt="Screen Shot 2020-04-13 at 6 10 59 AM" src="https://user-images.githubusercontent.com/35985244/79122841-9f7dd880-7d4d-11ea-83ad-f70ce3b082f3.png">

Left  is a scope with a `name prefix`, and the edge extends to the center of the `A` node, where as in the right scope, where there is no node prefix, the result is as expected. If we use a `name suffix`, the same problem arises.

**Comment by QJLc** [comment]
I may get the point of this issue.

See  **tikz.code.tex**.

After line 5427, I add   lines:
```latex
    \def\tikz@parse@node@temp{#2}%
    \ifx\tikz@parse@node@temp\tikztostart%
      \tikz@shapebordertrue%
    \fi%
```
this will set the  `(\tikztostart)` on shape border. But I do not know whether this will cause errors.

I guess, the key point about this issue is , command `\tikz@scan@one@point` sets `\tikz@shapeborderfalse`,  the full name `L-A` is saved in `\tikztostart`, so, `\tikz@shapeborderfalse` is always valid, and then, command `\tikz@@moveto`will set
```latex
\let\tikz@moveto@waiting=\relax
```

**Comment by hmenke** [comment]
Hm, I'm not sure whether this is the right way to approach this.  It seems like a very symptomatic treatment.  This patch also solves the problem and is maybe a bit more idiomatic.  I'm not sure which way to go.
```patch
--- a/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
+++ b/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
@@ -5431,7 +5431,13 @@
         \tikz@shapebordertrue%
         \def\tikz@shapeborder@name{\tikz@pp@name{#2}}%
       \fi%
-    \fi
+    \else\ifcsname pgf@sh@ns@#2\endcsname
+      \expandafter\ifx\csname pgf@sh@ns@#2\endcsname\tikz@coordinate@text%
+      \else
+        \tikz@shapebordertrue%
+        \def\tikz@shapeborder@name{#2}%
+      \fi%
+    \fi\fi
   \fi%
   \edef\tikz@marshal{\noexpand#1{\noexpand\pgfqpoint{\the\pgf@x}{\the\pgf@y}}}%
   \tikz@marshal%
```

**Comment by QJLc** [comment]
Yes, I have learned it, your patch is very reasonable.
The command
```\tikz@scan@one@point{\tikz@@moveto}(A)```
will define
```\def\tikz@shapeborder@name{L-A}```
so, the added line
```+        \def\tikz@shapeborder@name{#2}%```
could repeat the defination, is this repetition needed?
