### ISSUE TITLE
Patterns get offset when one converts the pdf file to (e.g.) gif

### ISSUE THREAD

**Issue by ghost** [pgf-tikz/pgf#850]
I really hope I do not repeat a bug but I tried to find a closely related issue but did not find a duplicate. The perhaps closest one is issue https://github.com/pgf-tikz/pgf/issues/775. The problem is that there is an offset in the pattern when one converts the output to GIF (say). Here is a rather minimal example.

```latex
\documentclass[tikz,border=3mm]{standalone}
    \usetikzlibrary{patterns.meta}
    \tikzdeclarepattern{
        name=neurons,
        type=uncolored,
        bounding box={(-1.25mm,-1.25mm) and (1.25mm,1.25mm)},
        tile size={(\tikztilesize,\tikztilesize)},
        parameters={\tikzcircleradius,\tikztilesize},
        tile transformation={
            xshift=1.75mm,
            yshift=1.75mm,
        },
        defaults={
            radius/.store in=\tikzcircleradius,radius=1mm,
            tile size/.store in=\tikztilesize,tile size=2.5mm,
        },
        code={
            \draw[thin] (0,0) circle[radius=\tikzcircleradius];
        },
    }
\begin{document}
\begin{tikzpicture}
    \path[pattern=neurons]  (-1.5,-1.5) rectangle +(3,3);
    \draw[red] (+.25 * 2 -0.375, -0.25 * 2+0.125) circle[radius=1mm];
\end{tikzpicture}
\end{document}
```

The resulting PDF shows

<img width="573" alt="Screen Shot 2020-04-28 at 1 05 15 AM" src="https://user-images.githubusercontent.com/35985244/80463027-6bc5b580-88ec-11ea-9128-738bfa0ac5fe.png">

The important point is that the red circle is really on top of a black circle.

However, when I convert this to a GIF via
```
convert -density 300 <file>.pdf test.gif
```
I get

<img width="366" alt="Screen Shot 2020-04-28 at 1 06 13 AM" src="https://user-images.githubusercontent.com/35985244/80463122-91eb5580-88ec-11ea-8254-10eef72e248d.png">

Other densities seem to come with slightly different offsets (or this is an illusion). The real problem is that there is an offset.

**Comment by hmenke** [comment]
Huh? Wouldn't this indicate a bug in imagemagick? Have you filed a bug there? What makes you think that this is a PGF bug?

**Comment by hmenke** [comment]
Hm, I can reproduce this with mupdf (I wouldn't trust the output of and [especially the input of imagemagick](https://imagetragick.com/)), but the shift seems to be dependent upon the rendering resolution.

100dpi
![test](https://user-images.githubusercontent.com/1903556/80472363-b8ff6100-8998-11ea-8508-a9cee7dcb32c.gif)

200dpi
![test](https://user-images.githubusercontent.com/1903556/80472386-c4528c80-8998-11ea-9b6b-13900a99c4fe.gif)

300dpi
![test](https://user-images.githubusercontent.com/1903556/80472413-cb799a80-8998-11ea-826a-8274e911a966.gif)

I quickly checked the low-level code for whether I forgot a pt->bp conversion somewhere but that looks all fine.  I suspect that this is one of those edge cases where it depends on how people implement the spec.  I'll see whether I can reproduce with poppler.

**Comment by ghost** [comment]
@hmenke  OK, so it is not an illusion. I wrote "Other densities seem to come with slightly different offsets (or this is an illusion).". Yes, it might well be that it is imagemagick's fault or something else, meanwhile Symbol 1 also commented to be familiar with this issue. The issue seems to be that the origin of the coordinate system gets decided to be somewhere else in the conversion process. One could just add a remark in the manual. And of course I can file a bug at imagemagick, I haven't done that yet. Seems to be specific to patterns, though.

**Comment by hmenke** [comment]
If I make the pattern a single tile and move the circle onto it, it becomes scale-independent.
```latex
\begin{tikzpicture}
    \path[pattern=neurons] (0,0) rectangle +(2.5mm,2.5mm);
    \draw[red] (1.25mm, 1.25mm) circle[radius=1mm];
\end{tikzpicture}
```
However, replacing `+(2.5mm,2.5mm)` by `+(25mm,25mm)` the shift is back.

**Comment by hmenke** [comment]
Actually, how did you come up with this?
```latex
tile transformation={
    xshift=1.75mm,
    yshift=1.75mm,
},
```

**Comment by ghost** [comment]
@hmenke  Well, I was just playing. From the first example on p. 737 of manual v3.1.5  I took that, since `rotate=\tikzstarrotate` works, other keys will work, too. It could well be that this is not what one should do, but on the pdf it did what it was supposed to do. If the bottomline is that we should not do that, and we add this to the manual, this is a perfectly fine solution.

**Comment by hmenke** [comment]
No, that's not what I mean.  Using transformations is totally fine, but how did you come up with the exact value of `1.75mm`.  Was that just an educated guess or is there some math behind it?

**Comment by ghost** [comment]
@hmenke  No, I was just trying to answer a question [here](https://tex.stackexchange.com/a/541073/194703) and the rationale for the pattern was to speed up the computation time of a code for an animation. Since I had a centered grid already, and in particular some circles that move over the grid, I wanted the pattern circles to match, and the shift was needed to do that. If the question is whether I tried to find out which grid on the tikzpicture the pattern is aligned to, the answer is no (but I think it is aligned w.r.t. to the `(0,0)` of the `tikzpicture`.

**Comment by hmenke** [comment]
No, the pattern is aligned with respect to `(0,0)` of the PDF object that is generated from the TikZ code.

I've also pulled up the [spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G7.3998969) and quickly skimmed through it.  Here are some relevant passages (emphasis is mine)

> A tiling pattern consists of a small graphical figure called a pattern cell. Painting with the pattern replicates the cell  at  fixed  horizontal  and  vertical  intervals  to  fill  an  area.  The  effect  is  as  if  the  figure  were  painted  on  the  surface of a clear glass tile, identical copies of which were then laid down in an array covering the area and trimmed to its boundaries. This process is called tiling the area. 
> 
> The pattern cell can include graphical elements such as filled areas, text, and sampled images. Its shape need not be rectangular, and the spacing of tiles can differ from the dimensions of the cell itself. When performing painting operations such as S (stroke) or f (fill), the conforming reader shall paint the cell on the current page as many times as necessary to fill an area. **The order in which individual tiles (instances of the cell) are painted is unspecified and unpredictable; figures on adjacent tiles should not overlap.**
> 
> The  appearance  of  the  pattern  cell  shall  be  defined  by  a  content  stream  containing  the  painting  operators  needed to paint one instance of the cell. Besides the usual entries common to all streams (see Table 5), this stream’s dictionary may contain the additional entries listed in Table 75.
> 
> The pattern dictionary’s BBox, XStep, and YStep values shall be interpreted in the pattern coordinate system, and the graphics objects in the pattern’s content stream shall be defined with respect to that coordinate system. **The  placement  of  pattern  cells  in  the  tiling  is  based  on  the  location  of  one  key  pattern  cell,  which  is  then  displaced by multiples of XStep and YStep to replicate the pattern.** The origin of the key pattern cell coincides with  the  origin  of  the  pattern  coordinate  system.  The  phase  of  the  tiling  can  be  controlled  by  the  translation  components of the Matrix entry in the pattern dictionary.

I'm not really sure what this implies though and I could also not find out how to set the location of the key pattern tile.

**Comment by ghost** [comment]
@hmenke  Oh WOW, I did not even know that this exists! So are you saying with Ti*k*Z we can just put stuff into the "stream" they are talking about? If so, this would be super great news since it would imply that one could make Ti*k*Z way more versatile w.r.t. 3d than I thought. I was always hoping that the viewer would take care of the 3d ordering but if I read the contents of section **13.6.5Coordinate Systems for 3D** correctly they already are doing it. (I must confess, though, that I do not at all understand everything that is written there, presumably one needs to play with a few examples and also know how pgf output relates to their stream.)

**Comment by hmenke** [comment]
This digresses from the issue at hand.  Also keep in mind that this is the spec for PDF 1.7 but pdfTeX generates PDF 1.4, so these features might actually not be available.  Inserting content into the PDF stream is what `\pdfliteral` does.  All of PGF is implemented in that way.

**Comment by hmenke** [comment]
This seems to be implementation-defined and the original author has deleted their account, so it is unlikely that anymore input will follow here.
