### ISSUE TITLE
ghostscript transparency changes coming

### ISSUE THREAD

**Issue by kberry** [pgf-tikz/pgf#862]
Not exactly a bug, but anyway ...

As you may know, Ghostscript's transparency support has been in flux. GS developer Chris Liddell recently posted a summary of the proposed changes to come (https://ghostscript.com/pipermail/gs-devel/2020-May/010295.html), and Bruno Voisin posted a summary of the history (https://tug.org/pipermail/tex-live/2020-May/045752.html).

With the next gs release (9.53), I guess it would be good for pgf/tikz to support the new operators discussed in the mail, if they are present, since the old ones will disappear in a year or two.

Hope this helps somehow. --best, karl.

**Comment by hmenke** [comment]
Thanks Karl! Yes, I saw the thread on the TeX Live list. I'll have to work out how to do this in a compatible way. I wouldn't want to break old dvips.
