### ISSUE TITLE
[pgfkeys] Obsolete \pgfkeys@ifcsname and use \ifcsname?

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#863]
When reading `pgfkeys.code.tex`, I find the use of `\pgfkeys@ifcsname`. Considering
1. There is already a safe guard in `pgfkeys.code.tex` which requires etex v2.
1. There is one direct use of `\ifcsname` in `pgfkeys.code.tex`.
1. Another etex primitive `\scantokens` is directly used (see https://github.com/pgf-tikz/pgf/commit/187f5f484720100c9cfab49aa90832c2b2fcc6c1) and its wrapped name `\pgfutil@scantokens` is made obsolete.

https://github.com/pgf-tikz/pgf/blob/c8d7d9b82b5dd4374c85bf5538e4d319a811d3ce/tex/generic/pgf/utilities/pgfkeys.code.tex#L30-L46

Can we obsolete `\pgfkeys@ifcsname` and use `\ifcsname` directly and consistently? (I should be confident enough to just open a PR. hmmm)

**Comment by hmenke** [comment]
Using `\ifcsname` everywhere should be fine (probably just forgot that when transitioning to eTeX), `\scantokens` I'd like to avoid whenever possible, because it has too many gotchas.

**Comment by muzimuzhi** [comment]
Thanks.

**Comment by hmenke** [comment]
Feel free to suggest more eTeX optimizations where you see fit.  You can always open a PR.  If you check the backlog, you'll see that most of them got accepted.
