### ISSUE TITLE
Distorted Bend Arrows

### ISSUE THREAD

**Issue by miglincit** [pgf-tikz/pgf#865]
I want to draw a front plate with a volume knob surrounded by a _circular triangle_ getting thicker towards the louder end...  

As this is not easy to achieve I wanted to use a bent arrow head, but this only works up to a length which is not sufficient for my purpose:

- The blue figure shows what I want to draw, but it should circumference ~330° not only 180°.
- The green looks promising, but the arrow is too short.
- The orange is longer but the arrow is no longer what I want to draw...

(Maybe I am torturing the bend arrow function too much?!) 

```latex
\documentclass{article}

  % Any preamble code goes here
\usepackage{tikz}%
\usetikzlibrary{arrows.meta}%
\usetikzlibrary{bending}%
\tikzset{x=1mm,y=1mm}%

\begin{document}

  % Demonstration of issue here
  \begin{figure}%
    \begin{tikzpicture}%
      \draw[blue](30,30)coordinate(A)circle(15);%
      \draw[blue,fill=blue](A)%
        ++(180:16)%
        arc[radius=16, start angle=180, delta angle=-180]%
        -- ++(4,0)%
        arc[radius=18, start angle=0, delta angle=180];%
      %
      \draw[green](70,30)coordinate(B)circle(15);%
      \draw[green,{Triangle[length=20mm,width=5mm,right,bend,]}-]%
        (B)%
        ++(180:16)%
        arc[radius=16, start angle=180, delta angle=-180];%
      %
      \draw[orange](110,30)coordinate(C)circle(15);%
      \draw[orange,{Triangle[length=48mm,width=5mm,right,bend,]}-]%
        (C)%
        ++(180:16)%
        arc[radius=16, start angle=180, delta angle=-180];%
    \end{tikzpicture}%
  \end{figure}%

\end{document}
```

**Comment by hmenke** [comment]
> - The blue figure shows what I want to draw, but it should circumference ~330° not only 180°.

Well you only draw a 180° angle, so I don't see why you expect a 330° angle to magically appear.

> The green looks promising, but the arrow is too short.

No it isn't.  You specified that the arrow be `20mm` in length and that is what it is.

> The orange is longer but the arrow is no longer what I want to draw...

The `bending` library works by applying a nonlinear transformation to the arrow.  To that end the first four points on the curve are used to construct a Bézier curve.  However, you are drawing an arc, so all the first four points are going to lie within the first 90° segment.  Here is a visualization of the Bézier curve that this picked by the `bending` library to construct the transformation, the open circles are the support points.

![test](https://user-images.githubusercontent.com/1903556/83079171-58fef600-a0cf-11ea-885a-a5237e348917.png)

**Comment by miglincit** [comment]
Thanks for the explanation of the usage of Bézier curves.
That means I cannot use that method.

Btw: The blue and green were just example of how I tried to attempt the orange figure - I know they are what I specified, and not what I finally would like to have...
