### ISSUE TITLE
chains library leaves a gap between the nodes and the connecting line with scale & transform shape

### ISSUE THREAD

**Issue by 7Z0t99** [pgf-tikz/pgf#875]
Consider the following example
```latex
\documentclass{standalone}

\usepackage{tikz}
\usetikzlibrary{chains}
\begin{document}
    \begin{tikzpicture}[scale=10,transform shape]
	    \node[start chain,on chain,rectangle,draw]{a};
        \node[on chain,join,rectangle,draw]{b};		
    \end{tikzpicture}
\end{document}
````
Without transform shape, the rectangular nodes are connected by a line (as expected), but with transform shape, there is a gap between the rectangles and the connecting line. 
(Tested with TeX Live 2020 on Windows)

I would be very happy if this could be fixed or if you could maybe tell me a workaround to connect the rectangles.

**Comment by 7Z0t99** [comment]
Oh by the way: connecting the nodes with a `\draw` command instead of using chains' join produces the same picture:
````latex
\documentclass{standalone}

\usepackage{tikz}
\usetikzlibrary{chains}
\begin{document}
    \begin{tikzpicture}[scale=10,transform shape]
	\node(a)[start chain,on chain,rectangle,draw]{a};
	\node(b)[on chain,rectangle,draw]{b};
	\draw(a.east)--(b.west);
    \end{tikzpicture}
\end{document}
````

**Comment by hmenke** [comment]
Has nothing to do with `chains`.
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}[scale=10,transform shape]
    \node[draw] (a) at (0,0) {a};
    \node[draw] (b) at (1,0) {b};
    \draw (a.east) -- (b.west);
\end{tikzpicture}
\end{document}
```

![test](https://user-images.githubusercontent.com/1903556/84835483-d17e2480-b087-11ea-89c1-da892eaa41f3.png)

**Comment by hmenke** [comment]
Also reproducible with pure PGF.
```latex
\documentclass{article}
\usepackage{pgf}
\begin{document}
\begin{pgfpicture}
    \pgftransformscale{10}
    \pgftransformshift{\pgfpointorigin}
    \pgfnode{rectangle}{center}{a}{a}{\pgfusepath{stroke}}
    \pgftransformshift{\pgfqpoint{20pt}{0pt}}
    \pgfnode{rectangle}{center}{b}{b}{\pgfusepath{stroke}}
    \pgfpathmoveto{\pgfpointanchor{a}{east}}
    \pgfpathlineto{\pgfpointanchor{b}{west}}
    \pgfusepath{stroke}
\end{pgfpicture}
\end{document}
```

**Comment by hmenke** [comment]
By default `/pgf/outer xsep=.5\pgflinewidth` and this will be scaled up as well by `scale=10` when `transform shape` is active.  This is the correct behaviour in my opinion, even though it might be a bit unexpected in this situation.  You can offset it by manually unscaling the the `outer xsep`.  Not a bug.
```latex
\documentclass{standalone}

\usepackage{tikz}
\usetikzlibrary{chains}
\begin{document}
    \begin{tikzpicture}[scale=10,outer xsep=.5\pgflinewidth/10,transform shape]
        \node[start chain,on chain,rectangle,draw]{a};
        \node[on chain,join,rectangle,draw]{b};		
    \end{tikzpicture}
\end{document}
```

**Comment by 7Z0t99** [comment]
Thank you very much for showing me that `outer sep` needs to me adjusted manually with scaling. 
I have found in the manual that there is even an option does this automatically: `outer sep=auto`. To be honest I wouldn't call it correct behaviour that `outer sep` is scaled, but the line width isn't. Even the manual says that it is a good idea to use `auto`, but that it is not the default mainly for compatibility. Maybe making `outer sep=auto` the default is something you could add to #869 .
