### ISSUE TITLE
Text alignment of nodes on paths for dvisvgm driver

### ISSUE THREAD

**Issue by Excentertex** [pgf-tikz/pgf#880]
When placing a node on a path, something is wrong with the alignment. In the MWE below, it can be seen that the text is NOT centered along the line and extra space is unevenly added between the letters. This problem does not occur with the pdf driver. Several values for font size and alignment, and multiple viewers (Chromium, Inkscape) present the problem.

```latex
\documentclass[dvisvgm]{article}

\usepackage{tikz}

\begin{document}
\begin{tikzpicture}
  \draw (0,0) -- node[above,pos=.5,align=center,font=\tiny] {Testtesttest} (2,0);
\end{tikzpicture}
\end{document}
```

Attached: screenshot (from Chromium).

![Screenshot_20200617_222321](https://user-images.githubusercontent.com/3968577/84946535-2900ac80-b0e9-11ea-8364-bd310d9b7367.png)

**Comment by Mo-Gul** [comment]
Thank you for the report. Would you mind adding an image as well? That way it is clearly visible -- also to others -- what exactly the problem is.

**Comment by hmenke** [comment]
That is a rendering problem.  If you use
```
dvisvgm --font-format=woff test.dvi
```
it shows up correctly (and also with the correct fonts).

![test](https://user-images.githubusercontent.com/1903556/84956067-8a0d9c00-b14c-11ea-873a-315884027237.png)

**Comment by hmenke** [comment]
Just to corroborate that this is not a problem in PGF, try running this
```latex
\documentclass{article}
\begin{document}
\tiny Testtesttest
\end{document}
```
with
```
pdflatex --output-format=dvi test.tex && dvisvgm test.dvi
```

![test](https://user-images.githubusercontent.com/1903556/84956523-862e4980-b14d-11ea-8856-b8d3851bb7f0.png)
