### ISSUE TITLE
[manual] (some) page link destinations seem to be wrong

### ISSUE THREAD

**Issue by Mo-Gul** [pgf-tikz/pgf#885]
I am not 100% sure that this is an TikZ issue. At least in the latest manual (v3.1.5b and current master) some page link destinations seem to be wrong. One example is the link in the first paragraph on page 89

> ... see page 778 for an example).

The number of the destination is correct, but when one clicks on the link one lands "Shading `axis` > `/tikz/top color` > item 4" on page 777 instead of at "Shading `color wheel`" which is indeed on page 778. If it helps, I could add more examples.

The same applies to the PGFPlots manual. Here as an example the page link on page 51

> Please see page 109 ...

jumps to "Section 4.5.12 Scatter Plots" on page 107 instead of to the key `/pgfplots/scatter src` (on indeed page 109).

**Comment by muzimuzhi** [comment]
An attempt:
```diff
diff --git a/doc/generic/pgf/text-en/pgfmanual-en-library-shadings.tex b/doc/generic/pgf/text-en/pgfmanual-en-library-shadings.tex
index a8076563..85c9ab0f 100644
--- a/doc/generic/pgf/text-en/pgfmanual-en-library-shadings.tex
+++ b/doc/generic/pgf/text-en/pgfmanual-en-library-shadings.tex
@@ -134,7 +134,6 @@ this library is not used.
 \end{shading}

 \begin{shading}{color wheel}
-\label{shading-color-wheel}%
     This shading fills the path with a color wheel.
     %
 \begin{codeexample}[preamble={\usepgflibrary{shadings}}]
diff --git a/doc/generic/pgf/text-en/pgfmanual-en-tutorial-map.tex b/doc/generic/pgf/text-en/pgfmanual-en-tutorial-map.tex
index 4c895031..0a609e19 100644
--- a/doc/generic/pgf/text-en/pgfmanual-en-tutorial-map.tex
+++ b/doc/generic/pgf/text-en/pgfmanual-en-tutorial-map.tex
@@ -870,7 +870,7 @@ that is blue in the lower right direction and then changes smoothly to orange
 in the upper right direction and then to green in the upper left direction and
 so on. Unfortunately, there is no easy way of creating such a color wheel
 shading (although it can be done, in principle, but only at a very high cost,
-see page~\pageref{shading-color-wheel} for an example).
+see shading~|color wheel| for an example).

 Johannes decides to do something a bit more basic: He creates four large
 rectangles, one for each of the four quadrants around the central concept, each
```

### Long explanation
The source code of output
> .. see page 778 for an example).

is
https://github.com/pgf-tikz/pgf/blob/df4959a7dc3b6a647f6c28159db83f73dc994ba9/doc/generic/pgf/text-en/pgfmanual-en-tutorial-map.tex#L871-L873
And this label is defined in
https://github.com/pgf-tikz/pgf/blob/df4959a7dc3b6a647f6c28159db83f73dc994ba9/doc/generic/pgf/text-en/pgfmanual-en-library-shadings.tex#L136-L152

However, `shading` environment does not step any counters, hence cannot be labeled. So the `\label{shading-color-wheel}` stores info of last stepped counter, which is a list item.
https://github.com/pgf-tikz/pgf/blob/df4959a7dc3b6a647f6c28159db83f73dc994ba9/doc/generic/pgf/macros/pgfmanual-en-macros.tex#L521-L532

`shading` calls `\pgfmanualpdflabel{#1}{}` to support auto hyperlinks input as `|<#1>|`, here `#1 == color wheel`. Therefore I change `\pageref{...}` to `shading~|color wheel|` and delete the `\label` used inside `shading` environment.

### Discussion
If the `\pageref` output is preferred, one can add a dummy counter and step it inside `shading` (and similar) environment(s) to support `\label-\ref` scheme.

In my current attempt, one need to check if there are more similar situations. In the dummy counter method, similar problems will be solved at once.

**Comment by muzimuzhi** [comment]
> The same applies to the PGFPlots manual. Here as an example the page link on page 51
> 
> > Please see page 109 ...
> 
> jumps to "Section 4.5.12 Scatter Plots" on page 107 instead of to the key `/pgfplots/scatter src` (on indeed page 109).

The above explanation holds for `pgfplots`, except `pgfplots` uses more `\pageref` to wrongly labeled labels.
```
$ grep -rni 'key:restrict:x:to:domain' .
./pgfplots.reference.coordfiltering.tex:356:\label{key:restrict:x:to:domain}
./pgfplots.install.tex:215:        page~\pageref{key:restrict:x:to:domain} for details).
./pgfplots.reference.2dplots.tex:2804:    page~\pageref{key:restrict:x:to:domain}.

$ grep -rni 'pgfplots:scatter:src' .
./pgfplots.reference.markers-meta.tex:3713:    for |scatter src| on page~\pageref{pgfplots:scatter:src} covers the same
./pgfplots.reference.axis-addplot.tex:643:        |scatter src|, see page~\pageref{pgfplots:scatter:src}) as has been
./pgfplots.reference.axis-addplot.tex:807:    page~\pageref{pgfplots:scatter:src} for details about meta data or the
./pgfplots.reference.axis-addplot.tex:2550:    element which is read. See page~\pageref{pgfplots:scatter:src} for
./pgfplots.reference.2dplots.tex:1946:\label{pgfplots:scatter:src}
```

Now the dummy counter method looks more attractive.

**Comment by muzimuzhi** [comment]
(sorry for my continuous self-talking comments)

A simple `grep` shows there are ~30 wrongly labeled labels like `\label{shading-color-wheel}` in source code of pgfmanual, and the number doubles in source code of pgfplots manual. 

```
# test under macOS
# for pgf
grep -rni '\\label{' doc/**/*.tex | grep -ve '\\label{\(section\|pgfmath\|sec:\|LPPL:\)'
# for pgfplots
grep -rni '\\label{' doc/**/*.tex | grep -ve '\\label{\(section\|sec:\|pgfplots:sec:\)'
```
