### ISSUE TITLE
Unexpected position shift when using `blend group` with XeLaTeX

### ISSUE THREAD

**Issue by Mikumikunisiteageru** [pgf-tikz/pgf#888]
Hello friends,

I found a bug in the package, when I use `blend group` with XeLaTeX, as in the following code:

```latex
\documentclass[tikz]{standalone}
\begin{document}
\tikz[blend group=normal]
	\node[draw=black] {};
\end{document}
```

I got a PDF output successfully, and the page size was exactly as the box generated by `\node`. But the problem was, the box was unexpectly shifted a little bit to the left, so part of the left line exceeded the left edge of the page, while a blank strip occured between the right line of the frame and the right edge of the page. In fact, when there are other elements on the page, whether in the scope of Ti*k*Z or not, will be shifted together.

I am sure that this is not an issue of PDF rendering, as I tried some PDF readers and all of them showed me the same image. Another evidence was that a shifted PDF could be `\includegraphics`ed into another one, but the latter one would not get infected. By the way, PDFLaTeX was okay.

So why is there such a strange bug, and is there any way to get rid of it if one sticks to XeLaTeX?

**Comment by hmenke** [comment]
Just some little `pt` vs `bp` confusion.  Possible patch:
```patch
diff --git a/tex/generic/pgf/systemlayer/pgfsys-dvipdfmx.def b/tex/generic/pgf/systemlayer/pgfsys-dvipdfmx.def
index b5779bea..f9c5f79a 100644
--- a/tex/generic/pgf/systemlayer/pgfsys-dvipdfmx.def
+++ b/tex/generic/pgf/systemlayer/pgfsys-dvipdfmx.def
@@ -450,6 +450,7 @@
 % Transparency groups came from pgfsys-pdftex.def
 \def\pgfsys@transparencygroupfrombox#1{%
   {%
+    \pgfutil@tempdima=\pgf@picminx
     \pgf@sys@bp@correct\pgf@picminx%
     \pgf@sys@bp@correct\pgf@picmaxx%
     \pgf@sys@bp@correct\pgf@picminy%
@@ -459,7 +460,7 @@
       \wd#1=0pt%
       \ht#1=0pt%
       \dp#1=0pt%
-      \hskip\pgf@picminx bp\box#1\hskip-\pgf@picminx bp%
+      \hskip\pgfutil@tempdima\box#1\hskip-\pgfutil@tempdima%
       \special{pdf:put @resources
       <<
         \ifpgf@sys@pdf@extgs@exists /ExtGState @pgfextgs \fi
```
