### ISSUE TITLE
Make manuals of pgf & pgfplots share common macro settings

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#891]
When resolving #855 and https://github.com/pgf-tikz/pgfplots/issues/362, it comes out that making both repositories aware of a set of common manual macro would be helpful.

> _from https://github.com/pgf-tikz/pgfplots/issues/362#issuecomment-650940691, by @hmenke_
> PGF should probably install `pgfmanual-en-macros.tex` somewhere where `kpathsea` can find it. That would cut down on all the duplication by packages that also use the manual macro and copied the file into their source tree.

Currently, `pgf` and `pgfplots` holds their own `pgfmanual-en-macros.tex`, and those two copies are very different.

> _from https://github.com/pgf-tikz/pgfplots/issues/362#issuecomment-650980500, by @muzimuzhi_
> An interesting finding: `pgf`'s `pgfmanual-en-macros.tex` is almost twice as long as `pgfplots`'s, so considerable work is required to split them into pgfmanual-common macro file and pgf repo specific macro files. Or, even create a new small package?
> 
> * https://github.com/pgf-tikz/pgfplots/blob/master/doc/latex/pgfplots/pgfmanual-en-macros.tex, 1032 lines
> * https://github.com/pgf-tikz/pgf/blob/master/doc/generic/pgf/macros/pgfmanual-en-macros.tex, 1911 lines

But both of them loads `pgfmanual` package, which is only hosted by `pgf`.

> _from https://github.com/pgf-tikz/pgfplots/issues/362#issuecomment-651391492, by @muzimuzhi_
> I find that `pgf` has a `pgfmanual` (sub-)package. See its corresponding directory in `pgf` repo here: https://github.com/pgf-tikz/pgf/tree/master/tex/latex/pgf/doc. `pgfplots` doesn't host its own copy, instead it loads it
>
> https://github.com/pgf-tikz/pgfplots/blob/d85789248e5c0352ea0ec9349914e5ae87c8a0b1/doc/latex/pgfplots/pgfplots-macros.tex#L4-L22
> 
> Maybe we can gradually move more common manual macros into `pgfmanual` package, and even maintain it in separate repo for easier dependency management.

To express my suggestion, by repeating my last sentence in the referred comment:
> Maybe we can gradually move more common manual macros into `pgfmanual` package, and even maintain it in separate repo for easier dependency management.

**Comment by hmenke** [comment]
I've moved the `pgfmanual-en-macros.tex` into the texmf tree in https://github.com/pgf-tikz/pgf/commit/a9818b15a158f15a15cffcf7907c26f3f487005e, so that it can be discovered by `kpathsea`, so from the PGF side this is fixed.
