### ISSUE TITLE
A few minor typos in the manual

### ISSUE THREAD

**Issue by arunisaac** [pgf-tikz/pgf#894]
Hi,

I found the following minor typos in the manual.

Version: 3.1.5b
- first paragraph of page 37: "[scale=3" -> "[scale=3]"
- the paragraph before the last one in section 81.1 (page 854): "if you only need to provide" -> "you only need to provide"
- page 901: should it be "/tikz/data visualization/tick typesetter=<value>", instead of ".../tick typesetting=<value>"?
- page 904: 7 instances of "mayor" -> "major"

Thanks!

**Comment by Mo-Gul** [comment]
Good catches. Thank you very much for reporting!
(For the record: The first one was already fixed in an earlier commit and was a parser issue instead of a typo.)
