### ISSUE TITLE
Archive old manuals?

### ISSUE THREAD

**Issue by AndreC75** [pgf-tikz/pgf#903]
TikZ has a long history which is reflected in the documentation. 

Some lines of code from the latest manuals are no longer documented, see for example, this question about `-to` [What do “-to” and “pre=moveto” do in TikZ arrows?](https://tex.stackexchange.com/q/555655/138900)
or this one about intersection [Specifying the point via “intersection of” in TikZ - a problem](https://tex.stackexchange.com/q/290502/138900)

Various old manuals are still available online. But there is no guarantee that they will remain online.  Can the main versions of these manuals be archived here?

TikZ 1.01 [TikZ and pgf Manual for Version 1.01](http://deptinfo.unice.fr/~carine/UEL/pgfmanual.pdf)
tikz 1.18 [TikZ and pgf Manual for version 1.18](http://math.bme.hu/~morap/informatika1-2007/pgfmanual.pdf)
tikz 2.10 : [Manual for Version 2.10–cvs](https://texample.net/media/pgf/builds/pgfmanualCVS2012-11-04.pdf)
TikZ 3.0.1a [Manual for Version 3.0.1a](http://www.ict.nsc.ru/xmlui/handle/ICT/1487)

I apologize if I formatted the text incorrectly.

**Comment by hmenke** [comment]
Just compile the old sources.

**Comment by AndreC75** [comment]
In this case, can you indicate the procedure to follow and answer this question since this user has not been able to compile the sources to obtain the manual: [Compiling Tikz-PGF Manual](https://tex.stackexchange.com/q/455755/138900)

**Comment by hmenke** [comment]
No, you have to find out by yourself.  Generally to compile old manuals you have to install the corresponding version of PGF, then go to `doc/generic/pgf/version-for-<engine>/en` and type `make`, which only works on a Linux system (and maybe on macOS).

However, you can also just access the old versions of the manuals that were shipped with TeX Live.  All PGF updates that were pushed to TeX Live are available in their SVN repo.  This only goes back to 2.00 though.

https://tug.org/svn/texlive/trunk/Master/texmf-dist/doc/generic/pgf/pgfmanual.pdf?view=log

**Comment by AndreC75** [comment]
How do I install pgf version 1.01 on MikTeX?

**Comment by hmenke** [comment]
https://miktex.org/help

**Comment by muzimuzhi** [comment]
> However, you can also just access the old versions of the manuals that were shipped with TeX Live. All PGF updates that were pushed to TeX Live are available in their SVN repo. This only goes back to 2.00 though.
> 
> https://tug.org/svn/texlive/trunk/Master/texmf-dist/doc/generic/pgf/pgfmanual.pdf?view=log

`pgfmanual.pdf` prior to 2.00 is located in another path (since texlive [revision 6471](https://tug.org/svn/texlive?view=revision&revision=6741)), see
https://tug.org/svn/texlive/trunk/Master/texmf-dist/doc/generic/pgf/version-for-pdftex/en/pgfmanual.pdf?view=log&pathrev=6740.

Follow the above link, the first version of `pgfmanual.pdf` contained in texlive is `pgfmanual.pdf` 1.00, which is added by texlive [revision 85](https://tug.org/svn/texlive?limit_changes=0&view=revision&revision=85) and is downloadable from [this link](https://tug.org/svn/texlive/trunk/Master/texmf-dist/doc/generic/pgf/version-for-pdftex/en/pgfmanual.pdf\?revision\=85\&view\=co\&pathrev\=85).

**Comment by muzimuzhi** [comment]
Or, you can find all release versions not newer than 3.1.1, including the 0.9x pre-releases in `pgf`'s sourceforge home
https://sourceforge.net/projects/pgf/files/pgf/, in form of `.tar.gz` files. These `.tar.gz` files contain full source code and user manual, and has TDS structure.

**Comment by AndreC75** [comment]
@muzimuzhi  Ah yes, they are all there and compiled! You are a gold mine!

**Comment by hmenke** [comment]
Ah, good call, mate.
Cheers.

**Comment by AndreC75** [comment]
@muzimuzhi    Can you explain this on tex.stackexchange chat? [chat rooms/41/tex-latex-and-friends](https://chat.stackexchange.com/transcript/message/55129532#55129532)

**Comment by AndreC75** [comment]
@muzimuzhi there is still `-to` in page 1076 `\begin{pgfpicture}
\begin{pgfscope}
{
\pgfsetarrows{-to}
\pgfpathmoveto{\pgfpointorigin}\pgfpathlineto{\pgfpoint{2ex}{2ex}}
\pgfusepath{stroke}
}
\pgfpathmoveto{\pgfpoint{3ex}{0ex}}\pgfpathlineto{\pgfpoint{5ex}{2ex}}
\pgfusepath{stroke}
\end{pgfscope}
\pgfpathmoveto{\pgfpoint{6ex}{0ex}}\pgfpathlineto{\pgfpoint{8ex}{2ex}}
\pgfusepath{stroke}
\end{pgfpicture}`
