### ISSUE TITLE
Description of `\pgfqkeys` is misleading.

### ISSUE THREAD

**Issue by Skillmon** [pgf-tikz/pgf#904]
Version: 3.1.5b

On page 978, the description of `\pgfqkeys` is suboptimal. `\pgfqkeys{foo}{bar=baz}` doesn't have the same effect as `\pgfkeys{foo/.cd,bar=baz}`, instead it should be `\pgfqkeys{/foo}{bar=baz}`.

**Comment by ilayn** [comment]
`foo` is not a path. Read end of 975 and start of 976.

**Comment by Skillmon** [comment]
After I had some discussion about this elsewhere, I want to further narrow down my reasoning for this issue.

According to the `pgfmanual` a key can be given as a full key or a partial key and the two words "path" and "key" have more or less the same meaning for the most part of it (*e.g.*, `/tikz/coordinate system/x` is a key, just as `/tikz`, which is also called a path on the same page). For this reason, I'd alter the documentation of `\pgfqkeys` to include the information that the first argument has to be a full path (so with a leading `/`) and not a relative/partial path.
