### ISSUE TITLE
Documente arrow tips defined in pgfcorearrows.code.tex?

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#906]
Version: 3.1.5b

As mentioned in https://github.com/pgf-tikz/pgf/pull/746#issuecomment-531585663 by @Mo-Gul in Sep 2019, there are several undocumented arrow tips defined in auto-loaded [`pgfcorearrows.code.tex`](https://github.com/pgf-tikz/pgf/blob/master/tex/generic/pgf/basiclayer/pgfcorearrows.code.tex). For example, in LaTeX format, `pgfcorearrows.code.tex` is loaded by
```
tikz.sty
└── pgf.sty
    └── pgfcore.sty
        └── pgfcore.code.tex
            └── pgfcorearrows.code.tex
```
For (unanswered) questions Mo-Gul posted in https://github.com/pgf-tikz/pgf/pull/746#issuecomment-531585663,
> Shall somewhere stated (again) that there are these default arrow tips? And if yes, should they be redefined to the sizes of the arrows.meta tips? I personally would prefer that but of course for backward compatibility reasons that would be an issue.

My answer is yes to the first question and no to the second.

Related: https://github.com/pgf-tikz/pgf/pull/905#issuecomment-667691485

**Comment by muzimuzhi** [comment]
- Most of them are commented out from pgfmanual in https://github.com/pgf-tikz/pgf/commit/aa5d94b532b69a7d3e7a09e6b014b5dad38d35dc by tantau in Oct 2013. For example, arrow tips `to`, `latex`, and `stealth`. 
 - Arrow tip `|` defined by `\pgfkeys{| /.tip = {Bar}}` seems not belong to this type.

**Comment by hmenke** [comment]
Since Till commented out the docs I'm just going to leave it at that.  There must have been a reason.
