### ISSUE TITLE
Space in pgfmathdeclarefunction shifts plots to the right.

### ISSUE THREAD

**Issue by clecap** [pgf-tikz/pgf#915]
There already is an overview and analysis of this on stackexchange, together with minimal example.

The title may be a bit misleading, as the core problem is most likely not connected with the samples parameter but with blanks in the function declaration. See:

https://tex.stackexchange.com/questions/561108/tikz-issue-with-samples-parameter-minimal-example

**Comment by hmenke** [comment]
1. This issue is in an invalid format because every issue MUST include a MWE.  Is there something wrong with using the issue tenplate?

2. It's an exact duplicate of #508.  Search exisiting issues before opening a new one.

3. It won't be fixed because it breaks usage of pgfkeys in functions which many clients rely on.  Just fix your definition.

**Comment by clecap** [comment]
> 1. This issue is in an invalid format because every issue MUST include a MWE.  

As are issues 869, 900, 908, 904. ;-)

> Is there something wrong with using the issue tenplate?

Basically not. Unless you want to learn about all issues, bugs and problems. And sometimes there are reasons why submitters do not follow strict templates. Such as not being sure about having a bug or having the same information already at a different place. But maybe linking to info somewhere else is not ok as well?

> 2. It's an exact duplicate of #508.  Search exisiting issues before opening a new one.

No, it's not. If you read the linked source and the edits there you will see that the issue started out from a completely different observation and only later evolved into something similar. 

> 3. It won't be fixed because it breaks usage of pgfkeys in functions which many clients rely on.  Just fix your definition.

Sometimes design decisions in the past were wrong or only over time are understood to have been inconvenient. They may affect future development in so far that a modification breaks code that is relied upon. There are pathways out of this dilemma using versioning and renaming. They can be applied here. And, I think, they should.

Yes, TeX has a peculiar way of dealing with blanks. This makes life complicated for package developers. But, from the users perspective, there is no good reason why a blank in a function definition at some place in the code should end up shifting layout positions at a completely different place in the code - and depend highly on the `samples` parameter as well. Well...unless you like surprises, of course. If you have nested definitions and high values of `samples' it can shift the diagram completely off the screen. I consider this a problem. But we can disagree on that :-)

**Comment by hmenke** [comment]
Please don't ever report an issue again, thanks.
