### ISSUE TITLE
"Lines" pattern from patterns.meta is broken in latest Tikz update

### ISSUE THREAD

**Issue by matthiastummers** [pgf-tikz/pgf#917]
**Brief outline of the bug**

Recently the pattern "Lines" from the tikz library patterns.meta started producing the following bug:
```
... Package pgf Error: Undefined pattern `Lines'. ...
```
resulting in the pattern not being displayed.

It worked perfectly before.

**Minimal working example (MWE)**

```latex
\documentclass{article}

\usepackage{tikz}
	\usetikzlibrary{patterns.meta}

\begin{document}

\begin{tikzpicture}
  \draw[pattern={Lines[yshift=.5pt]},pattern color=blue]
    (0,0) rectangle +(1,1);
\end{tikzpicture}

\end{document}
```

**Comment by muzimuzhi** [comment]
Your example works well here, using tikz 3.1.5b released in Jan 2020. Which version do you use?

**Comment by hmenke** [comment]
Works fine here as well.  Please transfer this issue to the TeX distribution you are using.  Clearly something must be wrong with their packaging or how you updated your system.

**Comment by matthiastummers** [comment]
Thanks for checking, indeed (my bad), my pgf package was not up to date. Only strange it worked before ... Anyways, everything is ok now. Thanks again ! Matt
