### ISSUE TITLE
Key handler ".expand two once" is buggy and not documented

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#918]
**Brief outline of the bug**
Interred from its handler name and the implementation, `.expand two once` should 
 1. accept two mandatory arguments (like `.code 2 args` does), 
 1. expand each of them once, and finally
 1. call the resulting `<rst1>` and `<rst2>` as if user had written `<key>=<rst1><rst2>`. (Or, should it eventually call `<key>={<rst1>}{<rst2>}`? This would make it incompatible with `.initial`.)

But the [current implementation](https://github.com/pgf-tikz/pgf/blob/908db0011cc96b4092b45de7d432e3ead32f4323/tex/generic/pgf/utilities/pgfkeys.code.tex#L970) 
 - always leaves its second argument in the input stream and
 - even buggier when its first argument contains multiple tokens.

See the implementation with manually adjusted indent:
```tex
\pgfkeys{/handlers/.expand two once/.code 2 args=%
  \expandafter\expandafter\expandafter\pgfkeys@exp@call
  \expandafter\expandafter\expandafter{%
  \expandafter#1\expandafter}\expandafter{#2}%
}
\long\def\pgfkeys@exp@call#1{\pgfkeysalso{\pgfkeyscurrentpath={#1}}}
```
(Noted `\pgfkeys@exp@call` is given two arguments, but it accepts/absorbs only one.)

This handler was added since pgf 3.0.0 (released in 2013), by https://github.com/pgf-tikz/pgf/commit/9f5c89d750057dd3ba63d37eaf9c9a8ee7b21047 and https://github.com/pgf-tikz/pgf/commit/356fbcf4bca31a367ebde356af7beb861c18737b. And it was never modified since then.

**Minimal working example (MWE)**

Adapted from the code example under documentation of handler `.expand once`.
```latex
\documentclass{article}
\usepackage{pgfkeys}

\begin{document}
\def\a{bottom}
\def\b{\a}
\def\c{\b}

\pgfkeys{/key/.initial/.expand two once=\c\c}

\def\a{{\ttfamily\string\a}}
\def\b{{\ttfamily\string\b}}
\def\c{{\ttfamily\string\c}}

\verb|/key|: \pgfkeys{/key}
\end{document}
```

Expected output: 
`\pgfkeys{/key/.initial/.expand two once=\c\c}` outputs nothing, and `\pgfkeys{/key}` outputs `\b\b`.

Actual output:
`\pgfkeys{/key/.initial/.expand two once=\c\c}` outputs `bottom`, and `\pgfkeys{/key}` outputs `\b`.

**Suggestions**

I doubt if `.expand two once` is ever used. For maximum backward compatibility, it can be changed to
```tex
\pgfkeys{/handlers/.expand two once/.code 2 args=%
  \toks0\expandafter{#1}%
  \toks1\expandafter{#2}%
  \edef\pgfkeys@temp{\the\toks0 \the\toks1 }%
  \expandafter\pgfkeys@exp@call\expandafter{\pgfkeys@temp}%
}
```

When pgf adopts use of `\expanded` in the future, it can also be defined without using any token lists (seems trickier, does it?),
```tex
\pgfkeys{/handlers/.expand two once/.code 2 args=%
  \expandafter\pgfkeys@exp@call\expandafter{\expanded{%
      \expandafter\unexpanded\expandafter{#1}%
      \expandafter\unexpanded\expandafter{#1}%
  }}%
}
```

**Comment by muzimuzhi** [comment]
Still not sure if `.expand two once` should be simply commented out or fixed & documented.

**Comment by hmenke** [comment]
> I doubt if .expand two once is ever used. For maximum backward compatibility, it can be changed to

Nah, just check whether there is any occurrence in TeX Live and if there isn't just get rid of it.  As it's broken since the beginning I don't think anyone uses it.
