### ISSUE TITLE
error if dollar sign has not the expected catcode

### ISSUE THREAD

**Issue by u-fischer** [pgf-tikz/pgf#927]
tikz tests with `\tikz@ensure@dollar@catcode` if `$` has catcode 3 and errors if not. 

The problem is that it also errors if a different catcode doesn't matter, either because the picture doesn't use a `$`, or because the content of tikzpicture has been tokenized earlier and store for example in a command. 

One problematic case is if the picture is used in the output routine, for example in the header or in a background picture. If the output routine has been called in the middle of a verbatim or listing the catcode of `$` will  be 12. 

This happens quite regularly as a search on tex.sx shows:

https://tex.stackexchange.com/search?q=redefined+the+meaning+of+the+math-mode+dollar+sign

Imho tikz should either degrade the error to a warning, or offer an option "dont-check-math-dollar-catcode". 

The following example errors, but the calc coordinate works fine:

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{calc}
\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{\tikz\draw(0,0)rectangle ($(0.1,0.1) + (3,1)$); }
\begin{document}
\vspace*{40\baselineskip}
\begin{verbatim}
foo

bar

x

x
\end{verbatim}
\end{document}

```

**Comment by hmenke** [comment]
I wonder why the catcode of $ is important for TikZ anyway, because it is obviously not used as a math shift (unlike & which actually *is* used as an alignment tab).

**Comment by hmenke** [comment]
Ah, it's used as a delimiter, so the catcode has to match.

https://github.com/pgf-tikz/pgf/blob/c6df959df719f39fd49c5fc955597ced74a48bd6/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarycalc.code.tex#L95-L133

**Comment by u-fischer** [comment]
yes, something like ``{\catcode`\$=12 \tikz\draw(0,0)rectangle ($(0.1,0.1) + (3,1)$); }
``  would really break. But on the other side: other catcode changes would break tikz too, e.g. ``\catcode`\; =11``, so it is not quite clear why tikz checks only this one.

**Comment by muzimuzhi** [comment]
> Ah, it's used as a delimiter, so the catcode has to match.

Also https://github.com/pgf-tikz/pgf/blob/c6df959df719f39fd49c5fc955597ced74a48bd6/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex#L5290-L5295

> But on the other side: other catcode changes would break tikz too, e.g. `` \catcode`\; =11 ``, so it is not quite clear why tikz checks only this one.

The check `\tikz@ensure@dollar@catcode` is added by https://github.com/pgf-tikz/pgf/commit/f5d046d2eb28122d8d46e267a414c3fbed423fbe in response to https://tex.stackexchange.com/a/99563, a compatibility issue between `tikz` and `onlyamsmath` (which changes catcode of `$`).

Since `\pgfutil@ifnextchar` is commonly used, `pgf/tikz` actually relies on catcode of many tokens.
