### ISSUE TITLE
pgf shadings issue on latex-dev + dvipdfmx

### ISSUE THREAD

**Issue by aminophen** [pgf-tikz/pgf#928]
## Brief outline of the bug

Today I got an update "pgf 2020-09-28 v3.1.6" from TeX Live (assuming #900 is fixed), but "shadings" library is still not working as expected on latex-dev + dvipdfmx.

## Minimal working example (MWE)

``` tex
\ifnum\ifx\pdfoutput\undefined0\else\pdfoutput\fi=1\relax
  \documentclass[pdftex]{article}
\else
  \documentclass[dvipdfmx]{article}
\fi

\setlength\columnseprule{.4pt}
\pagestyle{empty}
\usepackage{tikz}

\usetikzlibrary{shadings}

\begin{document}

\begin{tikzpicture}
 \node[circle,%
   shading=radial,%
   outer color=blue!30,%
   inner color=white,%
   minimum width=10cm]
  {Test};
\end{tikzpicture}

\end{document}
```

## Output

This is obtained with "pdflatex", "pdflatex-dev", and "latex + dvipdfmx".

<img src="https://user-images.githubusercontent.com/9957466/94548012-0c991200-028b-11eb-96ad-a4fa68a38958.png" width="400px">

This is unexpectedly obtained with "latex-dev + dvipdfmx".

<img src="https://user-images.githubusercontent.com/9957466/94547984-0014b980-028b-11eb-8405-29ae0c96a384.png" width="400px">

----

More examples and logs are available in: [20200929-shadings.zip](https://github.com/pgf-tikz/pgf/files/5298325/20200929-shadings.zip).  Thank you in advance.

**Comment by hmenke** [comment]
@u-fischer

**Comment by u-fischer** [comment]
Hm. The shading is there, but the bbox of the xobject is shifted. The shading uses `\pgfutil@insertatbegincurrentpagefrombox` and this must be adapted (I'm not sure why the factor 2 is needed):

```latex
% tested with xelatex
\documentclass{article}
\setlength\columnseprule{.4pt}
\pagestyle{empty}
\usepackage{tikz}

\usetikzlibrary{shadings}

\makeatletter
\hoffset=2cm  % only for test

\def\pgfutil@insertatbegincurrentpagefrombox#1{%
  \edef\pgf@temp{\the\wd\pgfutil@abb}%
  \global\setbox\pgfutil@abb\hbox{%
    \unhbox\pgfutil@abb%
    %
    % the order in which \pgfutil@insertatbegincurrentpagefrombox
    % matters unless we make the following -shift!
    % To see this, consider writing two such statements. The second
    % one will (naturally) be placed more to the right, although there
    % is no apparent reason why it should.
    %
    % CF observed problems when placing patterns in XObjects without
    % this skip (dvipdfmx driver for pgfplots shader=interp)
    \hskip\dimexpr2in-2\hoffset-\pgf@temp\relax% changed
    #1%
    \hskip\dimexpr-2in-2\hoffset\relax% new
  }%
}
\makeatother
\begin{document}
%\tracingmacros=1
\showoutput

\begin{tikzpicture}
  \shade[draw,shading=radial,%
   outer color=blue!30,%
   inner color=white] (0,0) rectangle (5,5);
\end{tikzpicture}%
\begin{tikzpicture}
  \shade[draw,shading=radial,%
   outer color=blue!30,%
   inner color=red] (0,0) rectangle (5,5);
\end{tikzpicture}%

\begin{tikzpicture}
 \node[circle,%
   shading=radial,%
   outer color=yellow!30,%
   inner color=white,%
   minimum width=10cm]
  {Test};
\end{tikzpicture}

\end{document}
```

But  I don't quite understand why (x)dvipdfmx use this `\pgfutil@insertatbegincurrentpagefrombox`. The default default definition from `pdfsys-common-pdf-via-dvi` which uses `\pgfutil@insertatbegincurrentpage` seems to work fine too:

```latex
\documentclass{article}
\setlength\columnseprule{.4pt}
\pagestyle{empty}
\usepackage{tikz}

\usetikzlibrary{shadings}

\makeatletter
%\hoffset=2cm  % only for test

\def\pgfsys@radialshading#1#2#3{%
  {%
    \pgf@parsefunc{#3}%
    \pgf@process{#2}%
    \pgf@xa=\pgf@x%
    \pgf@ya=\pgf@y%
    \pgf@process{\pgfpoint{\pgf@max}{\pgf@max}}%
    \advance\pgf@xa by \pgf@x\relax%
    \advance\pgf@ya by \pgf@y\relax%
    \pgf@sys@bp@correct{\pgf@x}%
    \pgf@sys@bp@correct{\pgf@y}%
    \pgf@sys@bp@correct{\pgf@xa}%
    \pgf@sys@bp@correct{\pgf@ya}%
    \pgfutil@tempdima=2\pgf@max\relax%
    \edef\@temp{\noexpand\pgfutil@insertatbegincurrentpage{\special{pdf: beginxobj @pgfshade\the\pgfsys@objnum\space width \the\pgfutil@tempdima\space height \the\pgfutil@tempdima}}}\@temp%
    \edef\@temp{\noexpand\pgfutil@insertatbegincurrentpage{\special{pdf: put @resources <<
      /Shading << /Sh << /ShadingType 3
      /ColorSpace \pgf@shading@device\space
      /Domain [\pgf@pdfparseddomain]
      /Coords [\pgf@sys@tonumber{\pgf@xa} \pgf@sys@tonumber{\pgf@ya} \pgf@doma\space \pgf@sys@tonumber{\pgf@x} \pgf@sys@tonumber{\pgf@y} \pgf@domb]
      /Function \pgf@pdfparsedfunction
      /Extend [true false] >> >> >>}}}\@temp% <<
      \pgfutil@insertatbegincurrentpage{\special{pdf: content /Sh sh}%
      \special{pdf: endxobj}}%
    \xdef\pgfutil@tempa{%
      \hbox to\the\pgfutil@tempdima{\vbox to\the\pgfutil@tempdima{\vfil\special{pdf: usexobj @pgfshade\the\pgfsys@objnum}}\hfil}}%
  }%
  \global\expandafter\let\csname @pgfshading#1!\endcsname=\pgfutil@tempa
  \global\advance\pgfsys@objnum\@ne
}%
\makeatother
\begin{document}
%\tracingmacros=1
\showoutput

\begin{tikzpicture}
  \shade[draw,shading=radial,%
   outer color=blue!30,%
   inner color=white] (0,0) rectangle (5,5);
\end{tikzpicture}%
\begin{tikzpicture}
  \shade[draw,shading=radial,%
   outer color=blue!30,%
   inner color=red] (0,0) rectangle (5,5);
\end{tikzpicture}%

\begin{tikzpicture}
 \node[circle,%
   shading=radial,%
   outer color=yellow!30,%
   inner color=white,%
   minimum width=10cm]
  {Test};
\end{tikzpicture}

\end{document}
```

**Comment by hmenke** [comment]
@u-fischer This is evidently a problem with the new hook system, because with `everyshi` the old `\pgfutil@insertatbegincurrentpagefrombox` was working just fine.  I'm not changing the driver, risking yet another regression which will also impact old versions.

**Comment by u-fischer** [comment]
@hmenke  the problem imho is that all this shipout patches uses different reference points. In the patch in issue #900 I had to shift the code by 1in left and up, because obviously somewhere in the depth of pgf or everyshi there was a shift in the other direction.  

` \pgfutil@insertatbegincurrentpagefrombox` is still working fine. It only place the code now at the wrong place. I don't think that there is much you can do apart from correcting the shift. 

You don't have to change the drivers. I suspect that `\pgfutil@insertatbegincurrentpagefrombox` is no longer needed with the new hooks, and that you would get simpler code without it, but as it works there is no need to rush to remove it or to remove it at all.

**Comment by hmenke** [comment]
Sorry, but that's not a solution. This driver also has to support Plain TeX and ConTeXt MkII.  For now PGF shadings will therefore remain broken with XeTeX.

**Comment by u-fischer** [comment]
@hmenke  my first suggestion above was to adapt the definition `\pgfutil@insertatbegincurrentpagefrombox`.  This command is defined in pgfutil-latex.def. You just changed this file to solve the two other issues, so where is the problem to adapt it for this issue a second time?

**Comment by hmenke** [comment]
But `\pgfutil@insertatbegincurrentpagefrombox` is used in the `dvipdfmx`, `dvips`, and `xetex` drivers.  Apart from such a change being a semantic nightmare, because then the macro doesn't do what is says anymore, is this guaranteed to work with all of them? Also what about `\pgfsys@fadingfrombox` and `\pgfsys@transparencygroupfrombox`?

**Comment by u-fischer** [comment]
I didn't change the semantic of the command. I only changed the shift amount. The old command does

~~~~
   \hskip-\pgf@temp\relax%
    #1%
~~~~

and the new

~~~~
    \hskip\dimexpr2in-2\hoffset-\pgf@temp\relax% changed
    #1%
    \hskip\dimexpr-2in-2\hoffset\relax% new
~~~~

**Comment by samcarter** [comment]
@hmenke  You'll get a box of chocolate if you release a new version to CTAN - a lot of beamer users have problems with missing bullets points etc.
