### ISSUE TITLE
Externalize does not work with the standalone class

### ISSUE THREAD

**Issue by judober** [pgf-tikz/pgf#932]
I have problems with externalize probably related to the latest pgf version.
MWE:
```
% !TeX TXS-program:compile = txs:///lualatex/[--shell-escape]	

\documentclass[class=report,11pt,a4paper,tikz,]{standalone}
\usepackage{tikz}
\usepackage{shellesc}
\usetikzlibrary{external}
\tikzexternalize[prefix=tikzfiles/]

\begin{document}
	\begin{tikzpicture}
	\draw (0,0) -- (1,1);
	\end{tikzpicture}%
\end{document}
```
I get
> ! Package tikz Error: Sorry, the system call 'lualatex -shell-escape -halt-on-e
rror -interaction=batchmode -jobname "tikzfiles/ExternalizeBroken-figure0" "\de
f\tikzexternalrealjob{ExternalizeBroken}\input{ExternalizeBroken}"' did NOT res
ult in a usable output file 'tikzfiles/ExternalizeBroken-figure0' (expected one
 of .pdf:.jpg:.jpeg:.png:). Please verify that you have enabled system calls. F
or pdflatex, this is 'pdflatex -shell-escape'. Sometimes it is also named 'writ
e 18' or something like that. Or maybe the command simply failed? Error message
s can be found in 'tikzfiles/ExternalizeBroken-figure0.log'. If you continue no
w, I'll try to typeset the picture.

In the main log.
Looking in the tikzfiles-folder .log I find

> \openout4 = tikzfiles/ExternalizeBroken-figure0.dpth
 [1
]
! Improper \prevdepth.
\newpage ...everypar {}\fi \par \ifdim \prevdepth 
                                                  >\z@ \vskip -\ifdim \prevd...
l.19 \end{document}

close to the end where I'm told

> !  ==> Fatal error occurred, no output PDF file produced!

May this be related to the new pgf version and is there anything I can do about it?

**Comment by hmenke** [comment]
My guess is that it's the LaTeX update. I haven't touched `externalize` in a while.

**Comment by judober** [comment]
I updated everything at once so this may very well be true. Any idea where I can file this bug? maybe I will just ask at stackexchange.

**Comment by u-fischer** [comment]
it fails for me also in miktex, which hasn't been updated for a month and so has neither the new latex (and I didn't use lualatex-dev, but lualatex), nor the new pgf.  With article.cls it compiles fine, and I don't see a reason to use standalone here, which only make the shipout more complicated without any gains.

**Comment by davidcarlisle** [comment]
Henri
I don't know tikz externalise well enough to fix but I get the same errors
in texlive 2018 and 2019 and 2020

the prevdepth error in tl 2020 and 2019


missing } error in tl 2018 and 2017

! Missing } inserted.
<inserted text>
                }
l.11 \end{document}


so it doesn't seem related to the update

**Comment by davidcarlisle** [comment]
See the same error reported here (with texlive 2019)

https://tex.stackexchange.com/questions/492981/compile-error-improper-prevdepth-from-epstopdf-when-trying-tikzcode-which-must/492987#492987

**Comment by judober** [comment]
> it fails for me also in miktex, which hasn't been updated for a month and so has neither the new latex (and I didn't use lualatex-dev, but lualatex), nor the new pgf. With article.cls it compiles fine, and I don't see a reason to use standalone here, which only make the shipout more complicated without any gains.

You are right, I didn't check for the relation to standalone. For my use case, my tikzpictures are in separate files and I create them using standalone as it is more comfortable than recompiling the whole document every time I change my pictures.

However, apparently my MWE was very bad. Here my improved version with two files:

file2:
```
% !TeX TXS-program:compile = txs:///lualatex/[--shell-escape]

\documentclass[class=report,11pt,a4paper,tikz,]{standalone}

\begin{document}
	\begin{tikzpicture}
	\draw (0,0) -- (1,1);
	\end{tikzpicture}%
\end{document}
```

file1:

```
% !TeX TXS-program:compile = txs:///lualatex/[--shell-escape]	

\documentclass[]{report}
\usepackage{tikz}
\usepackage{shellesc}
\usetikzlibrary{external}
\tikzexternalize[prefix=tikzfiles/]
\usepackage{standalone}

\begin{document}
\input{file2.tex}
\end{document}
```

Now, running file2 works but file1 does not.
I also checke on another machine with texlive 2020 but updated a while ago and there both work.

Edit: updated logs can be found on https://tex.stackexchange.com/questions/565269/tikz-externalize-broken

**Comment by judober** [comment]
It seems that this is not related to externalize but to standalone as explained on stackexchange.

**Comment by hmenke** [comment]
Thank you all for your comments. I agree that this is most likely related to the fact that the `standalone` class overrides the normal LaTeX output routine which `external` depends on.

**Comment by hmenke** [comment]
Fixed in https://github.com/latex3/latex3/commit/014272041f0b2719cc5c8b6c60363fa04e7435dc, I believe.
