### ISSUE TITLE
Plot small molecules with chemical bonds

### ISSUE THREAD

**Issue by copent** [pgf-tikz/pgf#936]
I want to plot small chemical molecules such as CO$_2$, I use \shade[ball color=red] (0,0) circle (2.3pt); to plot atoms, but I can't get the perfect results of chemical bonds between atoms, such as the attached figure.

![CO2](https://user-images.githubusercontent.com/50385516/95652440-7d5deb00-0b23-11eb-8e53-3c31fa63f31c.png)

**Comment by hmenke** [comment]
This is a bug tracker, not a Q&A site.  Please go to, e.g. https://tex.stackexchange.com/ for your request.
