### ISSUE TITLE
pgf - mathematical engine - a switch for detecting whether currently evaluation of a `\pgfmathparse`-expression is taking place

### ISSUE THREAD

**Issue by Ulrich-Diez** [pgf-tikz/pgf#945]
The following feature-request is closely related to my question  
["How to detect if expansion takes place while evaluating a \pgfmathparse-expression/if inside a \pgfmathparse-expression?"](https://tex.stackexchange.com/q/569781/118714)  
on TeX - LaTeX StackExchange.

---

I intend to write a macro which behaves differently depending on whether used 

- within a `\pgfmathparse`-expression while the `"`-operator is not in effect
- within a `\pgfmathparse`-expression while the `"`-operator is in effect
- outside a `\pgfmathparse`-expression.

The request is for the mathematical engine of PGF to bring along a reliable test or switch or flag or whatever which indicates if currently evaluation of a `\pgfmathparse`-expression is taking place and if so if currently things are processed while the `"`..`"`-operator is in effect..

Something like a macro ` \PGFmathNoQuoteOrQuoteOrElse`  with syntax

<pre><code>\PGFmathNoQuoteOrQuoteOrElse{&langle;tokens in case pgf-math expression is evaluated and "-operator is not in effect&rangle;}%
                            {&langle;tokens in case pgf-math expression is evaluated and "-operator is in effect&rangle;}%
                            {&langle;tokens in other cases&rangle;}</code></pre>

which can be used for defining something like:

    \documentclass{article}
    \usepackage[unicode]{hyperref}
    \usepackage{textgreek}
    \usepackage{tikz}
    
    \makeatletter
    \DeclareRobustCommand\MyNicePi{%
      \texorpdfstring{%
        \PGFmathNoQuoteOrQuoteOrElse{pi\@gobble}%
                                    {\unexpanded}%
                                    {\@firstofone}%
        {\ifmmode\expandafter\@firstoftwo\else\expandafter\@secondoftwo\fi{\pi}{\textpi}}%
      }{\9003\300}%
    }%
    \makeatother
    
    \begin{document}
    
    \leavevmode\MyNicePi{} is approximately
    \pgfmathparse{\MyNicePi}\pgfmathprintnumber[fixed, precision=3]{\pgfmathresult}\,.
    
    \pgfmathparse{"\MyNicePi"}\pgfmathresult
    
    \MyNicePi
    
    \end{document}

delivering the same as

    \documentclass{article}
    \usepackage[unicode]{hyperref}
    \usepackage{textgreek}
    \usepackage{tikz}
    
    \begin{document}
    
    \leavevmode\textpi{} is approximately
    \pgfmathparse{pi}\pgfmathprintnumber[fixed, precision=3]{\pgfmathresult}\,.
    
    \pgfmathparse{"\unexpanded{\textpi}"}\pgfmathresult
    
    \textpi
    
    \end{document}

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/QoLic.jpg

**Comment by hmenke** [comment]
You can easily detect whether you are inside `\pgfmathparse` by testing whether any of the internal variables is currently defined, e.g. `\pgfmath@parse@next` or `\pgfmath@token`.  Then you can formulate a test like
```latex
\def\@ifpgfmath@parsing{%
    \ifdefined\pgfmath@parse@next
        \expandafter\pgfutil@firstoftwo
    \else
        \expandafter\pgfutil@secondoftwo
    \fi
}
```
However, when you use it you must be aware that `\pgfmathparse` fully expands its argument on entry, i.e. you have to protect the test using `\noexpand` from being expanded immediately.  So this works:
```latex
\def\mypi{\noexpand\@ifpgfmath@parsing{pi}{\noexpand\pi}}

\pgfmathparse{\mypi}\pgfmathresult

$\mypi$
```
For the `"` operator you can't test, however, there is simply no way, because all the `"` operator does is push its argument as an operand onto the stack.  No expansion is performed so it is not possible to find out where the operand originally came from.

**Comment by ilayn** [comment]
You can locally test around it and immediately do something about it. But I don't think this is good enough for a feature.

```latex
\newif\ifpgfmath@parse@quote@parser@ineffect
\pgfmath@parse@quote@parser@ineffectfalse
\def\pgfmath@parse@prefix@operator{%
  \ifx\pgfmath@token\pgfmath@char@quote% Quote character.
    \pgfmath@parse@quote@parser@ineffecttrue
    \let\pgfmath@parse@next=\pgfmath@parse@operand@quote%
    \pgfmath@parse@quote@parser@ineffectfalse
  \else%
    \ifx\pgfmath@token\pgfmath@char@exclamation% Prefix !.
      \pgfmath@stack@push@operation{not}%
      \let\pgfmath@parse@next=\pgfmath@parse@@operand%
    \else% Anything else, just push and hope.
      \expandafter\pgfmath@stack@push@operation\expandafter{\pgfmath@token}%
      \let\pgfmath@parse@next=\pgfmath@parse@@operand%
    \fi%
  \fi%
  \pgfmath@parse@next%
}%
```

**Comment by hmenke** [comment]
No reply so I'm just closing this.  Please reopen if there is still interest.
