### ISSUE TITLE
Possible errata in pgfmanual

### ISSUE THREAD

**Issue by veotos** [pgf-tikz/pgf#948]
Hello there,
shouldn't be x radius and y radius \<factor\> instead of dimension?
https://github.com/pgf-tikz/pgf/blob/31544c850d52744475c83379cdb1ff10d5c4c80f/doc/generic/pgf/text-en/pgfmanual-en-tikz-coordinates.tex#L258-L264

Cheers

**Comment by hmenke** [comment]
No, it's a dimension. When you write `(xyz polar cs:angle=0,radius=1)` that is implicitly `(xyz polar cs:angle=0,radius=1cm)`.

**Comment by veotos** [comment]
Thank you for your quick reply.
Now then I'm confused. I can see a red line with following statement.
```
\draw[color= red] (xyz polar cs:angle=0,radius=1) -- (xyz polar cs:angle=0,radius=1cm);
```
What I'm missing?

**Comment by hmenke** [comment]
Then `1` probably becomes `1pt` in this context and not `1cm`, but it's definitely a dimension.

**Comment by veotos** [comment]
Thank you and sorry for the misunderstanding.

**Comment by muzimuzhi** [comment]
The `1` do becomes `1pt`, in which the unit `pt` is added by `\pgfmathsetlength`.

 - In parsing coordinate `(xyz polar cs:angle=0,radius=1)`, `\tikzset{/cs/radius=1}` is executed, which will store `1` in both `\tikz@cs@xradius` and `\tikz@cs@yradius`.
 - Then `\pgfpointpolar{\tikz@cs@angle}{\tikz@cs@xradius and \tikz@cs@yradius}` is executed, which will internally call `\pgfmathsetlength{\pgf@x}{\tikz@cs@xradius}`.
 - From the documentation of `\pgfmathsetlength{<register>}{<expression>}` (see `pgfmanual` v3.1.6a, sec. 94.1.1), when (i)`<expression>` does not start with a `+`, (ii) evaluating `<expression>` results in a dimensionless value, and (iii) unit `mu` is not encountered during evaluation, unit `pt` is appended.

**Comment by veotos** [comment]
Thanks a lot for the explanation.

**Comment by muzimuzhi** [comment]
> * From the documentation of `\pgfmathsetlength{<register>}{<expression>}` (see `pgfmanual` v3.1.6a, sec. 94.1.1), when (i)`<expression>` does not start with a `+`, (ii) evaluating `<expression>` results in a dimensionless value, and (iii) unit `mu` is not encountered during evaluation, unit `pt` is appended.

@veotos "(ii) evaluating `<expression>` results in a dimensionless value" was wrong. Evaluation of `<expression>` done by calling `\pgfmathparse{<expression>}` _always_ results in a dimensionless value.

For example, `\pgfmathparse{1pt}` will set `\pgfmathresult` to `1.0`.

**Comment by veotos** [comment]
Noted and thanks again.
