### ISSUE TITLE
pgfonlayer sets line width but doesn't restore after the scope ends

### ISSUE THREAD

**Issue by PhelypeOleinik** [pgf-tikz/pgf#950]
**Brief outline of the bug**

`\pgfonlayer` does:

https://github.com/pgf-tikz/pgf/blob/67295ec8a0958e6400d1873fc1ed56895d2f60cd/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex#L108

but the scope of `\pgfsetlinewidth` is global, so this affects the rest of the `tikzpicture` after the `\end{pgfonlayer}`.

**Minimal working example (MWE)**

```latex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{backgrounds}
\begin{document}

\begin{tikzpicture}[ultra thick]
  \draw[red] (0,0.5) -- (3,0.5);
  \draw (0,0) -- ++(1,1);
  \begin{pgfonlayer}{background}
    \draw (1,0) -- ++(1,1);
  \end{pgfonlayer}
  \draw (2,0) -- ++(1,1);
\end{tikzpicture}

\end{document}
```

![test](https://user-images.githubusercontent.com/12678598/99196081-d810e500-2768-11eb-8da2-b6f49ce9540c.png)

**Possible fix**

If this is indeed not the intended behaviour (it does seem weird to reset the line width, even only inside `pgfonlayer`, but):
```diff
diff --git a/usr/local/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex b/pgfcorelayers.code.tex
index 158f33d..57b4ffc 100644
--- a/usr/local/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex
+++ b/pgfcorelayers.code.tex
@@ -105,6 +105,7 @@
               \begingroup%
         }%
       \fi
+   \edef\pgf@saved@linewidth{\the\pgflinewidth}%
    \pgfsetlinewidth{0.4pt}% always reset the line width
    \pgf@temp
   }%
@@ -113,6 +114,7 @@
       \endgroup%
       \hss
     \egroup%
+   \pgfsetlinewidth{\pgf@saved@linewidth}%
   \endgroup
 }
```

**Comment by ilayn** [comment]
This is briefly explained on the `backgrounds` library docs. Main issue here is that you are mixing PGF layer and TikZ layer pictures without scoping. For example this doesn't suffer from the problem 

```latex
\usetikzlibrary{backgrounds}

\begin{tikzpicture}[ultra thick]
  \draw[red] (0,0.5) -- (3,0.5);
  \draw (0,0) -- ++(1,1);
  \begin{scope}[on background layer]
    \draw (1,0) -- ++(1,1);
  \end{scope}
  \draw (2,0) -- ++(1,1);
\end{tikzpicture}
```

PGF usage always comes with extra care for scopes and graphics states which is laborious.

**Comment by PhelypeOleinik** [comment]
Ah, so I should use with `scope` then.  Thanks!

I thought for a moment that `pgfonlayer` is “supported” TikZ syntax (apparently I didn't get the clue from the name :) That's what I get for shamelessly copying code from stackexchange :-)

I guess this can be `closed-invalid`?

**Comment by ilayn** [comment]
[Copy/paste](https://www.theguardian.com/technology/2020/feb/20/creator-of-copy-and-paste-command-larry-tesler-dies-aged-74) is what makes the world go around  so no problem at all.
