### ISSUE TITLE
Invalid gnuplot syntax in the manual

### ISSUE THREAD

**Issue by zadeck** [pgf-tikz/pgf#952]
Using the page and section numbers of the 3.1.7a manual, 
The last sentence of the first paragraph of section 22.4 on page 344 is wrong.   There is no "set terminal table" command in gnuplot.   The example in the third purple box down is correct when it says 'set table "../plots/....'.  There is no terminal type called table in gnuplot, only a 'set table' command that takes a operand of the file name.

Likewise the text in section 113.2.2 on page 1187 under the \pgfplotgnuplot command is wrong.   it should be 'set table "#1.table"; ...'

**Comment by hmenke** [comment]
Please choose a better title next time and use the issue template.

**Comment by zadeck** [comment]
I have worked in the open source community for several years.   One of the things that we prided ourselves on in the GCC community was not to bite the hands of first time submitters.  

I will not make this mistake again because i will never waste my time submitting another issue for this package.

Ken Zadeck

**Comment by hmenke** [comment]
I have no idea what's your problem.  I fixed your issue and asked you *nicely* to improve your report next time.

**Comment by zadeck** [comment]
It seemed as if you had just told me to get lost.  Thankyou for fixing 
it.   I will look for the proper procedures next time.

Kenny
