### ISSUE TITLE
random(9,0) is always 9

### ISSUE THREAD

**Issue by Symbol1** [pgf-tikz/pgf#954]
Version: 3.1.7.a; I guess it's irrelevant.

On page 1042, or equivalently [these two lines](https://github.com/pgf-tikz/pgf/blob/master/doc/generic/pgf/text-en/pgfmanual-en-math-parsing.tex#L1214-L1215),
it is stated that if two numbers `x`, `y` are given, a random integer between `x` and `y` is generated.
However, if `x` > `y`, the generated number is always `x`.
Perhaps we can
* state in doc that `x` < `y` is expected, or
* modify the codebase to reorder `x`, `y`.

### MWE
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
	\foreach\ind in{1,...,99}{
		\pgfmathparse{random(0,9)}\pgfmathresult
	}
	\foreach\ind in{1,...,99}{
		\pgfmathparse{random(9,0)}\pgfmathresult
	}
\end{document}
```

**Comment by hmenke** [comment]
I think the order should not matter, so I reclassified this from manual to pgfmath bug.
