### ISSUE TITLE
CI fails on every un-signed commits

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#962]
**Brief outline of the bug**

After https://github.com/pgf-tikz/pgf/commit/8fa12a65760dc5dcca9a3af0fb7cd348b703cf6d, CI always fails on un-signed commits. Hence when a user pushes such commits to their forked repository, he/she will keep receiving CI failure emails.

**Comment by hmenke** [comment]
Signed release will still be enforced.

**Comment by muzimuzhi** [comment]
thanks
