### ISSUE TITLE
Combinations of "reset cm" and "insert path" give various results

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#965]
**Brief outline of the bug**

@marmotghost To avoid adding too many possibly off-topic replies under #963, let's continue here.

Short warm-up: As discussed in #963, it is uncovered that different combinations of `reset cm` and `insert path` will give various results and it's hard to tell which one is the expected.

**Minimal working example (MWE)**

The interesting example from https://github.com/pgf-tikz/pgf/issues/963#issuecomment-748552765
```tex
\documentclass{article}
\usepackage{tikz}
\begin{document}

\tikzset{my key/.code={%
  \path[reset cm] coordinate (a);
}}

\begin{tikzpicture}
  \draw (0,0) grid (2,2);
  
  \tikzset{scale=1.5, xshift=1cm}
  \path coordinate[my key] (b);
  \path (a) node[circle,draw]{a} (b) node[circle,draw]{b};
\end{tikzpicture}

\tikzset{my key'/.style={insert path={%
 [reset cm] coordinate (a')
}}}

\begin{tikzpicture}
  \draw (0,0) grid (2,2);
  
  \tikzset{scale=1.5, xshift=1cm}
  \path coordinate[my key'] (b');
  \path (a') node[circle,draw]{a} (b') node[circle,draw]{b};
\end{tikzpicture}

\tikzset{my key''/.style={insert path={%
  coordinate[reset cm] (a'')
}}}

\begin{tikzpicture}
  \draw (0,0) grid (2,2);
  
  \tikzset{scale=1.5, xshift=1cm}
  \path coordinate[my key''] (b'');
  \path (a'') node[circle,draw]{a} (b'') node[circle,draw]{b};
\end{tikzpicture}

\tikzset{my key'''/.style={insert path={%
  [reset cm] coordinate[reset cm] (a''')
}}}

\begin{tikzpicture}
  \draw (0,0) grid (2,2);
  
  \tikzset{scale=1.5, xshift=1cm}
  \path coordinate[my key'''] (b''');
  \path (a''') node[circle,draw]{a} (b''') node[circle,draw]{b};
\end{tikzpicture}

\end{document}
```

**Comment by muzimuzhi** [comment]
On one hand, adding the `\pgfutil@empty` tester to `\tikz@addtransform` can reduce those 4 cases to 2 and put every nodes containing text `a` at the origin.
```tex
\def\tikz@addtransform#1{%
  \ifx\tikz@transform\relax
    #1%
  \else
    \ifx\tikz@transform\pgfutil@empty
      #1%
    \else
      \expandafter\def\expandafter\tikz@transform\expandafter{\tikz@transform#1}%
    \fi
  \fi
}%
```
![image](https://user-images.githubusercontent.com/6376638/102704700-c9fb3a80-42b9-11eb-9c24-b37ec75d95bf.png)


On the other hand, I find the doc for `insert path` already suggests to **not** use it as node options.
https://github.com/pgf-tikz/pgf/blob/88f5a0efce527de4af0c28f829dcb33411e98563/doc/generic/pgf/text-en/pgfmanual-en-tikz-paths.tex#L127-L132

Perhaps similar warning should be added to doc of `name intersections`, since an option list following fancy path operators (`node[...]`, `grid[...]`) and those used in normal places `\draw[...]` do play different roles and are executed in different "environments". Nesting node constructions just makes it too difficult to specify what are the current coordinate and transformation matrix, and what are the user expected ones (without a stack).

Finally, it is the style shared by `pgfmanual` and many other latex package manuals that most words are about "what you can do", and very few are about "what you'd better not to do". Users might easily think that everything documented (packages, environments, commands, options) are orthogonal (every possible combination should work). The fact is that the list of edge cases are just too long to be documented. Maintainers can do some, but for sure not all.

**Comment by marmotghost** [comment]
Thanks! You are totally right, I should *not* have used `insert path`. Indeed, using `prefix after command` instead yields much better results:
```
\documentclass{article}
\usepackage{tikz}
\begin{document}

\tikzset{my key/.code={%
  \path[reset cm] coordinate (a);
}}

\begin{tikzpicture}
  \draw (0,0) grid (2,2);
  
  \tikzset{scale=1.5, xshift=1cm}
  \path coordinate[my key] (b);
  \path (a) node[circle,draw]{a} (b) node[circle,draw]{b};
\end{tikzpicture}

\tikzset{my key'/.style={prefix after command={%
 [reset cm] coordinate (a')
}}}

\begin{tikzpicture}
  \draw (0,0) grid (2,2);
  
  \tikzset{scale=1.5, xshift=1cm}
  \path coordinate[my key'] (b');
  \path (a') node[circle,draw]{a} (b') node[circle,draw]{b};
\end{tikzpicture}

\tikzset{my key''/.style={prefix after command={%
  coordinate[reset cm] (a'')
}}}

\begin{tikzpicture}
  \draw (0,0) grid (2,2);
  
  \tikzset{scale=1.5, xshift=1cm}
  \path coordinate[my key''] (b'');
  \path (a'') node[circle,draw]{a} (b'') node[circle,draw]{b};
\end{tikzpicture}

\tikzset{my key'''/.style={prefix after command={%
  [reset cm] coordinate[reset cm] (a''')
}}}

\begin{tikzpicture}
  \draw (0,0) grid (2,2);
  
  \tikzset{scale=1.5, xshift=1cm}
  \path coordinate[my key'''] (b''');
  \path (a''') node[circle,draw]{a} (b''') node[circle,draw]{b};
\end{tikzpicture}

\end{document}
```

**Comment by hmenke** [comment]
What is actually the bug here?  Can we close this or not?
