### ISSUE TITLE
tikz math lib: three keywords are undocumented

### ISSUE THREAD

**Issue by muzimuzhi** [pgf-tikz/pgf#974]
Do they, especially the first two, worth/ready to be documented?

 - `count`: `count <variable>, <additional variables>;` will define every `<variable>` as a new count
 - `length`: `length <variable>, <additional variables>;` will define every `<variable>` as a new dimension
 - `point`: short version of `coordinate`

An example using `count` and `length`
```tex
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{math}

\begin{document}
\tikzmath{
  count \x;
  length \y;
  \x = 3;
  \y = 10pt;
}

\the\x, \the\y % get "3, 10.0pt"
\end{document}
```

https://github.com/pgf-tikz/pgf/blob/48c45ea5773094b8fb7f36522883cee9fdd48d44/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarymath.code.tex#L239-L248

Also note the spurious `\show` in line 247.

There are no other undocumented keywords in tikz `math` lib, and no other spurious `\show`s in code base.

**Comment by hmenke** [comment]
I think I'll actually remove these.  It is too tempting to do things like
```latex
\tikzmath{
  for \x in {1,...,100} {
    count \y;
    % ...
  }
}
```
and even though e-TeX has 65536 registers, if you do that a couple of times you might run out.

**Comment by ilayn** [comment]
Just leave them undocumented then?

**Comment by hmenke** [comment]
Sounds about right, wont-fix it is then.

**Comment by muzimuzhi** [comment]
Another interesting finding: the doc for keywords `point` had been always there in `pgfmanual-en-library-math.tex` but commented out,  since that file was added.
https://github.com/pgf-tikz/pgf/commit/d2d2f3d19768e2034aa20fbdaca39a570e2374bd#diff-e79249eb30be5ac9acb1ce491f1ae7a330c1ab277f1cc0baa9d73085e13130dbR318-R324
