### ISSUE TITLE
\draw command fails when \coordinate's included through \input

### ISSUE THREAD

**Issue by ahaselbacher** [pgf-tikz/pgf#982]
**Brief outline of the bug**

I have a figure in which I draw points whose coordinates are included through \input. This used to work fine until I updated my  
TeXLive 2020 distribution just now. The new distribution is:
- LaTeX2e <2020-10-01> patch level 4
- L3 programming layer <2021-01-09> xparse <2020-03-03> 
- tikz.sty 2020/12/27 v3.1.8b
- pgf.sty 2020/12/27 v3.1.8b

The old distribution was:
- LaTeX2e <2020-02-02> patch level 5
- L3 programming layer <2020-04-06>
- tikz.sty 2020/01/08 v3.1.5b
- pgf.sty 2020/01/08 v3.1.5b

IMPORTANT: The error that occurs is 

```
! Package hooks Error: ERROR! This should not happen. Tried to pop from an
(hooks)                empty file name stack.
(hooks)                Please report at https://github.com/latex3/latex2e.

Type <return> to continue.
 ...                                         
                                                  
l.9     \draw[fill] (\point) circle (1.0pt);
```

When I started entering the information in the latex2e GitHub repository, I was asked to add "\RequirePackage{latexbug}", in the MWE whose output then asked me to contact you. If this is not an issue with TikZ/pgf, please let me know.

**Minimal working example (MWE)**

```latex
\documentclass{article}

\usepackage{tikz}

\begin{document}

\begin{tikzpicture}
%%% this does not work (but used to work)
  \input{points.tex} 
    \draw[fill] (\point) circle (1.0pt);    

%%% this works, but I need to generate the points separately from how they 
%%% are plotted
%\coordinate (A) at (0.0,0.0);
%\coordinate (B) at (1.0,1.0);
%\foreach \point in {A,B}
%  \draw[fill] (\point) circle (1.0pt);    
\end{tikzpicture}

\end{document}
```
The file "points.tex" contains: 

```
\coordinate (A) at (0.0,0.0);
\coordinate (B) at (1.0,1.0);
\foreach \point in {A,B}
```

**Comment** 

I need to generate the points to be drawn using a separate code, which is why I input them through the file. I do not want to put the \draw command into the file because I want to be able to change the way the points are drawn (color, size) without having to edit, compile and rerun the code.

**Comment by josephwright** [comment]
Looks like it relates to file hooks: I'll ask the team to take a look

**Comment by hmenke** [comment]
This is not related to TikZ.  You can temporarily work around it by using
```latex
\csname @@input\endcsname{points.tex}
```

Also, I'm curious why you are reporting this here when the error message clearly says “Please report at https://github.com/latex3/latex2e”

**Comment by ahaselbacher** [comment]
As I mentioned, when I was about to report it to the LaTeX2e Github repository, the output of the latexbug package told me to contact the Ticks/pgf team.

**Comment by hmenke** [comment]
@josephwright 

MWE:
```latex
\begin{filecontents*}{collectarg.tex}
\collectarg
\end{filecontents*}
\documentclass{article}
\makeatletter
% just need something that skips spaces
\def\collectarg{\@ifnextchar\relax{\@collectarg}{\@collectarg}}
\def\@collectarg#1{#1 world!}
\makeatother
\begin{document}
\input{collectarg.tex}{hello}
\end{document}
```

**Comment by davidcarlisle** [comment]
@ahaselbacher  yes it's tricky to know where to report cross package issues. But there is a big enough overlap of people here that the issue has been seen by both teams we'll look....

Note that this is one reason why we don't mechanically force that all latex2e issues are rejected if latexbug.sty complains. Sometimes you need to submit anyway, just leave a note saying that the third party package (tikz here) is needed but you think the issue is in the format not the package_

**Comment by hmenke** [comment]
I've opened https://github.com/latex3/latex2e/issues/473 with a quick-and-dirty MWE, which doesn't reproduce the error shown here but exhibits other wonky output.

**Comment by davidcarlisle** [comment]
@ahaselbacher 

I think that a form that works with old and new formats is not to have the start of the loop syntax in the included file and the end in the main file so

in the main file have


```
    \input{points.tex} 
    \foreach \point in \pointlist
```

and in the input file have

```
\coordinate (A) at (0.0,0.0);
\coordinate (B) at (1.0,1.0);
\def\pointlist{A,B}
```

**Comment by ahaselbacher** [comment]
@davidcarlisle: 

- Thanks for suggesting a form that works with both systems. I'll implement it. 
- Regarding your other comment about cross package issues: I'll be happy to submit a separate bug report to the LaTeX2e team. Not sure based on your comment whether this is necessary.
