### ISSUE TITLE
Error in Apple silicon mac

### ISSUE THREAD

**Issue by githubmanic** [pgf-tikz/pgf#985]
Hi there,

My code got an error in Apple silicon mac. The same code worked in Intel Mac. Here is my beamer slide code:

`\begin{frame}{Frame title}`
`\begin{itemize}`
`\item One item`
`\end{itemize}`
`\begin{tikzpicture}`
`\node (keyname1) {\includegraphics[width=10cm]{graphicfile1}};`
`\onslide<2->{`
`\node (keyname2) [overlay=of keyname1] {\includegraphics[width=10cm]{graphicfile2}};`
`}`
`\end{tikzpicture}`
`\end{frame}`

When I typeset, the error message says `Package pgfkeys Error: Choice 'of keyname1' unknown in choice key '/tikz/overlay'. I am going to ignore this key.`

Could you give me any idea how to fix it?

I put the below lines in the beginning of the beamer code:
`\usepackage{tikz}`
`\usetikzlibrary{tikzmark,fit,shapes.geometric}`
`\usetikzlibrary{positioning}`
`\usetikzlibrary{arrows.meta}`
`\usetikzlibrary{decorations.pathreplacing,calc}`

**Comment by muzimuzhi** [comment]
Option `overlay` accepts either `true` or `false`, hence `overlay=of keyname1` is invalid, see `pgfmanual` v3.1.8b, sec. 17.13.1. Guess you want to use options from `positioning` library, like `above=of <node name>`. There are documented in `pgfmanual`, sec. 17.5.3.

Also Q&A sites like tex.stackexchange.com is more recommended for usage questions like this.

**Comment by githubmanic** [comment]
> Option `overlay` accepts either `true` or `false`, hence `overlay=of keyname1` is invalid, see `pgfmanual` v3.1.8b, sec. 17.13.1. Guess you want to use options from `positioning` library, like `above=of <node name>`. There are documented in `pgfmanual`, sec. 17.5.3.
> 
> Also Q&A sites like tex.stackexchange.com is more recommended for usage questions like this.

Thank you for your help. I would take a look at the manual you mentioned. Is there any specific reason that the same code worked in Intel Mac, but not work in Apple silicon Mac?

**Comment by hmenke** [comment]
The example you give would also not have compiled on an Intel Mac, because it is full of syntax errors and lacks basic structure such as `\documentclass`.

Further, TeX is an interpreted language, so PGF does not make any assumptions about the underlying architecture.  As far as I know, MacTeX (or TeX Live for that matter) is not yet available for Apple Silicon, meaning that it runs in Rosetta the exact same binaries as on Intel.

**Comment by githubmanic** [comment]
> The example you give would also not have compiled on an Intel Mac, because it is full of syntax errors and lacks basic structure such as `\documentclass`.
> 
> Further, TeX is an interpreted language, so PGF does not make any assumptions about the underlying architecture. As far as I know, MacTeX (or TeX Live for that matter) is not yet available for Apple Silicon, meaning that it runs in Rosetta the exact same binaries as on Intel.

Here is an working example to show the issue:

`\documentclass{beamer}`

`\usepackage{tikz}`
`\usetikzlibrary{tikzmark,fit,shapes.geometric}`
`\usetikzlibrary{positioning}`
`\usetikzlibrary{arrows.meta}`
`\usetikzlibrary{decorations.pathreplacing,calc}`

`\begin{document}`

`\begin{frame}{Frame title}`
`\begin{itemize}`
`\item One item`
`\end{itemize}`
`\begin{tikzpicture}`
`\node (keyname1) {before overlay};`
`\onslide<2->{`
`\node (keyname2) [overlay=of keyname1] {after overlay};`
`}`
`\end{tikzpicture}`
`\end{frame}`

`\end{document}`

The above code works on my old MacBook with Mac OS Sierra and MacTex2015. But, it does not work on my new M1 Macbook with Mac OS Big Sur and MacTex2020. Any idea?

**Comment by hmenke** [comment]
No, this is not a Q&A site. Go to https://tex.stackexchange.com/
