### ISSUE TITLE
.code 2 args optional argument

### ISSUE THREAD

**Issue by joel-coffman** [pgf-tikz/pgf#991]
**Brief outline of the bug**

According to the manual (version 3.1.8b), the key handler `.code 2 args` treats the second argument as optional:

> The second argument is optional: if it is not provided, it will be the empty string.

As shown in the minimal working example (below), the actual behavior doesn't match this statement. In particular, if the second argument isn't provided, then the first letter of the first argument is treated as the first argument, and the rest of the second argument is treated as the second argument.

This issue has also been noted in [comments to an answer](https://tex.stackexchange.com/a/39838) on https://tex.stackexchange.com/.

**Minimal working example (MWE)**

```latex
\documentclass{article}

  % Any preamble code goes here
\usepackage{pgf}

\begin{document}

  % Demonstration of issue here
\noindent
\pgfkeys{%
  example/.code 2 args={%
    First argument: `#1'; Second argument: `#2'\\
  },
  example={first}{second},
  example={first}{},
  example={first},  % <-- issue is here
}

\end{document}
```

produces the following:

> First argument: ‘first’; Second argument: ‘second’
> First argument: ‘first’; Second argument: ‘’
> First argument: ‘f’; Second argument: ‘irst’

where, based on the documentation, I'd expect the third line to match the second.

**Comment by hmenke** [comment]
Looks like the documentation is wrong here, because looking through the history of the implementation of `code 2 args`, this would have never worked.

**Comment by joel-coffman** [comment]
May I open a pull request to remove that line from the documentation?

**Comment by muzimuzhi** [comment]
This is the brace-striping problem in another form, also see #368. The doc of package [`expkv`](https://ctan.org/pkg/expkv) has some discussion about this problem.

For pgfkeys v3.1.8b, exactly three levels of braces are stripped.

```tex
\documentclass{article}
\usepackage[T1]{fontenc}
  % Any preamble code goes here
\usepackage{pgf}

\begin{document}

  % Demonstration of issue here
\noindent
\pgfkeys{%
  example/.code 2 args={%
    First argument: `\detokenize{#1}'; Second argument: `\detokenize{#2}'\\
  },
  example=first,
  example={first},  % <-- issue is here
  example={{first}},
  example={{{first}}},
  example={{{{first}}}}
}

\end{document}
```
produces

> First argument: \`f'; Second argument: \`irst'
> First argument: \`f'; Second argument: \`irst'
> First argument: \`f'; Second argument: \`irst'
> First argument: \`first'; Second argument: \`'
> First argument: \`{first}'; Second argument: \`'
