### ISSUE TITLE
dvips backend: blend group displaces text and graphics

### ISSUE THREAD

**Issue by mgieseki** [pgf-tikz/pgf#995]
**Brief outline of the bug**
When converting the below example using `latex` and `dvips`, text and graphics are displaced in the resulting PS file. The "X" is supposed to be placed inside the circle but appears outside. The issue goes away if `blend group = soft light` is removed from the `scope` environment.
`pdflatex`, in contrast, converts the example correctly. 

**Minimal working example (MWE)**
This is a reduced version of the [Venn diagram example](https://texample.net/tikz/examples/venn).
```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}
  \begin{scope}[blend group = soft light]
    \fill[red!30!white] (90:1.2) circle (2);
  \end{scope}
  \node at (90:2) {X};
\end{tikzpicture}
\end{document}
```
![venn](https://user-images.githubusercontent.com/3620467/109381204-217cde80-78d9-11eb-9212-8fdfcd41eeff.png)

**Comment by hmenke** [comment]
Yes, the dvips driver is pretty broken.

**Comment by agrahn** [comment]
@muzimuzhi Thank you! Your fix is exactly what is needed here. I failed to test this potential issue when I coded blendmode and transparency groups in the dvips driver. The following example adds a test with a transparency group and overlaid text that renders correctly too, after your fix has been applied. I would recommend to accept the proposed fix.

````latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
% example from https://texample.net/tikz/examples/venn/
\begin{tikzpicture}
  \begin{scope}[blend group=soft light]
    \fill[red!30!white]   ( 90:1.2) circle (2);
    \fill[green!30!white] (210:1.2) circle (2);
    \fill[blue!30!white]  (330:1.2) circle (2);
  \end{scope}
  \node at ( 90:2)    {Typography};
  \node at ( 210:2)   {Design};
  \node at ( 330:2)   {Coding};
  \node [font=\Large] {\LaTeX};
\end{tikzpicture}

%transparency group example
\begin{tikzpicture}
  \begin{scope}[transparency group, opacity=0.3]
    \filldraw [ultra thick, fill=red] (0,0) circle (1);
  \end{scope}
  \node [font=\Large] at (0,0) {\LaTeX};
\end{tikzpicture}
\end{document}
````
